// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: catalog.proto

package server

import (
	"context"

	"micro-server/services/catalog/internal/logic"
	"micro-server/services/catalog/internal/svc"
	"micro-server/services/catalog/pb"
)

type CatalogServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCatalogServer
}

func NewCatalogServer(svcCtx *svc.ServiceContext) *CatalogServer {
	return &CatalogServer{
		svcCtx: svcCtx,
	}
}

func (s *CatalogServer) Ping(ctx context.Context, in *pb.PingReq) (*pb.PingResp, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

// ---- 商品 ----
func (s *CatalogServer) CreateProduct(ctx context.Context, in *pb.CreateProductReq) (*pb.CreateProductResp, error) {
	l := logic.NewCreateProductLogic(ctx, s.svcCtx)
	return l.CreateProduct(in)
}

func (s *CatalogServer) ListProduct(ctx context.Context, in *pb.ListProductReq) (*pb.ListProductResp, error) {
	l := logic.NewListProductLogic(ctx, s.svcCtx)
	return l.ListProduct(in)
}

// ---- SKU ----
func (s *CatalogServer) CreateSKU(ctx context.Context, in *pb.CreateSKUReq) (*pb.CreateSKUResp, error) {
	l := logic.NewCreateSKULogic(ctx, s.svcCtx)
	return l.CreateSKU(in)
}

func (s *CatalogServer) ListSKU(ctx context.Context, in *pb.ListSKUReq) (*pb.ListSKUResp, error) {
	l := logic.NewListSKULogic(ctx, s.svcCtx)
	return l.ListSKU(in)
}

// ---- 价格（版本化）----
func (s *CatalogServer) SetPrice(ctx context.Context, in *pb.SetPriceReq) (*pb.SetPriceResp, error) {
	l := logic.NewSetPriceLogic(ctx, s.svcCtx)
	return l.SetPrice(in)
}

func (s *CatalogServer) ListPrice(ctx context.Context, in *pb.ListPriceReq) (*pb.ListPriceResp, error) {
	l := logic.NewListPriceLogic(ctx, s.svcCtx)
	return l.ListPrice(in)
}

// ---- 质保策略 ----
func (s *CatalogServer) UpsertWarrantyPolicy(ctx context.Context, in *pb.UpsertWarrantyPolicyReq) (*pb.UpsertWarrantyPolicyResp, error) {
	l := logic.NewUpsertWarrantyPolicyLogic(ctx, s.svcCtx)
	return l.UpsertWarrantyPolicy(in)
}

// ---- 场站模板（BOM）----
func (s *CatalogServer) CreateStationProduct(ctx context.Context, in *pb.CreateStationProductReq) (*pb.CreateStationProductResp, error) {
	l := logic.NewCreateStationProductLogic(ctx, s.svcCtx)
	return l.CreateStationProduct(in)
}

func (s *CatalogServer) GetStationProduct(ctx context.Context, in *pb.GetStationProductReq) (*pb.GetStationProductResp, error) {
	l := logic.NewGetStationProductLogic(ctx, s.svcCtx)
	return l.GetStationProduct(in)
}

func (s *CatalogServer) ListStationProduct(ctx context.Context, in *pb.ListStationProductReq) (*pb.ListStationProductResp, error) {
	l := logic.NewListStationProductLogic(ctx, s.svcCtx)
	return l.ListStationProduct(in)
}
