// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	contractTemplateFieldNames          = builder.RawFieldNames(&ContractTemplate{})
	contractTemplateRows                = strings.Join(contractTemplateFieldNames, ",")
	contractTemplateRowsExpectAutoSet   = strings.Join(stringx.Remove(contractTemplateFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	contractTemplateRowsWithPlaceHolder = strings.Join(stringx.Remove(contractTemplateFieldNames, "`template_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheContractTemplateTemplateIdPrefix   = "cache:contractTemplate:templateId:"
	cacheContractTemplateTenantIdCodePrefix = "cache:contractTemplate:tenantId:code:"
)

type (
	contractTemplateModel interface {
		Insert(ctx context.Context, data *ContractTemplate) (sql.Result, error)
		FindOne(ctx context.Context, templateId int64) (*ContractTemplate, error)
		FindOneByTenantIdCode(ctx context.Context, tenantId int64, code string) (*ContractTemplate, error)
		Update(ctx context.Context, data *ContractTemplate) error
		Delete(ctx context.Context, templateId int64) error
	}

	defaultContractTemplateModel struct {
		sqlc.CachedConn
		table string
	}

	ContractTemplate struct {
		TemplateId    int64          `db:"template_id"`    // 雪花 ID
		Code          string         `db:"code"`           // 模板编码（租户内唯一）
		Name          string         `db:"name"`           // 模板名称
		ContractType  string         `db:"contract_type"`  // SALES/STATION/SERVICE/FRAMEWORK/EXTENDED
		VariablesJson sql.NullString `db:"variables_json"` // 变量定义 [{key,label,required}]
		Body          string         `db:"body"`           // 模板正文（{{key}} 占位）
		Version       int64          `db:"version"`        // 模板版本（更新递增）
		Status        string         `db:"status"`         // ACTIVE/DISABLED
		TenantId      int64          `db:"tenant_id"`      // 租户 ID
		CreatedAt     time.Time      `db:"created_at"`     // 创建时间
		CreatedBy     sql.NullInt64  `db:"created_by"`     // 创建人 uid
		UpdatedAt     time.Time      `db:"updated_at"`     // 更新时间
		UpdatedBy     sql.NullInt64  `db:"updated_by"`     // 更新人 uid
		DeletedAt     sql.NullTime   `db:"deleted_at"`     // 软删标记(NULL=有效)
	}
)

func newContractTemplateModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultContractTemplateModel {
	return &defaultContractTemplateModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`contract_template`",
	}
}

func (m *defaultContractTemplateModel) Delete(ctx context.Context, templateId int64) error {
	data, err := m.FindOne(ctx, templateId)
	if err != nil {
		return err
	}

	contractTemplateTemplateIdKey := fmt.Sprintf("%s%v", cacheContractTemplateTemplateIdPrefix, templateId)
	contractTemplateTenantIdCodeKey := fmt.Sprintf("%s%v:%v", cacheContractTemplateTenantIdCodePrefix, data.TenantId, data.Code)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `template_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, templateId)
	}, contractTemplateTemplateIdKey, contractTemplateTenantIdCodeKey)
	return err
}

func (m *defaultContractTemplateModel) FindOne(ctx context.Context, templateId int64) (*ContractTemplate, error) {
	contractTemplateTemplateIdKey := fmt.Sprintf("%s%v", cacheContractTemplateTemplateIdPrefix, templateId)
	var resp ContractTemplate
	err := m.QueryRowCtx(ctx, &resp, contractTemplateTemplateIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `template_id` = ? limit 1", contractTemplateRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, templateId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultContractTemplateModel) FindOneByTenantIdCode(ctx context.Context, tenantId int64, code string) (*ContractTemplate, error) {
	contractTemplateTenantIdCodeKey := fmt.Sprintf("%s%v:%v", cacheContractTemplateTenantIdCodePrefix, tenantId, code)
	var resp ContractTemplate
	err := m.QueryRowIndexCtx(ctx, &resp, contractTemplateTenantIdCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `code` = ? limit 1", contractTemplateRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, code); err != nil {
			return nil, err
		}
		return resp.TemplateId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultContractTemplateModel) Insert(ctx context.Context, data *ContractTemplate) (sql.Result, error) {
	contractTemplateTemplateIdKey := fmt.Sprintf("%s%v", cacheContractTemplateTemplateIdPrefix, data.TemplateId)
	contractTemplateTenantIdCodeKey := fmt.Sprintf("%s%v:%v", cacheContractTemplateTenantIdCodePrefix, data.TenantId, data.Code)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, contractTemplateRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TemplateId, data.Code, data.Name, data.ContractType, data.VariablesJson, data.Body, data.Version, data.Status, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt)
	}, contractTemplateTemplateIdKey, contractTemplateTenantIdCodeKey)
	return ret, err
}

func (m *defaultContractTemplateModel) Update(ctx context.Context, newData *ContractTemplate) error {
	data, err := m.FindOne(ctx, newData.TemplateId)
	if err != nil {
		return err
	}

	contractTemplateTemplateIdKey := fmt.Sprintf("%s%v", cacheContractTemplateTemplateIdPrefix, data.TemplateId)
	contractTemplateTenantIdCodeKey := fmt.Sprintf("%s%v:%v", cacheContractTemplateTenantIdCodePrefix, data.TenantId, data.Code)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `template_id` = ?", m.table, contractTemplateRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Code, newData.Name, newData.ContractType, newData.VariablesJson, newData.Body, newData.Version, newData.Status, newData.TenantId, newData.CreatedBy, newData.UpdatedBy, newData.DeletedAt, newData.TemplateId)
	}, contractTemplateTemplateIdKey, contractTemplateTenantIdCodeKey)
	return err
}

func (m *defaultContractTemplateModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheContractTemplateTemplateIdPrefix, primary)
}

func (m *defaultContractTemplateModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `template_id` = ? limit 1", contractTemplateRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultContractTemplateModel) tableName() string {
	return m.table
}
