// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	warrantyExtensionFieldNames          = builder.RawFieldNames(&WarrantyExtension{})
	warrantyExtensionRows                = strings.Join(warrantyExtensionFieldNames, ",")
	warrantyExtensionRowsExpectAutoSet   = strings.Join(stringx.Remove(warrantyExtensionFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	warrantyExtensionRowsWithPlaceHolder = strings.Join(stringx.Remove(warrantyExtensionFieldNames, "`extension_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheWarrantyExtensionExtensionIdPrefix         = "cache:warrantyExtension:extensionId:"
	cacheWarrantyExtensionTenantIdExtensionNoPrefix = "cache:warrantyExtension:tenantId:extensionNo:"
)

type (
	warrantyExtensionModel interface {
		Insert(ctx context.Context, data *WarrantyExtension) (sql.Result, error)
		FindOne(ctx context.Context, extensionId int64) (*WarrantyExtension, error)
		FindOneByTenantIdExtensionNo(ctx context.Context, tenantId int64, extensionNo string) (*WarrantyExtension, error)
		Update(ctx context.Context, data *WarrantyExtension) error
		Delete(ctx context.Context, extensionId int64) error
	}

	defaultWarrantyExtensionModel struct {
		sqlc.CachedConn
		table string
	}

	WarrantyExtension struct {
		ExtensionId    int64          `db:"extension_id"`     // 雪花 ID
		ExtensionNo    string         `db:"extension_no"`     // 延保单号
		BaseWarrantyId int64          `db:"base_warranty_id"` // 衔接的原质保
		Months         int64          `db:"months"`           // 延长月数
		OrderNo        sql.NullString `db:"order_no"`         // 延保销售订单
		Amount         float64        `db:"amount"`           // 销售金额
		Status         string         `db:"status"`           // ACTIVE/TRANSFERRED/REFUNDED
		ToTargetType   sql.NullString `db:"to_target_type"`   // 转移目标类型
		ToTargetId     sql.NullInt64  `db:"to_target_id"`
		ToTargetKey    sql.NullString `db:"to_target_key"`
		RefundNo       sql.NullString `db:"refund_no"`  // 退款单号（退款联动 finance）
		TenantId       int64          `db:"tenant_id"`  // 租户 ID
		CreatedAt      time.Time      `db:"created_at"` // 创建时间
		CreatedBy      sql.NullInt64  `db:"created_by"` // 创建人 uid
		UpdatedAt      time.Time      `db:"updated_at"` // 更新时间
		UpdatedBy      sql.NullInt64  `db:"updated_by"` // 更新人 uid
		DeletedAt      sql.NullTime   `db:"deleted_at"` // 软删标记(NULL=有效)
	}
)

func newWarrantyExtensionModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultWarrantyExtensionModel {
	return &defaultWarrantyExtensionModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`warranty_extension`",
	}
}

func (m *defaultWarrantyExtensionModel) Delete(ctx context.Context, extensionId int64) error {
	data, err := m.FindOne(ctx, extensionId)
	if err != nil {
		return err
	}

	warrantyExtensionExtensionIdKey := fmt.Sprintf("%s%v", cacheWarrantyExtensionExtensionIdPrefix, extensionId)
	warrantyExtensionTenantIdExtensionNoKey := fmt.Sprintf("%s%v:%v", cacheWarrantyExtensionTenantIdExtensionNoPrefix, data.TenantId, data.ExtensionNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `extension_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, extensionId)
	}, warrantyExtensionExtensionIdKey, warrantyExtensionTenantIdExtensionNoKey)
	return err
}

func (m *defaultWarrantyExtensionModel) FindOne(ctx context.Context, extensionId int64) (*WarrantyExtension, error) {
	warrantyExtensionExtensionIdKey := fmt.Sprintf("%s%v", cacheWarrantyExtensionExtensionIdPrefix, extensionId)
	var resp WarrantyExtension
	err := m.QueryRowCtx(ctx, &resp, warrantyExtensionExtensionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `extension_id` = ? limit 1", warrantyExtensionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, extensionId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWarrantyExtensionModel) FindOneByTenantIdExtensionNo(ctx context.Context, tenantId int64, extensionNo string) (*WarrantyExtension, error) {
	warrantyExtensionTenantIdExtensionNoKey := fmt.Sprintf("%s%v:%v", cacheWarrantyExtensionTenantIdExtensionNoPrefix, tenantId, extensionNo)
	var resp WarrantyExtension
	err := m.QueryRowIndexCtx(ctx, &resp, warrantyExtensionTenantIdExtensionNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `extension_no` = ? limit 1", warrantyExtensionRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, extensionNo); err != nil {
			return nil, err
		}
		return resp.ExtensionId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWarrantyExtensionModel) Insert(ctx context.Context, data *WarrantyExtension) (sql.Result, error) {
	warrantyExtensionExtensionIdKey := fmt.Sprintf("%s%v", cacheWarrantyExtensionExtensionIdPrefix, data.ExtensionId)
	warrantyExtensionTenantIdExtensionNoKey := fmt.Sprintf("%s%v:%v", cacheWarrantyExtensionTenantIdExtensionNoPrefix, data.TenantId, data.ExtensionNo)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, warrantyExtensionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ExtensionId, data.ExtensionNo, data.BaseWarrantyId, data.Months, data.OrderNo, data.Amount, data.Status, data.ToTargetType, data.ToTargetId, data.ToTargetKey, data.RefundNo, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt)
	}, warrantyExtensionExtensionIdKey, warrantyExtensionTenantIdExtensionNoKey)
	return ret, err
}

func (m *defaultWarrantyExtensionModel) Update(ctx context.Context, newData *WarrantyExtension) error {
	data, err := m.FindOne(ctx, newData.ExtensionId)
	if err != nil {
		return err
	}

	warrantyExtensionExtensionIdKey := fmt.Sprintf("%s%v", cacheWarrantyExtensionExtensionIdPrefix, data.ExtensionId)
	warrantyExtensionTenantIdExtensionNoKey := fmt.Sprintf("%s%v:%v", cacheWarrantyExtensionTenantIdExtensionNoPrefix, data.TenantId, data.ExtensionNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `extension_id` = ?", m.table, warrantyExtensionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ExtensionNo, newData.BaseWarrantyId, newData.Months, newData.OrderNo, newData.Amount, newData.Status, newData.ToTargetType, newData.ToTargetId, newData.ToTargetKey, newData.RefundNo, newData.TenantId, newData.CreatedBy, newData.UpdatedBy, newData.DeletedAt, newData.ExtensionId)
	}, warrantyExtensionExtensionIdKey, warrantyExtensionTenantIdExtensionNoKey)
	return err
}

func (m *defaultWarrantyExtensionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheWarrantyExtensionExtensionIdPrefix, primary)
}

func (m *defaultWarrantyExtensionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `extension_id` = ? limit 1", warrantyExtensionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultWarrantyExtensionModel) tableName() string {
	return m.table
}
