// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	warrantyFieldNames          = builder.RawFieldNames(&Warranty{})
	warrantyRows                = strings.Join(warrantyFieldNames, ",")
	warrantyRowsExpectAutoSet   = strings.Join(stringx.Remove(warrantyFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	warrantyRowsWithPlaceHolder = strings.Join(stringx.Remove(warrantyFieldNames, "`warranty_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheWarrantyWarrantyIdPrefix         = "cache:warranty:warrantyId:"
	cacheWarrantyTenantIdWarrantyNoPrefix = "cache:warranty:tenantId:warrantyNo:"
)

type (
	warrantyModel interface {
		Insert(ctx context.Context, data *Warranty) (sql.Result, error)
		FindOne(ctx context.Context, warrantyId int64) (*Warranty, error)
		FindOneByTenantIdWarrantyNo(ctx context.Context, tenantId int64, warrantyNo string) (*Warranty, error)
		Update(ctx context.Context, data *Warranty) error
		Delete(ctx context.Context, warrantyId int64) error
	}

	defaultWarrantyModel struct {
		sqlc.CachedConn
		table string
	}

	Warranty struct {
		WarrantyId int64          `db:"warranty_id"` // 雪花 ID
		WarrantyNo string         `db:"warranty_no"` // 质保编号
		Level      string         `db:"level"`       // STATION/DEVICE 双层
		TargetType string         `db:"target_type"` // STATION/DEVICE
		TargetId   int64          `db:"target_id"`   // 目标 ID（SN 起算时 device_id S6 回填）
		TargetKey  string         `db:"target_key"`  // 目标键（SN / 场站编号）
		Status     string         `db:"status"`      // PENDING/ACTIVE/EXPIRED/REFUNDED
		StartAt    sql.NullTime   `db:"start_at"`    // 起算时刻（事件驱动写入）
		EndAt      sql.NullTime   `db:"end_at"`      // 到期时刻（start_at + months）
		Months     int64          `db:"months"`      // 质保月数
		StartRule  sql.NullString `db:"start_rule"`  // 起算规则快照 {"event":"shipment_signed","months":24}
		SourceType string         `db:"source_type"` // ORDER/EXTENSION
		SourceNo   sql.NullString `db:"source_no"`   // 来源单号
		TenantId   int64          `db:"tenant_id"`   // 租户 ID
		CreatedAt  time.Time      `db:"created_at"`  // 创建时间
		CreatedBy  sql.NullInt64  `db:"created_by"`  // 创建人 uid
		UpdatedAt  time.Time      `db:"updated_at"`  // 更新时间
		UpdatedBy  sql.NullInt64  `db:"updated_by"`  // 更新人 uid
		DeletedAt  sql.NullTime   `db:"deleted_at"`  // 软删标记(NULL=有效)
	}
)

func newWarrantyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultWarrantyModel {
	return &defaultWarrantyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`warranty`",
	}
}

func (m *defaultWarrantyModel) Delete(ctx context.Context, warrantyId int64) error {
	data, err := m.FindOne(ctx, warrantyId)
	if err != nil {
		return err
	}

	warrantyTenantIdWarrantyNoKey := fmt.Sprintf("%s%v:%v", cacheWarrantyTenantIdWarrantyNoPrefix, data.TenantId, data.WarrantyNo)
	warrantyWarrantyIdKey := fmt.Sprintf("%s%v", cacheWarrantyWarrantyIdPrefix, warrantyId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `warranty_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, warrantyId)
	}, warrantyTenantIdWarrantyNoKey, warrantyWarrantyIdKey)
	return err
}

func (m *defaultWarrantyModel) FindOne(ctx context.Context, warrantyId int64) (*Warranty, error) {
	warrantyWarrantyIdKey := fmt.Sprintf("%s%v", cacheWarrantyWarrantyIdPrefix, warrantyId)
	var resp Warranty
	err := m.QueryRowCtx(ctx, &resp, warrantyWarrantyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `warranty_id` = ? limit 1", warrantyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, warrantyId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWarrantyModel) FindOneByTenantIdWarrantyNo(ctx context.Context, tenantId int64, warrantyNo string) (*Warranty, error) {
	warrantyTenantIdWarrantyNoKey := fmt.Sprintf("%s%v:%v", cacheWarrantyTenantIdWarrantyNoPrefix, tenantId, warrantyNo)
	var resp Warranty
	err := m.QueryRowIndexCtx(ctx, &resp, warrantyTenantIdWarrantyNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `warranty_no` = ? limit 1", warrantyRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, warrantyNo); err != nil {
			return nil, err
		}
		return resp.WarrantyId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWarrantyModel) Insert(ctx context.Context, data *Warranty) (sql.Result, error) {
	warrantyTenantIdWarrantyNoKey := fmt.Sprintf("%s%v:%v", cacheWarrantyTenantIdWarrantyNoPrefix, data.TenantId, data.WarrantyNo)
	warrantyWarrantyIdKey := fmt.Sprintf("%s%v", cacheWarrantyWarrantyIdPrefix, data.WarrantyId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, warrantyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.WarrantyId, data.WarrantyNo, data.Level, data.TargetType, data.TargetId, data.TargetKey, data.Status, data.StartAt, data.EndAt, data.Months, data.StartRule, data.SourceType, data.SourceNo, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt)
	}, warrantyTenantIdWarrantyNoKey, warrantyWarrantyIdKey)
	return ret, err
}

func (m *defaultWarrantyModel) Update(ctx context.Context, newData *Warranty) error {
	data, err := m.FindOne(ctx, newData.WarrantyId)
	if err != nil {
		return err
	}

	warrantyTenantIdWarrantyNoKey := fmt.Sprintf("%s%v:%v", cacheWarrantyTenantIdWarrantyNoPrefix, data.TenantId, data.WarrantyNo)
	warrantyWarrantyIdKey := fmt.Sprintf("%s%v", cacheWarrantyWarrantyIdPrefix, data.WarrantyId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `warranty_id` = ?", m.table, warrantyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.WarrantyNo, newData.Level, newData.TargetType, newData.TargetId, newData.TargetKey, newData.Status, newData.StartAt, newData.EndAt, newData.Months, newData.StartRule, newData.SourceType, newData.SourceNo, newData.TenantId, newData.CreatedBy, newData.UpdatedBy, newData.DeletedAt, newData.WarrantyId)
	}, warrantyTenantIdWarrantyNoKey, warrantyWarrantyIdKey)
	return err
}

func (m *defaultWarrantyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheWarrantyWarrantyIdPrefix, primary)
}

func (m *defaultWarrantyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `warranty_id` = ? limit 1", warrantyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultWarrantyModel) tableName() string {
	return m.table
}
