// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: finance.proto

package server

import (
	"context"

	"micro-server/services/finance/internal/logic"
	"micro-server/services/finance/internal/svc"
	"micro-server/services/finance/pb"
)

type FinanceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFinanceServer
}

func NewFinanceServer(svcCtx *svc.ServiceContext) *FinanceServer {
	return &FinanceServer{
		svcCtx: svcCtx,
	}
}

func (s *FinanceServer) Ping(ctx context.Context, in *pb.PingReq) (*pb.PingResp, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

// ---- 支付单 ----
func (s *FinanceServer) CreatePayment(ctx context.Context, in *pb.CreatePaymentReq) (*pb.CreatePaymentResp, error) {
	l := logic.NewCreatePaymentLogic(ctx, s.svcCtx)
	return l.CreatePayment(in)
}

func (s *FinanceServer) ConfirmPayment(ctx context.Context, in *pb.ConfirmPaymentReq) (*pb.ConfirmPaymentResp, error) {
	l := logic.NewConfirmPaymentLogic(ctx, s.svcCtx)
	return l.ConfirmPayment(in)
}

func (s *FinanceServer) ApprovePayment(ctx context.Context, in *pb.ApprovePaymentReq) (*pb.ApprovePaymentResp, error) {
	l := logic.NewApprovePaymentLogic(ctx, s.svcCtx)
	return l.ApprovePayment(in)
}

func (s *FinanceServer) SettlePayment(ctx context.Context, in *pb.SettlePaymentReq) (*pb.SettlePaymentResp, error) {
	l := logic.NewSettlePaymentLogic(ctx, s.svcCtx)
	return l.SettlePayment(in)
}

func (s *FinanceServer) GetPayment(ctx context.Context, in *pb.GetPaymentReq) (*pb.GetPaymentResp, error) {
	l := logic.NewGetPaymentLogic(ctx, s.svcCtx)
	return l.GetPayment(in)
}

func (s *FinanceServer) ListPayment(ctx context.Context, in *pb.ListPaymentReq) (*pb.ListPaymentResp, error) {
	l := logic.NewListPaymentLogic(ctx, s.svcCtx)
	return l.ListPayment(in)
}

// ---- 渠道 ----
func (s *FinanceServer) WechatPayURL(ctx context.Context, in *pb.WechatPayURLReq) (*pb.WechatPayURLResp, error) {
	l := logic.NewWechatPayURLLogic(ctx, s.svcCtx)
	return l.WechatPayURL(in)
}

func (s *FinanceServer) WechatCallback(ctx context.Context, in *pb.WechatCallbackReq) (*pb.WechatCallbackResp, error) {
	l := logic.NewWechatCallbackLogic(ctx, s.svcCtx)
	return l.WechatCallback(in)
}

func (s *FinanceServer) AlipayPayURL(ctx context.Context, in *pb.AlipayPayURLReq) (*pb.AlipayPayURLResp, error) {
	l := logic.NewAlipayPayURLLogic(ctx, s.svcCtx)
	return l.AlipayPayURL(in)
}

func (s *FinanceServer) AlipayCallback(ctx context.Context, in *pb.AlipayCallbackReq) (*pb.AlipayCallbackResp, error) {
	l := logic.NewAlipayCallbackLogic(ctx, s.svcCtx)
	return l.AlipayCallback(in)
}

// ---- 退款 ----
func (s *FinanceServer) CreateRefund(ctx context.Context, in *pb.CreateRefundReq) (*pb.CreateRefundResp, error) {
	l := logic.NewCreateRefundLogic(ctx, s.svcCtx)
	return l.CreateRefund(in)
}

func (s *FinanceServer) ListRefund(ctx context.Context, in *pb.ListRefundReq) (*pb.ListRefundResp, error) {
	l := logic.NewListRefundLogic(ctx, s.svcCtx)
	return l.ListRefund(in)
}

// ---- 发票（ISSUED/REVERSED 状态机桩，FR-FIN-004）----
func (s *FinanceServer) IssueInvoice(ctx context.Context, in *pb.IssueInvoiceReq) (*pb.IssueInvoiceResp, error) {
	l := logic.NewIssueInvoiceLogic(ctx, s.svcCtx)
	return l.IssueInvoice(in)
}

func (s *FinanceServer) ReverseInvoice(ctx context.Context, in *pb.ReverseInvoiceReq) (*pb.ReverseInvoiceResp, error) {
	l := logic.NewReverseInvoiceLogic(ctx, s.svcCtx)
	return l.ReverseInvoice(in)
}

func (s *FinanceServer) ListInvoice(ctx context.Context, in *pb.ListInvoiceReq) (*pb.ListInvoiceResp, error) {
	l := logic.NewListInvoiceLogic(ctx, s.svcCtx)
	return l.ListInvoice(in)
}

// ---- 对账任务（FR-FIN-003，差异修复只允许补投递重放，E10）----
func (s *FinanceServer) CreateReconcileTask(ctx context.Context, in *pb.CreateReconcileTaskReq) (*pb.CreateReconcileTaskResp, error) {
	l := logic.NewCreateReconcileTaskLogic(ctx, s.svcCtx)
	return l.CreateReconcileTask(in)
}

func (s *FinanceServer) ResolveReconcileTask(ctx context.Context, in *pb.ResolveReconcileTaskReq) (*pb.ResolveReconcileTaskResp, error) {
	l := logic.NewResolveReconcileTaskLogic(ctx, s.svcCtx)
	return l.ResolveReconcileTask(in)
}

func (s *FinanceServer) ListReconcileTask(ctx context.Context, in *pb.ListReconcileTaskReq) (*pb.ListReconcileTaskResp, error) {
	l := logic.NewListReconcileTaskLogic(ctx, s.svcCtx)
	return l.ListReconcileTask(in)
}
