// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: order.proto

package server

import (
	"context"

	"micro-server/services/order/internal/logic"
	"micro-server/services/order/internal/svc"
	"micro-server/services/order/pb"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) Ping(ctx context.Context, in *pb.PingReq) (*pb.PingResp, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

// ---- 订单 ----
func (s *OrderServer) CreateOrder(ctx context.Context, in *pb.CreateOrderReq) (*pb.CreateOrderResp, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *OrderServer) GetOrder(ctx context.Context, in *pb.GetOrderReq) (*pb.GetOrderResp, error) {
	l := logic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}

func (s *OrderServer) ListOrder(ctx context.Context, in *pb.ListOrderReq) (*pb.ListOrderResp, error) {
	l := logic.NewListOrderLogic(ctx, s.svcCtx)
	return l.ListOrder(in)
}

func (s *OrderServer) PayOrder(ctx context.Context, in *pb.PayOrderReq) (*pb.PayOrderResp, error) {
	l := logic.NewPayOrderLogic(ctx, s.svcCtx)
	return l.PayOrder(in)
}

func (s *OrderServer) CancelOrder(ctx context.Context, in *pb.CancelOrderReq) (*pb.CancelOrderResp, error) {
	l := logic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}

// ---- Saga ----
func (s *OrderServer) GetSaga(ctx context.Context, in *pb.GetSagaReq) (*pb.GetSagaResp, error) {
	l := logic.NewGetSagaLogic(ctx, s.svcCtx)
	return l.GetSaga(in)
}

func (s *OrderServer) RetrySaga(ctx context.Context, in *pb.RetrySagaReq) (*pb.RetrySagaResp, error) {
	l := logic.NewRetrySagaLogic(ctx, s.svcCtx)
	return l.RetrySaga(in)
}

// ---- 退货（FR-ORD-004：申请/审核/退款联动）----
func (s *OrderServer) CreateReturnOrder(ctx context.Context, in *pb.CreateReturnOrderReq) (*pb.CreateReturnOrderResp, error) {
	l := logic.NewCreateReturnOrderLogic(ctx, s.svcCtx)
	return l.CreateReturnOrder(in)
}

func (s *OrderServer) ApproveReturnOrder(ctx context.Context, in *pb.ApproveReturnOrderReq) (*pb.ApproveReturnOrderResp, error) {
	l := logic.NewApproveReturnOrderLogic(ctx, s.svcCtx)
	return l.ApproveReturnOrder(in)
}

// ---- 发货单与物流轨迹（FR-ORD-005，轨迹手工录入基线）----
func (s *OrderServer) CreateShipment(ctx context.Context, in *pb.CreateShipmentReq) (*pb.CreateShipmentResp, error) {
	l := logic.NewCreateShipmentLogic(ctx, s.svcCtx)
	return l.CreateShipment(in)
}

func (s *OrderServer) AddShipmentTrace(ctx context.Context, in *pb.AddShipmentTraceReq) (*pb.AddShipmentTraceResp, error) {
	l := logic.NewAddShipmentTraceLogic(ctx, s.svcCtx)
	return l.AddShipmentTrace(in)
}

func (s *OrderServer) ConfirmShipmentSigned(ctx context.Context, in *pb.ConfirmShipmentSignedReq) (*pb.ConfirmShipmentSignedResp, error) {
	l := logic.NewConfirmShipmentSignedLogic(ctx, s.svcCtx)
	return l.ConfirmShipmentSigned(in)
}

// ---- 统计 ----
func (s *OrderServer) SumPaidSales(ctx context.Context, in *pb.SumPaidSalesReq) (*pb.SumPaidSalesResp, error) {
	l := logic.NewSumPaidSalesLogic(ctx, s.svcCtx)
	return l.SumPaidSales(in)
}
