// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	invoiceFieldNames          = builder.RawFieldNames(&Invoice{})
	invoiceRows                = strings.Join(invoiceFieldNames, ",")
	invoiceRowsExpectAutoSet   = strings.Join(stringx.Remove(invoiceFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	invoiceRowsWithPlaceHolder = strings.Join(stringx.Remove(invoiceFieldNames, "`invoice_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheInvoiceInvoiceIdPrefix         = "cache:invoice:invoiceId:"
	cacheInvoiceTenantIdInvoiceNoPrefix = "cache:invoice:tenantId:invoiceNo:"
)

type (
	invoiceModel interface {
		Insert(ctx context.Context, data *Invoice) (sql.Result, error)
		FindOne(ctx context.Context, invoiceId int64) (*Invoice, error)
		FindOneByTenantIdInvoiceNo(ctx context.Context, tenantId int64, invoiceNo string) (*Invoice, error)
		Update(ctx context.Context, data *Invoice) error
		Delete(ctx context.Context, invoiceId int64) error
	}

	defaultInvoiceModel struct {
		sqlc.CachedConn
		table string
	}

	Invoice struct {
		InvoiceId     int64          `db:"invoice_id"`     // 雪花 ID
		InvoiceNo     string         `db:"invoice_no"`     // 发票号
		PaymentNo     string         `db:"payment_no"`     // 关联支付单
		OrderNo       string         `db:"order_no"`       // 关联订单
		Title         string         `db:"title"`          // 抬头
		TaxNo         sql.NullString `db:"tax_no"`         // 税号
		Amount        float64        `db:"amount"`         // 开票金额
		Status        string         `db:"status"`         // ISSUED/REVERSED
		ReverseReason sql.NullString `db:"reverse_reason"` // 红冲原因
		ReversedAt    sql.NullTime   `db:"reversed_at"`
		TenantId      int64          `db:"tenant_id"`  // 租户 ID
		CreatedAt     time.Time      `db:"created_at"` // 创建时间
		CreatedBy     sql.NullInt64  `db:"created_by"` // 创建人 uid
		UpdatedAt     time.Time      `db:"updated_at"` // 更新时间
		UpdatedBy     sql.NullInt64  `db:"updated_by"` // 更新人 uid
		DeletedAt     sql.NullTime   `db:"deleted_at"` // 软删标记(NULL=有效)
	}
)

func newInvoiceModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultInvoiceModel {
	return &defaultInvoiceModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`invoice`",
	}
}

func (m *defaultInvoiceModel) Delete(ctx context.Context, invoiceId int64) error {
	data, err := m.FindOne(ctx, invoiceId)
	if err != nil {
		return err
	}

	invoiceInvoiceIdKey := fmt.Sprintf("%s%v", cacheInvoiceInvoiceIdPrefix, invoiceId)
	invoiceTenantIdInvoiceNoKey := fmt.Sprintf("%s%v:%v", cacheInvoiceTenantIdInvoiceNoPrefix, data.TenantId, data.InvoiceNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `invoice_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, invoiceId)
	}, invoiceInvoiceIdKey, invoiceTenantIdInvoiceNoKey)
	return err
}

func (m *defaultInvoiceModel) FindOne(ctx context.Context, invoiceId int64) (*Invoice, error) {
	invoiceInvoiceIdKey := fmt.Sprintf("%s%v", cacheInvoiceInvoiceIdPrefix, invoiceId)
	var resp Invoice
	err := m.QueryRowCtx(ctx, &resp, invoiceInvoiceIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `invoice_id` = ? limit 1", invoiceRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, invoiceId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInvoiceModel) FindOneByTenantIdInvoiceNo(ctx context.Context, tenantId int64, invoiceNo string) (*Invoice, error) {
	invoiceTenantIdInvoiceNoKey := fmt.Sprintf("%s%v:%v", cacheInvoiceTenantIdInvoiceNoPrefix, tenantId, invoiceNo)
	var resp Invoice
	err := m.QueryRowIndexCtx(ctx, &resp, invoiceTenantIdInvoiceNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `invoice_no` = ? limit 1", invoiceRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, invoiceNo); err != nil {
			return nil, err
		}
		return resp.InvoiceId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInvoiceModel) Insert(ctx context.Context, data *Invoice) (sql.Result, error) {
	invoiceInvoiceIdKey := fmt.Sprintf("%s%v", cacheInvoiceInvoiceIdPrefix, data.InvoiceId)
	invoiceTenantIdInvoiceNoKey := fmt.Sprintf("%s%v:%v", cacheInvoiceTenantIdInvoiceNoPrefix, data.TenantId, data.InvoiceNo)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, invoiceRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.InvoiceId, data.InvoiceNo, data.PaymentNo, data.OrderNo, data.Title, data.TaxNo, data.Amount, data.Status, data.ReverseReason, data.ReversedAt, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt)
	}, invoiceInvoiceIdKey, invoiceTenantIdInvoiceNoKey)
	return ret, err
}

func (m *defaultInvoiceModel) Update(ctx context.Context, newData *Invoice) error {
	data, err := m.FindOne(ctx, newData.InvoiceId)
	if err != nil {
		return err
	}

	invoiceInvoiceIdKey := fmt.Sprintf("%s%v", cacheInvoiceInvoiceIdPrefix, data.InvoiceId)
	invoiceTenantIdInvoiceNoKey := fmt.Sprintf("%s%v:%v", cacheInvoiceTenantIdInvoiceNoPrefix, data.TenantId, data.InvoiceNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `invoice_id` = ?", m.table, invoiceRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.InvoiceNo, newData.PaymentNo, newData.OrderNo, newData.Title, newData.TaxNo, newData.Amount, newData.Status, newData.ReverseReason, newData.ReversedAt, newData.TenantId, newData.CreatedBy, newData.UpdatedBy, newData.DeletedAt, newData.InvoiceId)
	}, invoiceInvoiceIdKey, invoiceTenantIdInvoiceNoKey)
	return err
}

func (m *defaultInvoiceModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheInvoiceInvoiceIdPrefix, primary)
}

func (m *defaultInvoiceModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `invoice_id` = ? limit 1", invoiceRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultInvoiceModel) tableName() string {
	return m.table
}
