// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	refundFieldNames          = builder.RawFieldNames(&Refund{})
	refundRows                = strings.Join(refundFieldNames, ",")
	refundRowsExpectAutoSet   = strings.Join(stringx.Remove(refundFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	refundRowsWithPlaceHolder = strings.Join(stringx.Remove(refundFieldNames, "`refund_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRefundRefundIdPrefix          = "cache:refund:refundId:"
	cacheRefundPaymentNoReturnNoPrefix = "cache:refund:paymentNo:returnNo:"
	cacheRefundTenantIdRefundNoPrefix  = "cache:refund:tenantId:refundNo:"
)

type (
	refundModel interface {
		Insert(ctx context.Context, data *Refund) (sql.Result, error)
		FindOne(ctx context.Context, refundId int64) (*Refund, error)
		FindOneByPaymentNoReturnNo(ctx context.Context, paymentNo string, returnNo sql.NullString) (*Refund, error)
		FindOneByTenantIdRefundNo(ctx context.Context, tenantId int64, refundNo string) (*Refund, error)
		Update(ctx context.Context, data *Refund) error
		Delete(ctx context.Context, refundId int64) error
	}

	defaultRefundModel struct {
		sqlc.CachedConn
		table string
	}

	Refund struct {
		RefundId        int64          `db:"refund_id"`         // 雪花 ID
		RefundNo        string         `db:"refund_no"`         // 退款单号
		PaymentNo       string         `db:"payment_no"`        // 原支付单（原路退回锚点）
		OrderNo         string         `db:"order_no"`          // 业务订单号
		ReturnNo        sql.NullString `db:"return_no"`         // 触发退货单（退货审批联动必传）
		Amount          float64        `db:"amount"`            // 退款金额
		Channel         string         `db:"channel"`           // 原支付渠道（原路退回）
		Status          string         `db:"status"`            // PROCESSING/SUCCESS/FAILED
		ChannelRefundId sql.NullString `db:"channel_refund_id"` // 渠道退款流水
		Reason          sql.NullString `db:"reason"`
		TenantId        int64          `db:"tenant_id"`  // 租户 ID
		CreatedAt       time.Time      `db:"created_at"` // 创建时间
		CreatedBy       sql.NullInt64  `db:"created_by"` // 创建人 uid
		UpdatedAt       time.Time      `db:"updated_at"` // 更新时间
		UpdatedBy       sql.NullInt64  `db:"updated_by"` // 更新人 uid
		DeletedAt       sql.NullTime   `db:"deleted_at"` // 软删标记(NULL=有效)
	}
)

func newRefundModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultRefundModel {
	return &defaultRefundModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`refund`",
	}
}

func (m *defaultRefundModel) Delete(ctx context.Context, refundId int64) error {
	data, err := m.FindOne(ctx, refundId)
	if err != nil {
		return err
	}

	refundPaymentNoReturnNoKey := fmt.Sprintf("%s%v:%v", cacheRefundPaymentNoReturnNoPrefix, data.PaymentNo, data.ReturnNo)
	refundRefundIdKey := fmt.Sprintf("%s%v", cacheRefundRefundIdPrefix, refundId)
	refundTenantIdRefundNoKey := fmt.Sprintf("%s%v:%v", cacheRefundTenantIdRefundNoPrefix, data.TenantId, data.RefundNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `refund_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, refundId)
	}, refundPaymentNoReturnNoKey, refundRefundIdKey, refundTenantIdRefundNoKey)
	return err
}

func (m *defaultRefundModel) FindOne(ctx context.Context, refundId int64) (*Refund, error) {
	refundRefundIdKey := fmt.Sprintf("%s%v", cacheRefundRefundIdPrefix, refundId)
	var resp Refund
	err := m.QueryRowCtx(ctx, &resp, refundRefundIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `refund_id` = ? limit 1", refundRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, refundId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRefundModel) FindOneByPaymentNoReturnNo(ctx context.Context, paymentNo string, returnNo sql.NullString) (*Refund, error) {
	refundPaymentNoReturnNoKey := fmt.Sprintf("%s%v:%v", cacheRefundPaymentNoReturnNoPrefix, paymentNo, returnNo)
	var resp Refund
	err := m.QueryRowIndexCtx(ctx, &resp, refundPaymentNoReturnNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `payment_no` = ? and `return_no` = ? limit 1", refundRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, paymentNo, returnNo); err != nil {
			return nil, err
		}
		return resp.RefundId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRefundModel) FindOneByTenantIdRefundNo(ctx context.Context, tenantId int64, refundNo string) (*Refund, error) {
	refundTenantIdRefundNoKey := fmt.Sprintf("%s%v:%v", cacheRefundTenantIdRefundNoPrefix, tenantId, refundNo)
	var resp Refund
	err := m.QueryRowIndexCtx(ctx, &resp, refundTenantIdRefundNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `refund_no` = ? limit 1", refundRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, refundNo); err != nil {
			return nil, err
		}
		return resp.RefundId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRefundModel) Insert(ctx context.Context, data *Refund) (sql.Result, error) {
	refundPaymentNoReturnNoKey := fmt.Sprintf("%s%v:%v", cacheRefundPaymentNoReturnNoPrefix, data.PaymentNo, data.ReturnNo)
	refundRefundIdKey := fmt.Sprintf("%s%v", cacheRefundRefundIdPrefix, data.RefundId)
	refundTenantIdRefundNoKey := fmt.Sprintf("%s%v:%v", cacheRefundTenantIdRefundNoPrefix, data.TenantId, data.RefundNo)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, refundRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RefundId, data.RefundNo, data.PaymentNo, data.OrderNo, data.ReturnNo, data.Amount, data.Channel, data.Status, data.ChannelRefundId, data.Reason, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt)
	}, refundPaymentNoReturnNoKey, refundRefundIdKey, refundTenantIdRefundNoKey)
	return ret, err
}

func (m *defaultRefundModel) Update(ctx context.Context, newData *Refund) error {
	data, err := m.FindOne(ctx, newData.RefundId)
	if err != nil {
		return err
	}

	refundPaymentNoReturnNoKey := fmt.Sprintf("%s%v:%v", cacheRefundPaymentNoReturnNoPrefix, data.PaymentNo, data.ReturnNo)
	refundRefundIdKey := fmt.Sprintf("%s%v", cacheRefundRefundIdPrefix, data.RefundId)
	refundTenantIdRefundNoKey := fmt.Sprintf("%s%v:%v", cacheRefundTenantIdRefundNoPrefix, data.TenantId, data.RefundNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `refund_id` = ?", m.table, refundRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.RefundNo, newData.PaymentNo, newData.OrderNo, newData.ReturnNo, newData.Amount, newData.Channel, newData.Status, newData.ChannelRefundId, newData.Reason, newData.TenantId, newData.CreatedBy, newData.UpdatedBy, newData.DeletedAt, newData.RefundId)
	}, refundPaymentNoReturnNoKey, refundRefundIdKey, refundTenantIdRefundNoKey)
	return err
}

func (m *defaultRefundModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRefundRefundIdPrefix, primary)
}

func (m *defaultRefundModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `refund_id` = ? limit 1", refundRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRefundModel) tableName() string {
	return m.table
}
