// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: pb/file.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	File_Ping_FullMethodName             = "/file.File/Ping"
	File_PutFile_FullMethodName          = "/file.File/PutFile"
	File_GetFileMeta_FullMethodName      = "/file.File/GetFileMeta"
	File_ListFile_FullMethodName         = "/file.File/ListFile"
	File_GetDownloadToken_FullMethodName = "/file.File/GetDownloadToken"
	File_GetFileData_FullMethodName      = "/file.File/GetFileData"
	File_DeleteFile_FullMethodName       = "/file.File/DeleteFile"
)

// FileClient is the client API for File service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// File 文件服务契约（S4-04，v4/03 阶段 4）。
//
// 职责边界：file_db 存元数据，对象存 MinIO（S3 兼容，双桶 micro-file/micro-contract）；
// oss_key = /{tenant}/{biz_type}/{yyyy}/{mm}/{uuid}.{ext}（02 §6.5）；
// 临时下载令牌为 HMAC 签名 URL（file 服务签发/校验，BFF 代理流式回源）。
type FileClient interface {
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
	// 上传（BFF multipart → RPC bytes；dev 规模适用，大文件走直传属 S9 演进）
	PutFile(ctx context.Context, in *PutFileReq, opts ...grpc.CallOption) (*PutFileResp, error)
	// 元数据
	GetFileMeta(ctx context.Context, in *GetFileMetaReq, opts ...grpc.CallOption) (*GetFileMetaResp, error)
	ListFile(ctx context.Context, in *ListFileReq, opts ...grpc.CallOption) (*ListFileResp, error)
	// 下载：签发临时令牌 / 校验令牌并取对象内容
	GetDownloadToken(ctx context.Context, in *GetDownloadTokenReq, opts ...grpc.CallOption) (*GetDownloadTokenResp, error)
	GetFileData(ctx context.Context, in *GetFileDataReq, opts ...grpc.CallOption) (*GetFileDataResp, error)
	// 软删元数据（对象保留，回收属运维流程）
	DeleteFile(ctx context.Context, in *DeleteFileReq, opts ...grpc.CallOption) (*DeleteFileResp, error)
}

type fileClient struct {
	cc grpc.ClientConnInterface
}

func NewFileClient(cc grpc.ClientConnInterface) FileClient {
	return &fileClient{cc}
}

func (c *fileClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResp)
	err := c.cc.Invoke(ctx, File_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) PutFile(ctx context.Context, in *PutFileReq, opts ...grpc.CallOption) (*PutFileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutFileResp)
	err := c.cc.Invoke(ctx, File_PutFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) GetFileMeta(ctx context.Context, in *GetFileMetaReq, opts ...grpc.CallOption) (*GetFileMetaResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileMetaResp)
	err := c.cc.Invoke(ctx, File_GetFileMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) ListFile(ctx context.Context, in *ListFileReq, opts ...grpc.CallOption) (*ListFileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFileResp)
	err := c.cc.Invoke(ctx, File_ListFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) GetDownloadToken(ctx context.Context, in *GetDownloadTokenReq, opts ...grpc.CallOption) (*GetDownloadTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDownloadTokenResp)
	err := c.cc.Invoke(ctx, File_GetDownloadToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) GetFileData(ctx context.Context, in *GetFileDataReq, opts ...grpc.CallOption) (*GetFileDataResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileDataResp)
	err := c.cc.Invoke(ctx, File_GetFileData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) DeleteFile(ctx context.Context, in *DeleteFileReq, opts ...grpc.CallOption) (*DeleteFileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFileResp)
	err := c.cc.Invoke(ctx, File_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServer is the server API for File service.
// All implementations must embed UnimplementedFileServer
// for forward compatibility.
//
// File 文件服务契约（S4-04，v4/03 阶段 4）。
//
// 职责边界：file_db 存元数据，对象存 MinIO（S3 兼容，双桶 micro-file/micro-contract）；
// oss_key = /{tenant}/{biz_type}/{yyyy}/{mm}/{uuid}.{ext}（02 §6.5）；
// 临时下载令牌为 HMAC 签名 URL（file 服务签发/校验，BFF 代理流式回源）。
type FileServer interface {
	Ping(context.Context, *PingReq) (*PingResp, error)
	// 上传（BFF multipart → RPC bytes；dev 规模适用，大文件走直传属 S9 演进）
	PutFile(context.Context, *PutFileReq) (*PutFileResp, error)
	// 元数据
	GetFileMeta(context.Context, *GetFileMetaReq) (*GetFileMetaResp, error)
	ListFile(context.Context, *ListFileReq) (*ListFileResp, error)
	// 下载：签发临时令牌 / 校验令牌并取对象内容
	GetDownloadToken(context.Context, *GetDownloadTokenReq) (*GetDownloadTokenResp, error)
	GetFileData(context.Context, *GetFileDataReq) (*GetFileDataResp, error)
	// 软删元数据（对象保留，回收属运维流程）
	DeleteFile(context.Context, *DeleteFileReq) (*DeleteFileResp, error)
	mustEmbedUnimplementedFileServer()
}

// UnimplementedFileServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServer struct{}

func (UnimplementedFileServer) Ping(context.Context, *PingReq) (*PingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedFileServer) PutFile(context.Context, *PutFileReq) (*PutFileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PutFile not implemented")
}
func (UnimplementedFileServer) GetFileMeta(context.Context, *GetFileMetaReq) (*GetFileMetaResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileMeta not implemented")
}
func (UnimplementedFileServer) ListFile(context.Context, *ListFileReq) (*ListFileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFile not implemented")
}
func (UnimplementedFileServer) GetDownloadToken(context.Context, *GetDownloadTokenReq) (*GetDownloadTokenResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDownloadToken not implemented")
}
func (UnimplementedFileServer) GetFileData(context.Context, *GetFileDataReq) (*GetFileDataResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileData not implemented")
}
func (UnimplementedFileServer) DeleteFile(context.Context, *DeleteFileReq) (*DeleteFileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedFileServer) mustEmbedUnimplementedFileServer() {}
func (UnimplementedFileServer) testEmbeddedByValue()              {}

// UnsafeFileServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServer will
// result in compilation errors.
type UnsafeFileServer interface {
	mustEmbedUnimplementedFileServer()
}

func RegisterFileServer(s grpc.ServiceRegistrar, srv FileServer) {
	// If the following call panics, it indicates UnimplementedFileServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&File_ServiceDesc, srv)
}

func _File_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_PutFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).PutFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_PutFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).PutFile(ctx, req.(*PutFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_GetFileMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileMetaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).GetFileMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_GetFileMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).GetFileMeta(ctx, req.(*GetFileMetaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_ListFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).ListFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_ListFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).ListFile(ctx, req.(*ListFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_GetDownloadToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDownloadTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).GetDownloadToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_GetDownloadToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).GetDownloadToken(ctx, req.(*GetDownloadTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_GetFileData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).GetFileData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_GetFileData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).GetFileData(ctx, req.(*GetFileDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).DeleteFile(ctx, req.(*DeleteFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

// File_ServiceDesc is the grpc.ServiceDesc for File service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var File_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "file.File",
	HandlerType: (*FileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _File_Ping_Handler,
		},
		{
			MethodName: "PutFile",
			Handler:    _File_PutFile_Handler,
		},
		{
			MethodName: "GetFileMeta",
			Handler:    _File_GetFileMeta_Handler,
		},
		{
			MethodName: "ListFile",
			Handler:    _File_ListFile_Handler,
		},
		{
			MethodName: "GetDownloadToken",
			Handler:    _File_GetDownloadToken_Handler,
		},
		{
			MethodName: "GetFileData",
			Handler:    _File_GetFileData_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _File_DeleteFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/file.proto",
}
