// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	deviceTopologyFieldNames          = builder.RawFieldNames(&DeviceTopology{})
	deviceTopologyRows                = strings.Join(deviceTopologyFieldNames, ",")
	deviceTopologyRowsExpectAutoSet   = strings.Join(stringx.Remove(deviceTopologyFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	deviceTopologyRowsWithPlaceHolder = strings.Join(stringx.Remove(deviceTopologyFieldNames, "`node_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheDeviceTopologyNodeIdPrefix = "cache:deviceTopology:nodeId:"
)

type (
	deviceTopologyModel interface {
		Insert(ctx context.Context, data *DeviceTopology) (sql.Result, error)
		FindOne(ctx context.Context, nodeId int64) (*DeviceTopology, error)
		Update(ctx context.Context, data *DeviceTopology) error
		Delete(ctx context.Context, nodeId int64) error
	}

	defaultDeviceTopologyModel struct {
		sqlc.CachedConn
		table string
	}

	DeviceTopology struct {
		NodeId    int64         `db:"node_id"`    // 雪花 ID
		DeviceId  int64         `db:"device_id"`  // 所属设备
		ParentId  sql.NullInt64 `db:"parent_id"`  // 父节点（NULL=根）
		NodeType  string        `db:"node_type"`  // CELL 电芯/MODULE 模组/PACK 电池包/CHARGER 充电桩
		NodeName  string        `db:"node_name"`  // 节点名称/位号
		Sort      int64         `db:"sort"`       // 同级排序
		TenantId  int64         `db:"tenant_id"`  // 租户 ID
		CreatedAt time.Time     `db:"created_at"` // 创建时间
		UpdatedAt time.Time     `db:"updated_at"` // 更新时间
		DeletedAt sql.NullTime  `db:"deleted_at"` // 软删标记(NULL=有效)
	}
)

func newDeviceTopologyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDeviceTopologyModel {
	return &defaultDeviceTopologyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`device_topology`",
	}
}

func (m *defaultDeviceTopologyModel) Delete(ctx context.Context, nodeId int64) error {
	deviceTopologyNodeIdKey := fmt.Sprintf("%s%v", cacheDeviceTopologyNodeIdPrefix, nodeId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `node_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, nodeId)
	}, deviceTopologyNodeIdKey)
	return err
}

func (m *defaultDeviceTopologyModel) FindOne(ctx context.Context, nodeId int64) (*DeviceTopology, error) {
	deviceTopologyNodeIdKey := fmt.Sprintf("%s%v", cacheDeviceTopologyNodeIdPrefix, nodeId)
	var resp DeviceTopology
	err := m.QueryRowCtx(ctx, &resp, deviceTopologyNodeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `node_id` = ? limit 1", deviceTopologyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, nodeId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDeviceTopologyModel) Insert(ctx context.Context, data *DeviceTopology) (sql.Result, error) {
	deviceTopologyNodeIdKey := fmt.Sprintf("%s%v", cacheDeviceTopologyNodeIdPrefix, data.NodeId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, deviceTopologyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.NodeId, data.DeviceId, data.ParentId, data.NodeType, data.NodeName, data.Sort, data.TenantId, data.DeletedAt)
	}, deviceTopologyNodeIdKey)
	return ret, err
}

func (m *defaultDeviceTopologyModel) Update(ctx context.Context, data *DeviceTopology) error {
	deviceTopologyNodeIdKey := fmt.Sprintf("%s%v", cacheDeviceTopologyNodeIdPrefix, data.NodeId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `node_id` = ?", m.table, deviceTopologyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DeviceId, data.ParentId, data.NodeType, data.NodeName, data.Sort, data.TenantId, data.DeletedAt, data.NodeId)
	}, deviceTopologyNodeIdKey)
	return err
}

func (m *defaultDeviceTopologyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheDeviceTopologyNodeIdPrefix, primary)
}

func (m *defaultDeviceTopologyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `node_id` = ? limit 1", deviceTopologyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDeviceTopologyModel) tableName() string {
	return m.table
}
