// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	firmwareFieldNames          = builder.RawFieldNames(&Firmware{})
	firmwareRows                = strings.Join(firmwareFieldNames, ",")
	firmwareRowsExpectAutoSet   = strings.Join(stringx.Remove(firmwareFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	firmwareRowsWithPlaceHolder = strings.Join(stringx.Remove(firmwareFieldNames, "`firmware_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFirmwareFirmwareIdPrefix                = "cache:firmware:firmwareId:"
	cacheFirmwareTenantIdProductKeyVersionPrefix = "cache:firmware:tenantId:productKey:version:"
)

type (
	firmwareModel interface {
		Insert(ctx context.Context, data *Firmware) (sql.Result, error)
		FindOne(ctx context.Context, firmwareId int64) (*Firmware, error)
		FindOneByTenantIdProductKeyVersion(ctx context.Context, tenantId int64, productKey string, version string) (*Firmware, error)
		Update(ctx context.Context, data *Firmware) error
		Delete(ctx context.Context, firmwareId int64) error
	}

	defaultFirmwareModel struct {
		sqlc.CachedConn
		table string
	}

	Firmware struct {
		FirmwareId int64          `db:"firmware_id"` // 雪花 ID
		ProductKey string         `db:"product_key"` // 适用产品
		Version    string         `db:"version"`     // 固件版本
		FileUrl    string         `db:"file_url"`    // 固件包对象存储地址（MinIO file 桶）
		FileSize   int64          `db:"file_size"`   // 字节数
		Sha256     string         `db:"sha256"`      // 固件包 SHA-256（hex）
		Signature  string         `db:"signature"`   // Ed25519 签名（base64，对 sha256 hex 串签名）
		SignAlg    string         `db:"sign_alg"`    // 签名算法
		Remark     sql.NullString `db:"remark"`
		TenantId   int64          `db:"tenant_id"`  // 租户 ID
		CreatedAt  time.Time      `db:"created_at"` // 创建时间
		CreatedBy  sql.NullInt64  `db:"created_by"` // 上传人 uid
		UpdatedAt  time.Time      `db:"updated_at"` // 更新时间
		DeletedAt  sql.NullTime   `db:"deleted_at"` // 软删标记(NULL=有效)
	}
)

func newFirmwareModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFirmwareModel {
	return &defaultFirmwareModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`firmware`",
	}
}

func (m *defaultFirmwareModel) Delete(ctx context.Context, firmwareId int64) error {
	data, err := m.FindOne(ctx, firmwareId)
	if err != nil {
		return err
	}

	firmwareFirmwareIdKey := fmt.Sprintf("%s%v", cacheFirmwareFirmwareIdPrefix, firmwareId)
	firmwareTenantIdProductKeyVersionKey := fmt.Sprintf("%s%v:%v:%v", cacheFirmwareTenantIdProductKeyVersionPrefix, data.TenantId, data.ProductKey, data.Version)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `firmware_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, firmwareId)
	}, firmwareFirmwareIdKey, firmwareTenantIdProductKeyVersionKey)
	return err
}

func (m *defaultFirmwareModel) FindOne(ctx context.Context, firmwareId int64) (*Firmware, error) {
	firmwareFirmwareIdKey := fmt.Sprintf("%s%v", cacheFirmwareFirmwareIdPrefix, firmwareId)
	var resp Firmware
	err := m.QueryRowCtx(ctx, &resp, firmwareFirmwareIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `firmware_id` = ? limit 1", firmwareRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, firmwareId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFirmwareModel) FindOneByTenantIdProductKeyVersion(ctx context.Context, tenantId int64, productKey string, version string) (*Firmware, error) {
	firmwareTenantIdProductKeyVersionKey := fmt.Sprintf("%s%v:%v:%v", cacheFirmwareTenantIdProductKeyVersionPrefix, tenantId, productKey, version)
	var resp Firmware
	err := m.QueryRowIndexCtx(ctx, &resp, firmwareTenantIdProductKeyVersionKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `product_key` = ? and `version` = ? limit 1", firmwareRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, productKey, version); err != nil {
			return nil, err
		}
		return resp.FirmwareId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFirmwareModel) Insert(ctx context.Context, data *Firmware) (sql.Result, error) {
	firmwareFirmwareIdKey := fmt.Sprintf("%s%v", cacheFirmwareFirmwareIdPrefix, data.FirmwareId)
	firmwareTenantIdProductKeyVersionKey := fmt.Sprintf("%s%v:%v:%v", cacheFirmwareTenantIdProductKeyVersionPrefix, data.TenantId, data.ProductKey, data.Version)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, firmwareRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.FirmwareId, data.ProductKey, data.Version, data.FileUrl, data.FileSize, data.Sha256, data.Signature, data.SignAlg, data.Remark, data.TenantId, data.CreatedBy, data.DeletedAt)
	}, firmwareFirmwareIdKey, firmwareTenantIdProductKeyVersionKey)
	return ret, err
}

func (m *defaultFirmwareModel) Update(ctx context.Context, newData *Firmware) error {
	data, err := m.FindOne(ctx, newData.FirmwareId)
	if err != nil {
		return err
	}

	firmwareFirmwareIdKey := fmt.Sprintf("%s%v", cacheFirmwareFirmwareIdPrefix, data.FirmwareId)
	firmwareTenantIdProductKeyVersionKey := fmt.Sprintf("%s%v:%v:%v", cacheFirmwareTenantIdProductKeyVersionPrefix, data.TenantId, data.ProductKey, data.Version)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `firmware_id` = ?", m.table, firmwareRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ProductKey, newData.Version, newData.FileUrl, newData.FileSize, newData.Sha256, newData.Signature, newData.SignAlg, newData.Remark, newData.TenantId, newData.CreatedBy, newData.DeletedAt, newData.FirmwareId)
	}, firmwareFirmwareIdKey, firmwareTenantIdProductKeyVersionKey)
	return err
}

func (m *defaultFirmwareModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFirmwareFirmwareIdPrefix, primary)
}

func (m *defaultFirmwareModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `firmware_id` = ? limit 1", firmwareRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFirmwareModel) tableName() string {
	return m.table
}
