// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	otaTaskFieldNames          = builder.RawFieldNames(&OtaTask{})
	otaTaskRows                = strings.Join(otaTaskFieldNames, ",")
	otaTaskRowsExpectAutoSet   = strings.Join(stringx.Remove(otaTaskFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	otaTaskRowsWithPlaceHolder = strings.Join(stringx.Remove(otaTaskFieldNames, "`task_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheOtaTaskTaskIdPrefix         = "cache:otaTask:taskId:"
	cacheOtaTaskTenantIdTaskNoPrefix = "cache:otaTask:tenantId:taskNo:"
)

type (
	otaTaskModel interface {
		Insert(ctx context.Context, data *OtaTask) (sql.Result, error)
		FindOne(ctx context.Context, taskId int64) (*OtaTask, error)
		FindOneByTenantIdTaskNo(ctx context.Context, tenantId int64, taskNo string) (*OtaTask, error)
		Update(ctx context.Context, data *OtaTask) error
		Delete(ctx context.Context, taskId int64) error
	}

	defaultOtaTaskModel struct {
		sqlc.CachedConn
		table string
	}

	OtaTask struct {
		TaskId             int64          `db:"task_id"`              // 雪花 ID
		TaskNo             string         `db:"task_no"`              // 任务号（幂等键）
		Name               string         `db:"name"`                 // 任务名称
		ProductKey         string         `db:"product_key"`          // 目标产品
		FirmwareId         int64          `db:"firmware_id"`          // 目标固件
		RollbackFirmwareId sql.NullInt64  `db:"rollback_firmware_id"` // 回滚固件（失败回退目标）
		BatchSize          int64          `db:"batch_size"`           // 灰度批次大小（每轮下发的设备数）
		FailThresholdPct   int64          `db:"fail_threshold_pct"`   // 失败率阈值 %（超过自动 PAUSED）
		Status             string         `db:"status"`               // CREATED/RUNNING/PAUSED/DONE/CANCELLED/ROLLED_BACK
		Total              int64          `db:"total"`                // 设备总数
		SuccessCount       int64          `db:"success_count"`        // 成功数
		FailCount          int64          `db:"fail_count"`           // 失败数
		FailReason         sql.NullString `db:"fail_reason"`          // 暂停/回滚原因
		TenantId           int64          `db:"tenant_id"`            // 租户 ID
		CreatedAt          time.Time      `db:"created_at"`           // 创建时间
		CreatedBy          sql.NullInt64  `db:"created_by"`           // 创建人 uid
		UpdatedAt          time.Time      `db:"updated_at"`           // 更新时间
		DeletedAt          sql.NullTime   `db:"deleted_at"`           // 软删标记(NULL=有效)
	}
)

func newOtaTaskModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOtaTaskModel {
	return &defaultOtaTaskModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`ota_task`",
	}
}

func (m *defaultOtaTaskModel) Delete(ctx context.Context, taskId int64) error {
	data, err := m.FindOne(ctx, taskId)
	if err != nil {
		return err
	}

	otaTaskTaskIdKey := fmt.Sprintf("%s%v", cacheOtaTaskTaskIdPrefix, taskId)
	otaTaskTenantIdTaskNoKey := fmt.Sprintf("%s%v:%v", cacheOtaTaskTenantIdTaskNoPrefix, data.TenantId, data.TaskNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `task_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, taskId)
	}, otaTaskTaskIdKey, otaTaskTenantIdTaskNoKey)
	return err
}

func (m *defaultOtaTaskModel) FindOne(ctx context.Context, taskId int64) (*OtaTask, error) {
	otaTaskTaskIdKey := fmt.Sprintf("%s%v", cacheOtaTaskTaskIdPrefix, taskId)
	var resp OtaTask
	err := m.QueryRowCtx(ctx, &resp, otaTaskTaskIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `task_id` = ? limit 1", otaTaskRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, taskId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOtaTaskModel) FindOneByTenantIdTaskNo(ctx context.Context, tenantId int64, taskNo string) (*OtaTask, error) {
	otaTaskTenantIdTaskNoKey := fmt.Sprintf("%s%v:%v", cacheOtaTaskTenantIdTaskNoPrefix, tenantId, taskNo)
	var resp OtaTask
	err := m.QueryRowIndexCtx(ctx, &resp, otaTaskTenantIdTaskNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `task_no` = ? limit 1", otaTaskRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, taskNo); err != nil {
			return nil, err
		}
		return resp.TaskId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOtaTaskModel) Insert(ctx context.Context, data *OtaTask) (sql.Result, error) {
	otaTaskTaskIdKey := fmt.Sprintf("%s%v", cacheOtaTaskTaskIdPrefix, data.TaskId)
	otaTaskTenantIdTaskNoKey := fmt.Sprintf("%s%v:%v", cacheOtaTaskTenantIdTaskNoPrefix, data.TenantId, data.TaskNo)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, otaTaskRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TaskId, data.TaskNo, data.Name, data.ProductKey, data.FirmwareId, data.RollbackFirmwareId, data.BatchSize, data.FailThresholdPct, data.Status, data.Total, data.SuccessCount, data.FailCount, data.FailReason, data.TenantId, data.CreatedBy, data.DeletedAt)
	}, otaTaskTaskIdKey, otaTaskTenantIdTaskNoKey)
	return ret, err
}

func (m *defaultOtaTaskModel) Update(ctx context.Context, newData *OtaTask) error {
	data, err := m.FindOne(ctx, newData.TaskId)
	if err != nil {
		return err
	}

	otaTaskTaskIdKey := fmt.Sprintf("%s%v", cacheOtaTaskTaskIdPrefix, data.TaskId)
	otaTaskTenantIdTaskNoKey := fmt.Sprintf("%s%v:%v", cacheOtaTaskTenantIdTaskNoPrefix, data.TenantId, data.TaskNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `task_id` = ?", m.table, otaTaskRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TaskNo, newData.Name, newData.ProductKey, newData.FirmwareId, newData.RollbackFirmwareId, newData.BatchSize, newData.FailThresholdPct, newData.Status, newData.Total, newData.SuccessCount, newData.FailCount, newData.FailReason, newData.TenantId, newData.CreatedBy, newData.DeletedAt, newData.TaskId)
	}, otaTaskTaskIdKey, otaTaskTenantIdTaskNoKey)
	return err
}

func (m *defaultOtaTaskModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheOtaTaskTaskIdPrefix, primary)
}

func (m *defaultOtaTaskModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `task_id` = ? limit 1", otaTaskRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOtaTaskModel) tableName() string {
	return m.table
}
