// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userNotifySettingFieldNames          = builder.RawFieldNames(&UserNotifySetting{})
	userNotifySettingRows                = strings.Join(userNotifySettingFieldNames, ",")
	userNotifySettingRowsExpectAutoSet   = strings.Join(stringx.Remove(userNotifySettingFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userNotifySettingRowsWithPlaceHolder = strings.Join(stringx.Remove(userNotifySettingFieldNames, "`setting_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserNotifySettingSettingIdPrefix                  = "cache:userNotifySetting:settingId:"
	cacheUserNotifySettingTenantIdUserIdTemplateCodePrefix = "cache:userNotifySetting:tenantId:userId:templateCode:"
)

type (
	userNotifySettingModel interface {
		Insert(ctx context.Context, data *UserNotifySetting) (sql.Result, error)
		FindOne(ctx context.Context, settingId int64) (*UserNotifySetting, error)
		FindOneByTenantIdUserIdTemplateCode(ctx context.Context, tenantId int64, userId int64, templateCode string) (*UserNotifySetting, error)
		Update(ctx context.Context, data *UserNotifySetting) error
		Delete(ctx context.Context, settingId int64) error
	}

	defaultUserNotifySettingModel struct {
		sqlc.CachedConn
		table string
	}

	UserNotifySetting struct {
		SettingId    int64          `db:"setting_id"`    // 雪花 ID
		UserId       int64          `db:"user_id"`       // 用户 uid
		TemplateCode string         `db:"template_code"` // 模板编码(*=全局默认)
		Enabled      int64          `db:"enabled"`       // 1 接收/0 静默
		QuietHours   sql.NullString `db:"quiet_hours"`   // 免打扰时段 JSON {"start":"22:00","end":"08:00"}
		TenantId     int64          `db:"tenant_id"`     // 租户 ID
		CreatedAt    time.Time      `db:"created_at"`    // 创建时间
		CreatedBy    sql.NullInt64  `db:"created_by"`    // 创建人 uid
		UpdatedAt    time.Time      `db:"updated_at"`    // 更新时间
		UpdatedBy    sql.NullInt64  `db:"updated_by"`    // 更新人 uid
		DeletedAt    sql.NullTime   `db:"deleted_at"`    // 软删标记(NULL=有效)
	}
)

func newUserNotifySettingModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserNotifySettingModel {
	return &defaultUserNotifySettingModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_notify_setting`",
	}
}

func (m *defaultUserNotifySettingModel) Delete(ctx context.Context, settingId int64) error {
	data, err := m.FindOne(ctx, settingId)
	if err != nil {
		return err
	}

	userNotifySettingSettingIdKey := fmt.Sprintf("%s%v", cacheUserNotifySettingSettingIdPrefix, settingId)
	userNotifySettingTenantIdUserIdTemplateCodeKey := fmt.Sprintf("%s%v:%v:%v", cacheUserNotifySettingTenantIdUserIdTemplateCodePrefix, data.TenantId, data.UserId, data.TemplateCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `setting_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, settingId)
	}, userNotifySettingSettingIdKey, userNotifySettingTenantIdUserIdTemplateCodeKey)
	return err
}

func (m *defaultUserNotifySettingModel) FindOne(ctx context.Context, settingId int64) (*UserNotifySetting, error) {
	userNotifySettingSettingIdKey := fmt.Sprintf("%s%v", cacheUserNotifySettingSettingIdPrefix, settingId)
	var resp UserNotifySetting
	err := m.QueryRowCtx(ctx, &resp, userNotifySettingSettingIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `setting_id` = ? limit 1", userNotifySettingRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, settingId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserNotifySettingModel) FindOneByTenantIdUserIdTemplateCode(ctx context.Context, tenantId int64, userId int64, templateCode string) (*UserNotifySetting, error) {
	userNotifySettingTenantIdUserIdTemplateCodeKey := fmt.Sprintf("%s%v:%v:%v", cacheUserNotifySettingTenantIdUserIdTemplateCodePrefix, tenantId, userId, templateCode)
	var resp UserNotifySetting
	err := m.QueryRowIndexCtx(ctx, &resp, userNotifySettingTenantIdUserIdTemplateCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `user_id` = ? and `template_code` = ? limit 1", userNotifySettingRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, userId, templateCode); err != nil {
			return nil, err
		}
		return resp.SettingId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserNotifySettingModel) Insert(ctx context.Context, data *UserNotifySetting) (sql.Result, error) {
	userNotifySettingSettingIdKey := fmt.Sprintf("%s%v", cacheUserNotifySettingSettingIdPrefix, data.SettingId)
	userNotifySettingTenantIdUserIdTemplateCodeKey := fmt.Sprintf("%s%v:%v:%v", cacheUserNotifySettingTenantIdUserIdTemplateCodePrefix, data.TenantId, data.UserId, data.TemplateCode)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userNotifySettingRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SettingId, data.UserId, data.TemplateCode, data.Enabled, data.QuietHours, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt)
	}, userNotifySettingSettingIdKey, userNotifySettingTenantIdUserIdTemplateCodeKey)
	return ret, err
}

func (m *defaultUserNotifySettingModel) Update(ctx context.Context, newData *UserNotifySetting) error {
	data, err := m.FindOne(ctx, newData.SettingId)
	if err != nil {
		return err
	}

	userNotifySettingSettingIdKey := fmt.Sprintf("%s%v", cacheUserNotifySettingSettingIdPrefix, data.SettingId)
	userNotifySettingTenantIdUserIdTemplateCodeKey := fmt.Sprintf("%s%v:%v:%v", cacheUserNotifySettingTenantIdUserIdTemplateCodePrefix, data.TenantId, data.UserId, data.TemplateCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `setting_id` = ?", m.table, userNotifySettingRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.TemplateCode, newData.Enabled, newData.QuietHours, newData.TenantId, newData.CreatedBy, newData.UpdatedBy, newData.DeletedAt, newData.SettingId)
	}, userNotifySettingSettingIdKey, userNotifySettingTenantIdUserIdTemplateCodeKey)
	return err
}

func (m *defaultUserNotifySettingModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserNotifySettingSettingIdPrefix, primary)
}

func (m *defaultUserNotifySettingModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `setting_id` = ? limit 1", userNotifySettingRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserNotifySettingModel) tableName() string {
	return m.table
}
