// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: services/contract/pb/contract.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Contract_Ping_FullMethodName                = "/contract.Contract/Ping"
	Contract_CreateTemplate_FullMethodName      = "/contract.Contract/CreateTemplate"
	Contract_RenderTemplate_FullMethodName      = "/contract.Contract/RenderTemplate"
	Contract_CreateFromOrder_FullMethodName     = "/contract.Contract/CreateFromOrder"
	Contract_GetContract_FullMethodName         = "/contract.Contract/GetContract"
	Contract_ListContract_FullMethodName        = "/contract.Contract/ListContract"
	Contract_UploadContractFile_FullMethodName  = "/contract.Contract/UploadContractFile"
	Contract_ArchiveContract_FullMethodName     = "/contract.Contract/ArchiveContract"
	Contract_ListWarranty_FullMethodName        = "/contract.Contract/ListWarranty"
	Contract_GetWarrantyByTarget_FullMethodName = "/contract.Contract/GetWarrantyByTarget"
	Contract_CreateSlaStrategy_FullMethodName   = "/contract.Contract/CreateSlaStrategy"
	Contract_BindContractSla_FullMethodName     = "/contract.Contract/BindContractSla"
	Contract_ListSlaStrategy_FullMethodName     = "/contract.Contract/ListSlaStrategy"
	Contract_CreateClaim_FullMethodName         = "/contract.Contract/CreateClaim"
	Contract_ApproveClaim_FullMethodName        = "/contract.Contract/ApproveClaim"
	Contract_SettleClaim_FullMethodName         = "/contract.Contract/SettleClaim"
	Contract_ListClaim_FullMethodName           = "/contract.Contract/ListClaim"
	Contract_SellExtension_FullMethodName       = "/contract.Contract/SellExtension"
	Contract_TransferExtension_FullMethodName   = "/contract.Contract/TransferExtension"
	Contract_RefundExtension_FullMethodName     = "/contract.Contract/RefundExtension"
)

// ContractClient is the client API for Contract service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Contract 合同质保服务契约（S5-04，v4/03 阶段 5 任务正本）。
//
// 职责边界：contract_db 是合同/归档件/质保/延保/SLA 策略/索赔的唯一写入方（FR-CTR）。
// 合同签署基线 = 线下签署 + 上传归档（FR-CTR-003，在线签署为 L3）：
//
//	归档五要素 = 上传人（审计）/版本/关联（订单/客户/场站）/状态/受控下载；
//	平台不解析文件内容；文件本体存 file 服务合同桶（micro-contract，版本控制），本服务只存归档元数据。
//
// 质保起算（FR-CTR-005）：消费 device_activated / shipment_signed 事件 → 按 start_rule 快照写
//
//	warranty.start_at → 发 warranty_started 事件；场站级 + 设备级双层。
//
// SLA（FR-CTR-007）：策略在合同域定义，计时由 ops 执行（快照冻结，S7 消费）。
// 打印稿（FR-CTR-001，L2 辅助）：模板变量填充 → Go 原生 PDF（ADR-18，无 Gotenberg）。
// ID 传输 int64，对外 string（E8）；金额 DECIMAL 字符串。
type ContractClient interface {
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
	// ---- 模板（L2）----
	CreateTemplate(ctx context.Context, in *CreateTemplateReq, opts ...grpc.CallOption) (*CreateTemplateResp, error)
	RenderTemplate(ctx context.Context, in *RenderTemplateReq, opts ...grpc.CallOption) (*RenderTemplateResp, error)
	// ---- 合同 ----
	CreateFromOrder(ctx context.Context, in *CreateFromOrderReq, opts ...grpc.CallOption) (*CreateFromOrderResp, error)
	GetContract(ctx context.Context, in *GetContractReq, opts ...grpc.CallOption) (*GetContractResp, error)
	ListContract(ctx context.Context, in *ListContractReq, opts ...grpc.CallOption) (*ListContractResp, error)
	UploadContractFile(ctx context.Context, in *UploadContractFileReq, opts ...grpc.CallOption) (*UploadContractFileResp, error)
	ArchiveContract(ctx context.Context, in *ArchiveContractReq, opts ...grpc.CallOption) (*ArchiveContractResp, error)
	// ---- 质保 ----
	ListWarranty(ctx context.Context, in *ListWarrantyReq, opts ...grpc.CallOption) (*ListWarrantyResp, error)
	GetWarrantyByTarget(ctx context.Context, in *GetWarrantyByTargetReq, opts ...grpc.CallOption) (*GetWarrantyByTargetResp, error)
	// ---- SLA（FR-CTR-007）----
	CreateSlaStrategy(ctx context.Context, in *CreateSlaStrategyReq, opts ...grpc.CallOption) (*CreateSlaStrategyResp, error)
	BindContractSla(ctx context.Context, in *BindContractSlaReq, opts ...grpc.CallOption) (*BindContractSlaResp, error)
	ListSlaStrategy(ctx context.Context, in *ListSlaStrategyReq, opts ...grpc.CallOption) (*ListSlaStrategyResp, error)
	// ---- 索赔（FR-CTR-008）----
	CreateClaim(ctx context.Context, in *CreateClaimReq, opts ...grpc.CallOption) (*CreateClaimResp, error)
	ApproveClaim(ctx context.Context, in *ApproveClaimReq, opts ...grpc.CallOption) (*ApproveClaimResp, error)
	SettleClaim(ctx context.Context, in *SettleClaimReq, opts ...grpc.CallOption) (*SettleClaimResp, error)
	ListClaim(ctx context.Context, in *ListClaimReq, opts ...grpc.CallOption) (*ListClaimResp, error)
	// ---- 延保（FR-CTR-006：销售/衔接/转移/退款）----
	SellExtension(ctx context.Context, in *SellExtensionReq, opts ...grpc.CallOption) (*SellExtensionResp, error)
	TransferExtension(ctx context.Context, in *TransferExtensionReq, opts ...grpc.CallOption) (*TransferExtensionResp, error)
	RefundExtension(ctx context.Context, in *RefundExtensionReq, opts ...grpc.CallOption) (*RefundExtensionResp, error)
}

type contractClient struct {
	cc grpc.ClientConnInterface
}

func NewContractClient(cc grpc.ClientConnInterface) ContractClient {
	return &contractClient{cc}
}

func (c *contractClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResp)
	err := c.cc.Invoke(ctx, Contract_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) CreateTemplate(ctx context.Context, in *CreateTemplateReq, opts ...grpc.CallOption) (*CreateTemplateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTemplateResp)
	err := c.cc.Invoke(ctx, Contract_CreateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) RenderTemplate(ctx context.Context, in *RenderTemplateReq, opts ...grpc.CallOption) (*RenderTemplateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderTemplateResp)
	err := c.cc.Invoke(ctx, Contract_RenderTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) CreateFromOrder(ctx context.Context, in *CreateFromOrderReq, opts ...grpc.CallOption) (*CreateFromOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFromOrderResp)
	err := c.cc.Invoke(ctx, Contract_CreateFromOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) GetContract(ctx context.Context, in *GetContractReq, opts ...grpc.CallOption) (*GetContractResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContractResp)
	err := c.cc.Invoke(ctx, Contract_GetContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) ListContract(ctx context.Context, in *ListContractReq, opts ...grpc.CallOption) (*ListContractResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContractResp)
	err := c.cc.Invoke(ctx, Contract_ListContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) UploadContractFile(ctx context.Context, in *UploadContractFileReq, opts ...grpc.CallOption) (*UploadContractFileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadContractFileResp)
	err := c.cc.Invoke(ctx, Contract_UploadContractFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) ArchiveContract(ctx context.Context, in *ArchiveContractReq, opts ...grpc.CallOption) (*ArchiveContractResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveContractResp)
	err := c.cc.Invoke(ctx, Contract_ArchiveContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) ListWarranty(ctx context.Context, in *ListWarrantyReq, opts ...grpc.CallOption) (*ListWarrantyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWarrantyResp)
	err := c.cc.Invoke(ctx, Contract_ListWarranty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) GetWarrantyByTarget(ctx context.Context, in *GetWarrantyByTargetReq, opts ...grpc.CallOption) (*GetWarrantyByTargetResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWarrantyByTargetResp)
	err := c.cc.Invoke(ctx, Contract_GetWarrantyByTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) CreateSlaStrategy(ctx context.Context, in *CreateSlaStrategyReq, opts ...grpc.CallOption) (*CreateSlaStrategyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSlaStrategyResp)
	err := c.cc.Invoke(ctx, Contract_CreateSlaStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) BindContractSla(ctx context.Context, in *BindContractSlaReq, opts ...grpc.CallOption) (*BindContractSlaResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindContractSlaResp)
	err := c.cc.Invoke(ctx, Contract_BindContractSla_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) ListSlaStrategy(ctx context.Context, in *ListSlaStrategyReq, opts ...grpc.CallOption) (*ListSlaStrategyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSlaStrategyResp)
	err := c.cc.Invoke(ctx, Contract_ListSlaStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) CreateClaim(ctx context.Context, in *CreateClaimReq, opts ...grpc.CallOption) (*CreateClaimResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateClaimResp)
	err := c.cc.Invoke(ctx, Contract_CreateClaim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) ApproveClaim(ctx context.Context, in *ApproveClaimReq, opts ...grpc.CallOption) (*ApproveClaimResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveClaimResp)
	err := c.cc.Invoke(ctx, Contract_ApproveClaim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) SettleClaim(ctx context.Context, in *SettleClaimReq, opts ...grpc.CallOption) (*SettleClaimResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleClaimResp)
	err := c.cc.Invoke(ctx, Contract_SettleClaim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) ListClaim(ctx context.Context, in *ListClaimReq, opts ...grpc.CallOption) (*ListClaimResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClaimResp)
	err := c.cc.Invoke(ctx, Contract_ListClaim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) SellExtension(ctx context.Context, in *SellExtensionReq, opts ...grpc.CallOption) (*SellExtensionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SellExtensionResp)
	err := c.cc.Invoke(ctx, Contract_SellExtension_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) TransferExtension(ctx context.Context, in *TransferExtensionReq, opts ...grpc.CallOption) (*TransferExtensionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferExtensionResp)
	err := c.cc.Invoke(ctx, Contract_TransferExtension_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) RefundExtension(ctx context.Context, in *RefundExtensionReq, opts ...grpc.CallOption) (*RefundExtensionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundExtensionResp)
	err := c.cc.Invoke(ctx, Contract_RefundExtension_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContractServer is the server API for Contract service.
// All implementations must embed UnimplementedContractServer
// for forward compatibility.
//
// Contract 合同质保服务契约（S5-04，v4/03 阶段 5 任务正本）。
//
// 职责边界：contract_db 是合同/归档件/质保/延保/SLA 策略/索赔的唯一写入方（FR-CTR）。
// 合同签署基线 = 线下签署 + 上传归档（FR-CTR-003，在线签署为 L3）：
//
//	归档五要素 = 上传人（审计）/版本/关联（订单/客户/场站）/状态/受控下载；
//	平台不解析文件内容；文件本体存 file 服务合同桶（micro-contract，版本控制），本服务只存归档元数据。
//
// 质保起算（FR-CTR-005）：消费 device_activated / shipment_signed 事件 → 按 start_rule 快照写
//
//	warranty.start_at → 发 warranty_started 事件；场站级 + 设备级双层。
//
// SLA（FR-CTR-007）：策略在合同域定义，计时由 ops 执行（快照冻结，S7 消费）。
// 打印稿（FR-CTR-001，L2 辅助）：模板变量填充 → Go 原生 PDF（ADR-18，无 Gotenberg）。
// ID 传输 int64，对外 string（E8）；金额 DECIMAL 字符串。
type ContractServer interface {
	Ping(context.Context, *PingReq) (*PingResp, error)
	// ---- 模板（L2）----
	CreateTemplate(context.Context, *CreateTemplateReq) (*CreateTemplateResp, error)
	RenderTemplate(context.Context, *RenderTemplateReq) (*RenderTemplateResp, error)
	// ---- 合同 ----
	CreateFromOrder(context.Context, *CreateFromOrderReq) (*CreateFromOrderResp, error)
	GetContract(context.Context, *GetContractReq) (*GetContractResp, error)
	ListContract(context.Context, *ListContractReq) (*ListContractResp, error)
	UploadContractFile(context.Context, *UploadContractFileReq) (*UploadContractFileResp, error)
	ArchiveContract(context.Context, *ArchiveContractReq) (*ArchiveContractResp, error)
	// ---- 质保 ----
	ListWarranty(context.Context, *ListWarrantyReq) (*ListWarrantyResp, error)
	GetWarrantyByTarget(context.Context, *GetWarrantyByTargetReq) (*GetWarrantyByTargetResp, error)
	// ---- SLA（FR-CTR-007）----
	CreateSlaStrategy(context.Context, *CreateSlaStrategyReq) (*CreateSlaStrategyResp, error)
	BindContractSla(context.Context, *BindContractSlaReq) (*BindContractSlaResp, error)
	ListSlaStrategy(context.Context, *ListSlaStrategyReq) (*ListSlaStrategyResp, error)
	// ---- 索赔（FR-CTR-008）----
	CreateClaim(context.Context, *CreateClaimReq) (*CreateClaimResp, error)
	ApproveClaim(context.Context, *ApproveClaimReq) (*ApproveClaimResp, error)
	SettleClaim(context.Context, *SettleClaimReq) (*SettleClaimResp, error)
	ListClaim(context.Context, *ListClaimReq) (*ListClaimResp, error)
	// ---- 延保（FR-CTR-006：销售/衔接/转移/退款）----
	SellExtension(context.Context, *SellExtensionReq) (*SellExtensionResp, error)
	TransferExtension(context.Context, *TransferExtensionReq) (*TransferExtensionResp, error)
	RefundExtension(context.Context, *RefundExtensionReq) (*RefundExtensionResp, error)
	mustEmbedUnimplementedContractServer()
}

// UnimplementedContractServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContractServer struct{}

func (UnimplementedContractServer) Ping(context.Context, *PingReq) (*PingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedContractServer) CreateTemplate(context.Context, *CreateTemplateReq) (*CreateTemplateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedContractServer) RenderTemplate(context.Context, *RenderTemplateReq) (*RenderTemplateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderTemplate not implemented")
}
func (UnimplementedContractServer) CreateFromOrder(context.Context, *CreateFromOrderReq) (*CreateFromOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFromOrder not implemented")
}
func (UnimplementedContractServer) GetContract(context.Context, *GetContractReq) (*GetContractResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContract not implemented")
}
func (UnimplementedContractServer) ListContract(context.Context, *ListContractReq) (*ListContractResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContract not implemented")
}
func (UnimplementedContractServer) UploadContractFile(context.Context, *UploadContractFileReq) (*UploadContractFileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadContractFile not implemented")
}
func (UnimplementedContractServer) ArchiveContract(context.Context, *ArchiveContractReq) (*ArchiveContractResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveContract not implemented")
}
func (UnimplementedContractServer) ListWarranty(context.Context, *ListWarrantyReq) (*ListWarrantyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWarranty not implemented")
}
func (UnimplementedContractServer) GetWarrantyByTarget(context.Context, *GetWarrantyByTargetReq) (*GetWarrantyByTargetResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWarrantyByTarget not implemented")
}
func (UnimplementedContractServer) CreateSlaStrategy(context.Context, *CreateSlaStrategyReq) (*CreateSlaStrategyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSlaStrategy not implemented")
}
func (UnimplementedContractServer) BindContractSla(context.Context, *BindContractSlaReq) (*BindContractSlaResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BindContractSla not implemented")
}
func (UnimplementedContractServer) ListSlaStrategy(context.Context, *ListSlaStrategyReq) (*ListSlaStrategyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSlaStrategy not implemented")
}
func (UnimplementedContractServer) CreateClaim(context.Context, *CreateClaimReq) (*CreateClaimResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateClaim not implemented")
}
func (UnimplementedContractServer) ApproveClaim(context.Context, *ApproveClaimReq) (*ApproveClaimResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveClaim not implemented")
}
func (UnimplementedContractServer) SettleClaim(context.Context, *SettleClaimReq) (*SettleClaimResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SettleClaim not implemented")
}
func (UnimplementedContractServer) ListClaim(context.Context, *ListClaimReq) (*ListClaimResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClaim not implemented")
}
func (UnimplementedContractServer) SellExtension(context.Context, *SellExtensionReq) (*SellExtensionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SellExtension not implemented")
}
func (UnimplementedContractServer) TransferExtension(context.Context, *TransferExtensionReq) (*TransferExtensionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferExtension not implemented")
}
func (UnimplementedContractServer) RefundExtension(context.Context, *RefundExtensionReq) (*RefundExtensionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RefundExtension not implemented")
}
func (UnimplementedContractServer) mustEmbedUnimplementedContractServer() {}
func (UnimplementedContractServer) testEmbeddedByValue()                  {}

// UnsafeContractServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContractServer will
// result in compilation errors.
type UnsafeContractServer interface {
	mustEmbedUnimplementedContractServer()
}

func RegisterContractServer(s grpc.ServiceRegistrar, srv ContractServer) {
	// If the following call panics, it indicates UnimplementedContractServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Contract_ServiceDesc, srv)
}

func _Contract_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_CreateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).CreateTemplate(ctx, req.(*CreateTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_RenderTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).RenderTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_RenderTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).RenderTemplate(ctx, req.(*RenderTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_CreateFromOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFromOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).CreateFromOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_CreateFromOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).CreateFromOrder(ctx, req.(*CreateFromOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_GetContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContractReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).GetContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_GetContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).GetContract(ctx, req.(*GetContractReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_ListContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContractReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).ListContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_ListContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).ListContract(ctx, req.(*ListContractReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_UploadContractFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadContractFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).UploadContractFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_UploadContractFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).UploadContractFile(ctx, req.(*UploadContractFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_ArchiveContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveContractReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).ArchiveContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_ArchiveContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).ArchiveContract(ctx, req.(*ArchiveContractReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_ListWarranty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWarrantyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).ListWarranty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_ListWarranty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).ListWarranty(ctx, req.(*ListWarrantyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_GetWarrantyByTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWarrantyByTargetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).GetWarrantyByTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_GetWarrantyByTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).GetWarrantyByTarget(ctx, req.(*GetWarrantyByTargetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_CreateSlaStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSlaStrategyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).CreateSlaStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_CreateSlaStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).CreateSlaStrategy(ctx, req.(*CreateSlaStrategyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_BindContractSla_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindContractSlaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).BindContractSla(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_BindContractSla_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).BindContractSla(ctx, req.(*BindContractSlaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_ListSlaStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSlaStrategyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).ListSlaStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_ListSlaStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).ListSlaStrategy(ctx, req.(*ListSlaStrategyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_CreateClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClaimReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).CreateClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_CreateClaim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).CreateClaim(ctx, req.(*CreateClaimReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_ApproveClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveClaimReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).ApproveClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_ApproveClaim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).ApproveClaim(ctx, req.(*ApproveClaimReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_SettleClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleClaimReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).SettleClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_SettleClaim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).SettleClaim(ctx, req.(*SettleClaimReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_ListClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClaimReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).ListClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_ListClaim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).ListClaim(ctx, req.(*ListClaimReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_SellExtension_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SellExtensionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).SellExtension(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_SellExtension_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).SellExtension(ctx, req.(*SellExtensionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_TransferExtension_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferExtensionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).TransferExtension(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_TransferExtension_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).TransferExtension(ctx, req.(*TransferExtensionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_RefundExtension_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundExtensionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).RefundExtension(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contract_RefundExtension_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).RefundExtension(ctx, req.(*RefundExtensionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Contract_ServiceDesc is the grpc.ServiceDesc for Contract service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Contract_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contract.Contract",
	HandlerType: (*ContractServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Contract_Ping_Handler,
		},
		{
			MethodName: "CreateTemplate",
			Handler:    _Contract_CreateTemplate_Handler,
		},
		{
			MethodName: "RenderTemplate",
			Handler:    _Contract_RenderTemplate_Handler,
		},
		{
			MethodName: "CreateFromOrder",
			Handler:    _Contract_CreateFromOrder_Handler,
		},
		{
			MethodName: "GetContract",
			Handler:    _Contract_GetContract_Handler,
		},
		{
			MethodName: "ListContract",
			Handler:    _Contract_ListContract_Handler,
		},
		{
			MethodName: "UploadContractFile",
			Handler:    _Contract_UploadContractFile_Handler,
		},
		{
			MethodName: "ArchiveContract",
			Handler:    _Contract_ArchiveContract_Handler,
		},
		{
			MethodName: "ListWarranty",
			Handler:    _Contract_ListWarranty_Handler,
		},
		{
			MethodName: "GetWarrantyByTarget",
			Handler:    _Contract_GetWarrantyByTarget_Handler,
		},
		{
			MethodName: "CreateSlaStrategy",
			Handler:    _Contract_CreateSlaStrategy_Handler,
		},
		{
			MethodName: "BindContractSla",
			Handler:    _Contract_BindContractSla_Handler,
		},
		{
			MethodName: "ListSlaStrategy",
			Handler:    _Contract_ListSlaStrategy_Handler,
		},
		{
			MethodName: "CreateClaim",
			Handler:    _Contract_CreateClaim_Handler,
		},
		{
			MethodName: "ApproveClaim",
			Handler:    _Contract_ApproveClaim_Handler,
		},
		{
			MethodName: "SettleClaim",
			Handler:    _Contract_SettleClaim_Handler,
		},
		{
			MethodName: "ListClaim",
			Handler:    _Contract_ListClaim_Handler,
		},
		{
			MethodName: "SellExtension",
			Handler:    _Contract_SellExtension_Handler,
		},
		{
			MethodName: "TransferExtension",
			Handler:    _Contract_TransferExtension_Handler,
		},
		{
			MethodName: "RefundExtension",
			Handler:    _Contract_RefundExtension_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/contract/pb/contract.proto",
}
