// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: audit.proto

package server

import (
	"context"

	"micro-server/services/audit/internal/logic"
	"micro-server/services/audit/internal/svc"
	"micro-server/services/audit/pb"
)

type AuditServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAuditServer
}

func NewAuditServer(svcCtx *svc.ServiceContext) *AuditServer {
	return &AuditServer{
		svcCtx: svcCtx,
	}
}

func (s *AuditServer) Ping(ctx context.Context, in *pb.PingReq) (*pb.PingResp, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *AuditServer) WriteLog(ctx context.Context, in *pb.WriteLogReq) (*pb.WriteLogResp, error) {
	l := logic.NewWriteLogLogic(ctx, s.svcCtx)
	return l.WriteLog(in)
}

func (s *AuditServer) ListLog(ctx context.Context, in *pb.ListLogReq) (*pb.ListLogResp, error) {
	l := logic.NewListLogLogic(ctx, s.svcCtx)
	return l.ListLog(in)
}

func (s *AuditServer) WriteCmdLog(ctx context.Context, in *pb.WriteCmdLogReq) (*pb.WriteCmdLogResp, error) {
	l := logic.NewWriteCmdLogLogic(ctx, s.svcCtx)
	return l.WriteCmdLog(in)
}

func (s *AuditServer) ListCmdLog(ctx context.Context, in *pb.ListCmdLogReq) (*pb.ListCmdLogResp, error) {
	l := logic.NewListCmdLogLogic(ctx, s.svcCtx)
	return l.ListCmdLog(in)
}
