// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: contract.proto

package contract

import (
	"context"

	"micro-server/services/contract/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApproveClaimReq         = pb.ApproveClaimReq
	ApproveClaimResp        = pb.ApproveClaimResp
	ArchiveContractReq      = pb.ArchiveContractReq
	ArchiveContractResp     = pb.ArchiveContractResp
	BindContractSlaReq      = pb.BindContractSlaReq
	BindContractSlaResp     = pb.BindContractSlaResp
	ClaimDetail             = pb.ClaimDetail
	ContractDetail          = pb.ContractDetail
	ContractFile            = pb.ContractFile
	ContractTarget          = pb.ContractTarget
	CreateClaimReq          = pb.CreateClaimReq
	CreateClaimResp         = pb.CreateClaimResp
	CreateFromOrderReq      = pb.CreateFromOrderReq
	CreateFromOrderResp     = pb.CreateFromOrderResp
	CreateSlaStrategyReq    = pb.CreateSlaStrategyReq
	CreateSlaStrategyResp   = pb.CreateSlaStrategyResp
	CreateTemplateReq       = pb.CreateTemplateReq
	CreateTemplateResp      = pb.CreateTemplateResp
	GetContractReq          = pb.GetContractReq
	GetContractResp         = pb.GetContractResp
	GetWarrantyByTargetReq  = pb.GetWarrantyByTargetReq
	GetWarrantyByTargetResp = pb.GetWarrantyByTargetResp
	ListClaimReq            = pb.ListClaimReq
	ListClaimResp           = pb.ListClaimResp
	ListContractReq         = pb.ListContractReq
	ListContractResp        = pb.ListContractResp
	ListSlaStrategyReq      = pb.ListSlaStrategyReq
	ListSlaStrategyResp     = pb.ListSlaStrategyResp
	ListWarrantyReq         = pb.ListWarrantyReq
	ListWarrantyResp        = pb.ListWarrantyResp
	PingReq                 = pb.PingReq
	PingResp                = pb.PingResp
	RefundExtensionReq      = pb.RefundExtensionReq
	RefundExtensionResp     = pb.RefundExtensionResp
	RenderTemplateReq       = pb.RenderTemplateReq
	RenderTemplateResp      = pb.RenderTemplateResp
	SellExtensionReq        = pb.SellExtensionReq
	SellExtensionResp       = pb.SellExtensionResp
	SettleClaimReq          = pb.SettleClaimReq
	SettleClaimResp         = pb.SettleClaimResp
	SlaStrategyDetail       = pb.SlaStrategyDetail
	TransferExtensionReq    = pb.TransferExtensionReq
	TransferExtensionResp   = pb.TransferExtensionResp
	UploadContractFileReq   = pb.UploadContractFileReq
	UploadContractFileResp  = pb.UploadContractFileResp
	WarrantyItem            = pb.WarrantyItem

	Contract interface {
		Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
		// ---- 模板（L2）----
		CreateTemplate(ctx context.Context, in *CreateTemplateReq, opts ...grpc.CallOption) (*CreateTemplateResp, error)
		RenderTemplate(ctx context.Context, in *RenderTemplateReq, opts ...grpc.CallOption) (*RenderTemplateResp, error)
		// ---- 合同 ----
		CreateFromOrder(ctx context.Context, in *CreateFromOrderReq, opts ...grpc.CallOption) (*CreateFromOrderResp, error)
		GetContract(ctx context.Context, in *GetContractReq, opts ...grpc.CallOption) (*GetContractResp, error)
		ListContract(ctx context.Context, in *ListContractReq, opts ...grpc.CallOption) (*ListContractResp, error)
		UploadContractFile(ctx context.Context, in *UploadContractFileReq, opts ...grpc.CallOption) (*UploadContractFileResp, error)
		ArchiveContract(ctx context.Context, in *ArchiveContractReq, opts ...grpc.CallOption) (*ArchiveContractResp, error)
		// ---- 质保 ----
		ListWarranty(ctx context.Context, in *ListWarrantyReq, opts ...grpc.CallOption) (*ListWarrantyResp, error)
		GetWarrantyByTarget(ctx context.Context, in *GetWarrantyByTargetReq, opts ...grpc.CallOption) (*GetWarrantyByTargetResp, error)
		// ---- SLA（FR-CTR-007）----
		CreateSlaStrategy(ctx context.Context, in *CreateSlaStrategyReq, opts ...grpc.CallOption) (*CreateSlaStrategyResp, error)
		BindContractSla(ctx context.Context, in *BindContractSlaReq, opts ...grpc.CallOption) (*BindContractSlaResp, error)
		ListSlaStrategy(ctx context.Context, in *ListSlaStrategyReq, opts ...grpc.CallOption) (*ListSlaStrategyResp, error)
		// ---- 索赔（FR-CTR-008）----
		CreateClaim(ctx context.Context, in *CreateClaimReq, opts ...grpc.CallOption) (*CreateClaimResp, error)
		ApproveClaim(ctx context.Context, in *ApproveClaimReq, opts ...grpc.CallOption) (*ApproveClaimResp, error)
		SettleClaim(ctx context.Context, in *SettleClaimReq, opts ...grpc.CallOption) (*SettleClaimResp, error)
		ListClaim(ctx context.Context, in *ListClaimReq, opts ...grpc.CallOption) (*ListClaimResp, error)
		// ---- 延保（FR-CTR-006：销售/衔接/转移/退款）----
		SellExtension(ctx context.Context, in *SellExtensionReq, opts ...grpc.CallOption) (*SellExtensionResp, error)
		TransferExtension(ctx context.Context, in *TransferExtensionReq, opts ...grpc.CallOption) (*TransferExtensionResp, error)
		RefundExtension(ctx context.Context, in *RefundExtensionReq, opts ...grpc.CallOption) (*RefundExtensionResp, error)
	}

	defaultContract struct {
		cli zrpc.Client
	}
)

func NewContract(cli zrpc.Client) Contract {
	return &defaultContract{
		cli: cli,
	}
}

func (m *defaultContract) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

// ---- 模板（L2）----
func (m *defaultContract) CreateTemplate(ctx context.Context, in *CreateTemplateReq, opts ...grpc.CallOption) (*CreateTemplateResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.CreateTemplate(ctx, in, opts...)
}

func (m *defaultContract) RenderTemplate(ctx context.Context, in *RenderTemplateReq, opts ...grpc.CallOption) (*RenderTemplateResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.RenderTemplate(ctx, in, opts...)
}

// ---- 合同 ----
func (m *defaultContract) CreateFromOrder(ctx context.Context, in *CreateFromOrderReq, opts ...grpc.CallOption) (*CreateFromOrderResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.CreateFromOrder(ctx, in, opts...)
}

func (m *defaultContract) GetContract(ctx context.Context, in *GetContractReq, opts ...grpc.CallOption) (*GetContractResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.GetContract(ctx, in, opts...)
}

func (m *defaultContract) ListContract(ctx context.Context, in *ListContractReq, opts ...grpc.CallOption) (*ListContractResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.ListContract(ctx, in, opts...)
}

func (m *defaultContract) UploadContractFile(ctx context.Context, in *UploadContractFileReq, opts ...grpc.CallOption) (*UploadContractFileResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.UploadContractFile(ctx, in, opts...)
}

func (m *defaultContract) ArchiveContract(ctx context.Context, in *ArchiveContractReq, opts ...grpc.CallOption) (*ArchiveContractResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.ArchiveContract(ctx, in, opts...)
}

// ---- 质保 ----
func (m *defaultContract) ListWarranty(ctx context.Context, in *ListWarrantyReq, opts ...grpc.CallOption) (*ListWarrantyResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.ListWarranty(ctx, in, opts...)
}

func (m *defaultContract) GetWarrantyByTarget(ctx context.Context, in *GetWarrantyByTargetReq, opts ...grpc.CallOption) (*GetWarrantyByTargetResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.GetWarrantyByTarget(ctx, in, opts...)
}

// ---- SLA（FR-CTR-007）----
func (m *defaultContract) CreateSlaStrategy(ctx context.Context, in *CreateSlaStrategyReq, opts ...grpc.CallOption) (*CreateSlaStrategyResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.CreateSlaStrategy(ctx, in, opts...)
}

func (m *defaultContract) BindContractSla(ctx context.Context, in *BindContractSlaReq, opts ...grpc.CallOption) (*BindContractSlaResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.BindContractSla(ctx, in, opts...)
}

func (m *defaultContract) ListSlaStrategy(ctx context.Context, in *ListSlaStrategyReq, opts ...grpc.CallOption) (*ListSlaStrategyResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.ListSlaStrategy(ctx, in, opts...)
}

// ---- 索赔（FR-CTR-008）----
func (m *defaultContract) CreateClaim(ctx context.Context, in *CreateClaimReq, opts ...grpc.CallOption) (*CreateClaimResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.CreateClaim(ctx, in, opts...)
}

func (m *defaultContract) ApproveClaim(ctx context.Context, in *ApproveClaimReq, opts ...grpc.CallOption) (*ApproveClaimResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.ApproveClaim(ctx, in, opts...)
}

func (m *defaultContract) SettleClaim(ctx context.Context, in *SettleClaimReq, opts ...grpc.CallOption) (*SettleClaimResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.SettleClaim(ctx, in, opts...)
}

func (m *defaultContract) ListClaim(ctx context.Context, in *ListClaimReq, opts ...grpc.CallOption) (*ListClaimResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.ListClaim(ctx, in, opts...)
}

// ---- 延保（FR-CTR-006：销售/衔接/转移/退款）----
func (m *defaultContract) SellExtension(ctx context.Context, in *SellExtensionReq, opts ...grpc.CallOption) (*SellExtensionResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.SellExtension(ctx, in, opts...)
}

func (m *defaultContract) TransferExtension(ctx context.Context, in *TransferExtensionReq, opts ...grpc.CallOption) (*TransferExtensionResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.TransferExtension(ctx, in, opts...)
}

func (m *defaultContract) RefundExtension(ctx context.Context, in *RefundExtensionReq, opts ...grpc.CallOption) (*RefundExtensionResp, error) {
	client := pb.NewContractClient(m.cli.Conn())
	return client.RefundExtension(ctx, in, opts...)
}
