// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.4
// source: pb/notification.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_pb_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{0}
}

type PingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResp) Reset() {
	*x = PingResp{}
	mi := &file_pb_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResp) ProtoMessage() {}

func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{1}
}

func (x *PingResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type MessageItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	IsRead        bool                   `protobuf:"varint,5,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	BizType       string                 `protobuf:"bytes,6,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"`
	BizId         string                 `protobuf:"bytes,7,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageItem) Reset() {
	*x = MessageItem{}
	mi := &file_pb_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageItem) ProtoMessage() {}

func (x *MessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageItem.ProtoReflect.Descriptor instead.
func (*MessageItem) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{2}
}

func (x *MessageItem) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MessageItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MessageItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MessageItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageItem) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *MessageItem) GetBizType() string {
	if x != nil {
		return x.BizType
	}
	return ""
}

func (x *MessageItem) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *MessageItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListMessagesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OnlyUnread    bool                   `protobuf:"varint,2,opt,name=only_unread,json=onlyUnread,proto3" json:"only_unread,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesReq) Reset() {
	*x = ListMessagesReq{}
	mi := &file_pb_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesReq) ProtoMessage() {}

func (x *ListMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesReq.ProtoReflect.Descriptor instead.
func (*ListMessagesReq) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{3}
}

func (x *ListMessagesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListMessagesReq) GetOnlyUnread() bool {
	if x != nil {
		return x.OnlyUnread
	}
	return false
}

func (x *ListMessagesReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMessagesReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListMessagesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*MessageItem         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResp) Reset() {
	*x = ListMessagesResp{}
	mi := &file_pb_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResp) ProtoMessage() {}

func (x *ListMessagesResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResp.ProtoReflect.Descriptor instead.
func (*ListMessagesResp) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{4}
}

func (x *ListMessagesResp) GetList() []*MessageItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListMessagesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type MarkReadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 越权防护：仅本人可标记
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadReq) Reset() {
	*x = MarkReadReq{}
	mi := &file_pb_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadReq) ProtoMessage() {}

func (x *MarkReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadReq.ProtoReflect.Descriptor instead.
func (*MarkReadReq) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{5}
}

func (x *MarkReadReq) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MarkReadReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MarkReadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadResp) Reset() {
	*x = MarkReadResp{}
	mi := &file_pb_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadResp) ProtoMessage() {}

func (x *MarkReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadResp.ProtoReflect.Descriptor instead.
func (*MarkReadResp) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{6}
}

type UnreadCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnreadCountReq) Reset() {
	*x = UnreadCountReq{}
	mi := &file_pb_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadCountReq) ProtoMessage() {}

func (x *UnreadCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadCountReq.ProtoReflect.Descriptor instead.
func (*UnreadCountReq) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{7}
}

func (x *UnreadCountReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UnreadCountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnreadCountResp) Reset() {
	*x = UnreadCountResp{}
	mi := &file_pb_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadCountResp) ProtoMessage() {}

func (x *UnreadCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadCountResp.ProtoReflect.Descriptor instead.
func (*UnreadCountResp) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{8}
}

func (x *UnreadCountResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TemplateItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TemplateId      int64                  `protobuf:"varint,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Code            string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	TitleTemplate   string                 `protobuf:"bytes,3,opt,name=title_template,json=titleTemplate,proto3" json:"title_template,omitempty"`
	ContentTemplate string                 `protobuf:"bytes,4,opt,name=content_template,json=contentTemplate,proto3" json:"content_template,omitempty"`
	Channel         string                 `protobuf:"bytes,5,opt,name=channel,proto3" json:"channel,omitempty"`
	Status          int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TemplateItem) Reset() {
	*x = TemplateItem{}
	mi := &file_pb_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateItem) ProtoMessage() {}

func (x *TemplateItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateItem.ProtoReflect.Descriptor instead.
func (*TemplateItem) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{9}
}

func (x *TemplateItem) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *TemplateItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TemplateItem) GetTitleTemplate() string {
	if x != nil {
		return x.TitleTemplate
	}
	return ""
}

func (x *TemplateItem) GetContentTemplate() string {
	if x != nil {
		return x.ContentTemplate
	}
	return ""
}

func (x *TemplateItem) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *TemplateItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpsertTemplateReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	TitleTemplate   string                 `protobuf:"bytes,2,opt,name=title_template,json=titleTemplate,proto3" json:"title_template,omitempty"`
	ContentTemplate string                 `protobuf:"bytes,3,opt,name=content_template,json=contentTemplate,proto3" json:"content_template,omitempty"`
	Channel         string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"` // INBOX/SMS
	Status          int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`  // 0 = 不修改
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpsertTemplateReq) Reset() {
	*x = UpsertTemplateReq{}
	mi := &file_pb_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTemplateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTemplateReq) ProtoMessage() {}

func (x *UpsertTemplateReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTemplateReq.ProtoReflect.Descriptor instead.
func (*UpsertTemplateReq) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{10}
}

func (x *UpsertTemplateReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpsertTemplateReq) GetTitleTemplate() string {
	if x != nil {
		return x.TitleTemplate
	}
	return ""
}

func (x *UpsertTemplateReq) GetContentTemplate() string {
	if x != nil {
		return x.ContentTemplate
	}
	return ""
}

func (x *UpsertTemplateReq) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *UpsertTemplateReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpsertTemplateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTemplateResp) Reset() {
	*x = UpsertTemplateResp{}
	mi := &file_pb_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTemplateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTemplateResp) ProtoMessage() {}

func (x *UpsertTemplateResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTemplateResp.ProtoReflect.Descriptor instead.
func (*UpsertTemplateResp) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{11}
}

type ListTemplateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"` // code 模糊
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplateReq) Reset() {
	*x = ListTemplateReq{}
	mi := &file_pb_notification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplateReq) ProtoMessage() {}

func (x *ListTemplateReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplateReq.ProtoReflect.Descriptor instead.
func (*ListTemplateReq) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{12}
}

func (x *ListTemplateReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListTemplateReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTemplateReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListTemplateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*TemplateItem        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplateResp) Reset() {
	*x = ListTemplateResp{}
	mi := &file_pb_notification_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplateResp) ProtoMessage() {}

func (x *ListTemplateResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplateResp.ProtoReflect.Descriptor instead.
func (*ListTemplateResp) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{13}
}

func (x *ListTemplateResp) GetList() []*TemplateItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListTemplateResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UserSettingItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TemplateCode  string                 `protobuf:"bytes,2,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"` // '*' = 全局默认
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	QuietHours    string                 `protobuf:"bytes,4,opt,name=quiet_hours,json=quietHours,proto3" json:"quiet_hours,omitempty"` // JSON {"start":"22:00","end":"08:00"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSettingItem) Reset() {
	*x = UserSettingItem{}
	mi := &file_pb_notification_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettingItem) ProtoMessage() {}

func (x *UserSettingItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettingItem.ProtoReflect.Descriptor instead.
func (*UserSettingItem) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{14}
}

func (x *UserSettingItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserSettingItem) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *UserSettingItem) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UserSettingItem) GetQuietHours() string {
	if x != nil {
		return x.QuietHours
	}
	return ""
}

type GetUserSettingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TemplateCode  string                 `protobuf:"bytes,2,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"` // 空 = 全部设置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettingReq) Reset() {
	*x = GetUserSettingReq{}
	mi := &file_pb_notification_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettingReq) ProtoMessage() {}

func (x *GetUserSettingReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettingReq.ProtoReflect.Descriptor instead.
func (*GetUserSettingReq) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserSettingReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserSettingReq) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

type GetUserSettingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserSettingItem     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettingResp) Reset() {
	*x = GetUserSettingResp{}
	mi := &file_pb_notification_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettingResp) ProtoMessage() {}

func (x *GetUserSettingResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettingResp.ProtoReflect.Descriptor instead.
func (*GetUserSettingResp) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserSettingResp) GetList() []*UserSettingItem {
	if x != nil {
		return x.List
	}
	return nil
}

type UpdateUserSettingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TemplateCode  string                 `protobuf:"bytes,2,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	QuietHours    string                 `protobuf:"bytes,4,opt,name=quiet_hours,json=quietHours,proto3" json:"quiet_hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserSettingReq) Reset() {
	*x = UpdateUserSettingReq{}
	mi := &file_pb_notification_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserSettingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserSettingReq) ProtoMessage() {}

func (x *UpdateUserSettingReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserSettingReq.ProtoReflect.Descriptor instead.
func (*UpdateUserSettingReq) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateUserSettingReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserSettingReq) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *UpdateUserSettingReq) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpdateUserSettingReq) GetQuietHours() string {
	if x != nil {
		return x.QuietHours
	}
	return ""
}

type UpdateUserSettingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserSettingResp) Reset() {
	*x = UpdateUserSettingResp{}
	mi := &file_pb_notification_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserSettingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserSettingResp) ProtoMessage() {}

func (x *UpdateUserSettingResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserSettingResp.ProtoReflect.Descriptor instead.
func (*UpdateUserSettingResp) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{18}
}

// DeliverReq 与 notification_request 事件 payload 同构（管理端手动投递/测试桩复用内核）。
type DeliverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TemplateCode  string                 `protobuf:"bytes,2,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`
	ParamsJson    string                 `protobuf:"bytes,3,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"` // 模板渲染参数 {"order_no":"..."}
	BizType       string                 `protobuf:"bytes,4,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"`
	BizId         string                 `protobuf:"bytes,5,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverReq) Reset() {
	*x = DeliverReq{}
	mi := &file_pb_notification_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverReq) ProtoMessage() {}

func (x *DeliverReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverReq.ProtoReflect.Descriptor instead.
func (*DeliverReq) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{19}
}

func (x *DeliverReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeliverReq) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *DeliverReq) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

func (x *DeliverReq) GetBizType() string {
	if x != nil {
		return x.BizType
	}
	return ""
}

func (x *DeliverReq) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

type DeliverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivered     bool                   `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"`                  // false = 被频控/免打扰/模板缺失过滤
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                         // 过滤原因（观测用）
	MessageId     int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // 站内信 ID（INBOX 渠道）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverResp) Reset() {
	*x = DeliverResp{}
	mi := &file_pb_notification_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverResp) ProtoMessage() {}

func (x *DeliverResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_notification_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverResp.ProtoReflect.Descriptor instead.
func (*DeliverResp) Descriptor() ([]byte, []int) {
	return file_pb_notification_proto_rawDescGZIP(), []int{20}
}

func (x *DeliverResp) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *DeliverResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DeliverResp) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

var File_pb_notification_proto protoreflect.FileDescriptor

const file_pb_notification_proto_rawDesc = "" +
	"\n" +
	"\x15pb/notification.proto\x12\fnotification\"\t\n" +
	"\aPingReq\"\x1e\n" +
	"\bPingResp\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\"\xdf\x01\n" +
	"\vMessageItem\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x17\n" +
	"\ais_read\x18\x05 \x01(\bR\x06isRead\x12\x19\n" +
	"\bbiz_type\x18\x06 \x01(\tR\abizType\x12\x15\n" +
	"\x06biz_id\x18\a \x01(\tR\x05bizId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"s\n" +
	"\x0fListMessagesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vonly_unread\x18\x02 \x01(\bR\n" +
	"onlyUnread\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"W\n" +
	"\x10ListMessagesResp\x12-\n" +
	"\x04list\x18\x01 \x03(\v2\x19.notification.MessageItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"E\n" +
	"\vMarkReadReq\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x0e\n" +
	"\fMarkReadResp\")\n" +
	"\x0eUnreadCountReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"'\n" +
	"\x0fUnreadCountResp\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\xc7\x01\n" +
	"\fTemplateItem\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\x03R\n" +
	"templateId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12%\n" +
	"\x0etitle_template\x18\x03 \x01(\tR\rtitleTemplate\x12)\n" +
	"\x10content_template\x18\x04 \x01(\tR\x0fcontentTemplate\x12\x18\n" +
	"\achannel\x18\x05 \x01(\tR\achannel\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"\xab\x01\n" +
	"\x11UpsertTemplateReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12%\n" +
	"\x0etitle_template\x18\x02 \x01(\tR\rtitleTemplate\x12)\n" +
	"\x10content_template\x18\x03 \x01(\tR\x0fcontentTemplate\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"\x14\n" +
	"\x12UpsertTemplateResp\"S\n" +
	"\x0fListTemplateReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"X\n" +
	"\x10ListTemplateResp\x12.\n" +
	"\x04list\x18\x01 \x03(\v2\x1a.notification.TemplateItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x8a\x01\n" +
	"\x0fUserSettingItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12#\n" +
	"\rtemplate_code\x18\x02 \x01(\tR\ftemplateCode\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x1f\n" +
	"\vquiet_hours\x18\x04 \x01(\tR\n" +
	"quietHours\"Q\n" +
	"\x11GetUserSettingReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12#\n" +
	"\rtemplate_code\x18\x02 \x01(\tR\ftemplateCode\"G\n" +
	"\x12GetUserSettingResp\x121\n" +
	"\x04list\x18\x01 \x03(\v2\x1d.notification.UserSettingItemR\x04list\"\x8f\x01\n" +
	"\x14UpdateUserSettingReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12#\n" +
	"\rtemplate_code\x18\x02 \x01(\tR\ftemplateCode\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x1f\n" +
	"\vquiet_hours\x18\x04 \x01(\tR\n" +
	"quietHours\"\x17\n" +
	"\x15UpdateUserSettingResp\"\x9d\x01\n" +
	"\n" +
	"DeliverReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12#\n" +
	"\rtemplate_code\x18\x02 \x01(\tR\ftemplateCode\x12\x1f\n" +
	"\vparams_json\x18\x03 \x01(\tR\n" +
	"paramsJson\x12\x19\n" +
	"\bbiz_type\x18\x04 \x01(\tR\abizType\x12\x15\n" +
	"\x06biz_id\x18\x05 \x01(\tR\x05bizId\"b\n" +
	"\vDeliverResp\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\bR\tdelivered\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId2\xba\x05\n" +
	"\fNotification\x125\n" +
	"\x04Ping\x12\x15.notification.PingReq\x1a\x16.notification.PingResp\x12M\n" +
	"\fListMessages\x12\x1d.notification.ListMessagesReq\x1a\x1e.notification.ListMessagesResp\x12A\n" +
	"\bMarkRead\x12\x19.notification.MarkReadReq\x1a\x1a.notification.MarkReadResp\x12J\n" +
	"\vUnreadCount\x12\x1c.notification.UnreadCountReq\x1a\x1d.notification.UnreadCountResp\x12S\n" +
	"\x0eUpsertTemplate\x12\x1f.notification.UpsertTemplateReq\x1a .notification.UpsertTemplateResp\x12M\n" +
	"\fListTemplate\x12\x1d.notification.ListTemplateReq\x1a\x1e.notification.ListTemplateResp\x12S\n" +
	"\x0eGetUserSetting\x12\x1f.notification.GetUserSettingReq\x1a .notification.GetUserSettingResp\x12\\\n" +
	"\x11UpdateUserSetting\x12\".notification.UpdateUserSettingReq\x1a#.notification.UpdateUserSettingResp\x12>\n" +
	"\aDeliver\x12\x18.notification.DeliverReq\x1a\x19.notification.DeliverRespB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_notification_proto_rawDescOnce sync.Once
	file_pb_notification_proto_rawDescData []byte
)

func file_pb_notification_proto_rawDescGZIP() []byte {
	file_pb_notification_proto_rawDescOnce.Do(func() {
		file_pb_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_notification_proto_rawDesc), len(file_pb_notification_proto_rawDesc)))
	})
	return file_pb_notification_proto_rawDescData
}

var file_pb_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_pb_notification_proto_goTypes = []any{
	(*PingReq)(nil),               // 0: notification.PingReq
	(*PingResp)(nil),              // 1: notification.PingResp
	(*MessageItem)(nil),           // 2: notification.MessageItem
	(*ListMessagesReq)(nil),       // 3: notification.ListMessagesReq
	(*ListMessagesResp)(nil),      // 4: notification.ListMessagesResp
	(*MarkReadReq)(nil),           // 5: notification.MarkReadReq
	(*MarkReadResp)(nil),          // 6: notification.MarkReadResp
	(*UnreadCountReq)(nil),        // 7: notification.UnreadCountReq
	(*UnreadCountResp)(nil),       // 8: notification.UnreadCountResp
	(*TemplateItem)(nil),          // 9: notification.TemplateItem
	(*UpsertTemplateReq)(nil),     // 10: notification.UpsertTemplateReq
	(*UpsertTemplateResp)(nil),    // 11: notification.UpsertTemplateResp
	(*ListTemplateReq)(nil),       // 12: notification.ListTemplateReq
	(*ListTemplateResp)(nil),      // 13: notification.ListTemplateResp
	(*UserSettingItem)(nil),       // 14: notification.UserSettingItem
	(*GetUserSettingReq)(nil),     // 15: notification.GetUserSettingReq
	(*GetUserSettingResp)(nil),    // 16: notification.GetUserSettingResp
	(*UpdateUserSettingReq)(nil),  // 17: notification.UpdateUserSettingReq
	(*UpdateUserSettingResp)(nil), // 18: notification.UpdateUserSettingResp
	(*DeliverReq)(nil),            // 19: notification.DeliverReq
	(*DeliverResp)(nil),           // 20: notification.DeliverResp
}
var file_pb_notification_proto_depIdxs = []int32{
	2,  // 0: notification.ListMessagesResp.list:type_name -> notification.MessageItem
	9,  // 1: notification.ListTemplateResp.list:type_name -> notification.TemplateItem
	14, // 2: notification.GetUserSettingResp.list:type_name -> notification.UserSettingItem
	0,  // 3: notification.Notification.Ping:input_type -> notification.PingReq
	3,  // 4: notification.Notification.ListMessages:input_type -> notification.ListMessagesReq
	5,  // 5: notification.Notification.MarkRead:input_type -> notification.MarkReadReq
	7,  // 6: notification.Notification.UnreadCount:input_type -> notification.UnreadCountReq
	10, // 7: notification.Notification.UpsertTemplate:input_type -> notification.UpsertTemplateReq
	12, // 8: notification.Notification.ListTemplate:input_type -> notification.ListTemplateReq
	15, // 9: notification.Notification.GetUserSetting:input_type -> notification.GetUserSettingReq
	17, // 10: notification.Notification.UpdateUserSetting:input_type -> notification.UpdateUserSettingReq
	19, // 11: notification.Notification.Deliver:input_type -> notification.DeliverReq
	1,  // 12: notification.Notification.Ping:output_type -> notification.PingResp
	4,  // 13: notification.Notification.ListMessages:output_type -> notification.ListMessagesResp
	6,  // 14: notification.Notification.MarkRead:output_type -> notification.MarkReadResp
	8,  // 15: notification.Notification.UnreadCount:output_type -> notification.UnreadCountResp
	11, // 16: notification.Notification.UpsertTemplate:output_type -> notification.UpsertTemplateResp
	13, // 17: notification.Notification.ListTemplate:output_type -> notification.ListTemplateResp
	16, // 18: notification.Notification.GetUserSetting:output_type -> notification.GetUserSettingResp
	18, // 19: notification.Notification.UpdateUserSetting:output_type -> notification.UpdateUserSettingResp
	20, // 20: notification.Notification.Deliver:output_type -> notification.DeliverResp
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pb_notification_proto_init() }
func file_pb_notification_proto_init() {
	if File_pb_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_notification_proto_rawDesc), len(file_pb_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_notification_proto_goTypes,
		DependencyIndexes: file_pb_notification_proto_depIdxs,
		MessageInfos:      file_pb_notification_proto_msgTypes,
	}.Build()
	File_pb_notification_proto = out.File
	file_pb_notification_proto_goTypes = nil
	file_pb_notification_proto_depIdxs = nil
}
