// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderItemFieldNames          = builder.RawFieldNames(&OrderItem{})
	orderItemRows                = strings.Join(orderItemFieldNames, ",")
	orderItemRowsExpectAutoSet   = strings.Join(stringx.Remove(orderItemFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	orderItemRowsWithPlaceHolder = strings.Join(stringx.Remove(orderItemFieldNames, "`item_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheOrderItemItemIdPrefix = "cache:orderItem:itemId:"
)

type (
	orderItemModel interface {
		Insert(ctx context.Context, data *OrderItem) (sql.Result, error)
		FindOne(ctx context.Context, itemId int64) (*OrderItem, error)
		Update(ctx context.Context, data *OrderItem) error
		Delete(ctx context.Context, itemId int64) error
	}

	defaultOrderItemModel struct {
		sqlc.CachedConn
		table string
	}

	OrderItem struct {
		ItemId      int64          `db:"item_id"`      // 雪花 ID
		OrderId     int64          `db:"order_id"`     // 所属订单
		SkuId       int64          `db:"sku_id"`       // SKU
		SkuName     string         `db:"sku_name"`     // SKU 名称快照
		Sn          sql.NullString `db:"sn"`           // 设备 SN（DEVICE 单）
		WarehouseId int64          `db:"warehouse_id"` // 出库仓（Reserve/DeductLocked 指定）
		Qty         int64          `db:"qty"`          // 数量
		UnitPrice   float64        `db:"unit_price"`   // 单价快照
		Amount      float64        `db:"amount"`       // 小计
		OutQty      int64          `db:"out_qty"`      // 已出库确认数（stock_out 回写，per (order,sku) 幂等）
		TenantId    int64          `db:"tenant_id"`    // 租户 ID
		CreatedAt   time.Time      `db:"created_at"`   // 创建时间
		CreatedBy   sql.NullInt64  `db:"created_by"`   // 创建人 uid
		UpdatedAt   time.Time      `db:"updated_at"`   // 更新时间
		UpdatedBy   sql.NullInt64  `db:"updated_by"`   // 更新人 uid
		DeletedAt   sql.NullTime   `db:"deleted_at"`   // 软删标记(NULL=有效)
	}
)

func newOrderItemModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOrderItemModel {
	return &defaultOrderItemModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`order_item`",
	}
}

func (m *defaultOrderItemModel) Delete(ctx context.Context, itemId int64) error {
	orderItemItemIdKey := fmt.Sprintf("%s%v", cacheOrderItemItemIdPrefix, itemId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `item_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, itemId)
	}, orderItemItemIdKey)
	return err
}

func (m *defaultOrderItemModel) FindOne(ctx context.Context, itemId int64) (*OrderItem, error) {
	orderItemItemIdKey := fmt.Sprintf("%s%v", cacheOrderItemItemIdPrefix, itemId)
	var resp OrderItem
	err := m.QueryRowCtx(ctx, &resp, orderItemItemIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `item_id` = ? limit 1", orderItemRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, itemId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderItemModel) Insert(ctx context.Context, data *OrderItem) (sql.Result, error) {
	orderItemItemIdKey := fmt.Sprintf("%s%v", cacheOrderItemItemIdPrefix, data.ItemId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, orderItemRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ItemId, data.OrderId, data.SkuId, data.SkuName, data.Sn, data.WarehouseId, data.Qty, data.UnitPrice, data.Amount, data.OutQty, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt)
	}, orderItemItemIdKey)
	return ret, err
}

func (m *defaultOrderItemModel) Update(ctx context.Context, data *OrderItem) error {
	orderItemItemIdKey := fmt.Sprintf("%s%v", cacheOrderItemItemIdPrefix, data.ItemId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `item_id` = ?", m.table, orderItemRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.OrderId, data.SkuId, data.SkuName, data.Sn, data.WarehouseId, data.Qty, data.UnitPrice, data.Amount, data.OutQty, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt, data.ItemId)
	}, orderItemItemIdKey)
	return err
}

func (m *defaultOrderItemModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheOrderItemItemIdPrefix, primary)
}

func (m *defaultOrderItemModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `item_id` = ? limit 1", orderItemRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOrderItemModel) tableName() string {
	return m.table
}
