// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	returnOrderFieldNames          = builder.RawFieldNames(&ReturnOrder{})
	returnOrderRows                = strings.Join(returnOrderFieldNames, ",")
	returnOrderRowsExpectAutoSet   = strings.Join(stringx.Remove(returnOrderFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	returnOrderRowsWithPlaceHolder = strings.Join(stringx.Remove(returnOrderFieldNames, "`return_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheReturnOrderReturnIdPrefix         = "cache:returnOrder:returnId:"
	cacheReturnOrderTenantIdReturnNoPrefix = "cache:returnOrder:tenantId:returnNo:"
)

type (
	returnOrderModel interface {
		Insert(ctx context.Context, data *ReturnOrder) (sql.Result, error)
		FindOne(ctx context.Context, returnId int64) (*ReturnOrder, error)
		FindOneByTenantIdReturnNo(ctx context.Context, tenantId int64, returnNo string) (*ReturnOrder, error)
		Update(ctx context.Context, data *ReturnOrder) error
		Delete(ctx context.Context, returnId int64) error
	}

	defaultReturnOrderModel struct {
		sqlc.CachedConn
		table string
	}

	ReturnOrder struct {
		ReturnId     int64           `db:"return_id"`     // 雪花 ID
		ReturnNo     string          `db:"return_no"`     // 退货单号（order_return_approved 事件 key）
		OrderId      int64           `db:"order_id"`      // 原销售单
		OrderNo      string          `db:"order_no"`      // 原销售单号
		Reason       sql.NullString  `db:"reason"`        // 退货原因
		Status       string          `db:"status"`        // APPLYING/APPROVED/REJECTED/REFUNDED
		RefundAmount sql.NullFloat64 `db:"refund_amount"` // 退款金额（按退货明细 × 单价快照计）
		RefundNo     sql.NullString  `db:"refund_no"`     // 退款单号（payment_refunded 事件回写）
		RejectReason sql.NullString  `db:"reject_reason"` // 驳回原因
		TenantId     int64           `db:"tenant_id"`     // 租户 ID
		CreatedAt    time.Time       `db:"created_at"`    // 创建时间
		CreatedBy    sql.NullInt64   `db:"created_by"`    // 创建人 uid
		UpdatedAt    time.Time       `db:"updated_at"`    // 更新时间
		UpdatedBy    sql.NullInt64   `db:"updated_by"`    // 更新人 uid
		DeletedAt    sql.NullTime    `db:"deleted_at"`    // 软删标记(NULL=有效)
	}
)

func newReturnOrderModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultReturnOrderModel {
	return &defaultReturnOrderModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`return_order`",
	}
}

func (m *defaultReturnOrderModel) Delete(ctx context.Context, returnId int64) error {
	data, err := m.FindOne(ctx, returnId)
	if err != nil {
		return err
	}

	returnOrderReturnIdKey := fmt.Sprintf("%s%v", cacheReturnOrderReturnIdPrefix, returnId)
	returnOrderTenantIdReturnNoKey := fmt.Sprintf("%s%v:%v", cacheReturnOrderTenantIdReturnNoPrefix, data.TenantId, data.ReturnNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `return_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, returnId)
	}, returnOrderReturnIdKey, returnOrderTenantIdReturnNoKey)
	return err
}

func (m *defaultReturnOrderModel) FindOne(ctx context.Context, returnId int64) (*ReturnOrder, error) {
	returnOrderReturnIdKey := fmt.Sprintf("%s%v", cacheReturnOrderReturnIdPrefix, returnId)
	var resp ReturnOrder
	err := m.QueryRowCtx(ctx, &resp, returnOrderReturnIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `return_id` = ? limit 1", returnOrderRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, returnId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReturnOrderModel) FindOneByTenantIdReturnNo(ctx context.Context, tenantId int64, returnNo string) (*ReturnOrder, error) {
	returnOrderTenantIdReturnNoKey := fmt.Sprintf("%s%v:%v", cacheReturnOrderTenantIdReturnNoPrefix, tenantId, returnNo)
	var resp ReturnOrder
	err := m.QueryRowIndexCtx(ctx, &resp, returnOrderTenantIdReturnNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `return_no` = ? limit 1", returnOrderRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, returnNo); err != nil {
			return nil, err
		}
		return resp.ReturnId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReturnOrderModel) Insert(ctx context.Context, data *ReturnOrder) (sql.Result, error) {
	returnOrderReturnIdKey := fmt.Sprintf("%s%v", cacheReturnOrderReturnIdPrefix, data.ReturnId)
	returnOrderTenantIdReturnNoKey := fmt.Sprintf("%s%v:%v", cacheReturnOrderTenantIdReturnNoPrefix, data.TenantId, data.ReturnNo)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, returnOrderRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ReturnId, data.ReturnNo, data.OrderId, data.OrderNo, data.Reason, data.Status, data.RefundAmount, data.RefundNo, data.RejectReason, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt)
	}, returnOrderReturnIdKey, returnOrderTenantIdReturnNoKey)
	return ret, err
}

func (m *defaultReturnOrderModel) Update(ctx context.Context, newData *ReturnOrder) error {
	data, err := m.FindOne(ctx, newData.ReturnId)
	if err != nil {
		return err
	}

	returnOrderReturnIdKey := fmt.Sprintf("%s%v", cacheReturnOrderReturnIdPrefix, data.ReturnId)
	returnOrderTenantIdReturnNoKey := fmt.Sprintf("%s%v:%v", cacheReturnOrderTenantIdReturnNoPrefix, data.TenantId, data.ReturnNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `return_id` = ?", m.table, returnOrderRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ReturnNo, newData.OrderId, newData.OrderNo, newData.Reason, newData.Status, newData.RefundAmount, newData.RefundNo, newData.RejectReason, newData.TenantId, newData.CreatedBy, newData.UpdatedBy, newData.DeletedAt, newData.ReturnId)
	}, returnOrderReturnIdKey, returnOrderTenantIdReturnNoKey)
	return err
}

func (m *defaultReturnOrderModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheReturnOrderReturnIdPrefix, primary)
}

func (m *defaultReturnOrderModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `return_id` = ? limit 1", returnOrderRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultReturnOrderModel) tableName() string {
	return m.table
}
