// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sagaFieldNames          = builder.RawFieldNames(&Saga{})
	sagaRows                = strings.Join(sagaFieldNames, ",")
	sagaRowsExpectAutoSet   = strings.Join(stringx.Remove(sagaFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sagaRowsWithPlaceHolder = strings.Join(stringx.Remove(sagaFieldNames, "`saga_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSagaSagaIdPrefix          = "cache:saga:sagaId:"
	cacheSagaTenantIdOrderIdPrefix = "cache:saga:tenantId:orderId:"
)

type (
	sagaModel interface {
		Insert(ctx context.Context, data *Saga) (sql.Result, error)
		FindOne(ctx context.Context, sagaId int64) (*Saga, error)
		FindOneByTenantIdOrderId(ctx context.Context, tenantId int64, orderId int64) (*Saga, error)
		Update(ctx context.Context, data *Saga) error
		Delete(ctx context.Context, sagaId int64) error
	}

	defaultSagaModel struct {
		sqlc.CachedConn
		table string
	}

	Saga struct {
		SagaId      int64          `db:"saga_id"`       // 全局事务 ID（进日志与审计）
		OrderId     int64          `db:"order_id"`      // 关联订单
		OrderNo     string         `db:"order_no"`      // 关联订单号（事件 key/日志关联）
		OrderType   string         `db:"order_type"`    // 订单类型（决定是否含步骤6）
		CurrentStep int64          `db:"current_step"`  // 当前步骤 1~6（02 §9.1 补偿表）
		Status      string         `db:"status"`        // RUNNING/COMPENSATING/DONE/CANCELLED/MANUAL
		RetryCount  int64          `db:"retry_count"`   // 当前步骤已重试次数（退避 1m/5m/30m，超限→MANUAL）
		NextRetryAt sql.NullTime   `db:"next_retry_at"` // 下次推进时刻（重试扫描列）
		LastError   string         `db:"last_error"`    // 最近失败原因（人工队列排查入口）
		ContextJson sql.NullString `db:"context_json"`  // 补偿上下文（库存锁键/支付单号/合同号等原始业务标识）
		TenantId    int64          `db:"tenant_id"`     // 租户 ID
		CreatedAt   time.Time      `db:"created_at"`    // 创建时间
		CreatedBy   sql.NullInt64  `db:"created_by"`    // 创建人 uid
		UpdatedAt   time.Time      `db:"updated_at"`    // 更新时间
		UpdatedBy   sql.NullInt64  `db:"updated_by"`    // 更新人 uid
		DeletedAt   sql.NullTime   `db:"deleted_at"`    // 软删标记(NULL=有效)
	}
)

func newSagaModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSagaModel {
	return &defaultSagaModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`saga`",
	}
}

func (m *defaultSagaModel) Delete(ctx context.Context, sagaId int64) error {
	data, err := m.FindOne(ctx, sagaId)
	if err != nil {
		return err
	}

	sagaSagaIdKey := fmt.Sprintf("%s%v", cacheSagaSagaIdPrefix, sagaId)
	sagaTenantIdOrderIdKey := fmt.Sprintf("%s%v:%v", cacheSagaTenantIdOrderIdPrefix, data.TenantId, data.OrderId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `saga_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, sagaId)
	}, sagaSagaIdKey, sagaTenantIdOrderIdKey)
	return err
}

func (m *defaultSagaModel) FindOne(ctx context.Context, sagaId int64) (*Saga, error) {
	sagaSagaIdKey := fmt.Sprintf("%s%v", cacheSagaSagaIdPrefix, sagaId)
	var resp Saga
	err := m.QueryRowCtx(ctx, &resp, sagaSagaIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `saga_id` = ? limit 1", sagaRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, sagaId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSagaModel) FindOneByTenantIdOrderId(ctx context.Context, tenantId int64, orderId int64) (*Saga, error) {
	sagaTenantIdOrderIdKey := fmt.Sprintf("%s%v:%v", cacheSagaTenantIdOrderIdPrefix, tenantId, orderId)
	var resp Saga
	err := m.QueryRowIndexCtx(ctx, &resp, sagaTenantIdOrderIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `order_id` = ? limit 1", sagaRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, orderId); err != nil {
			return nil, err
		}
		return resp.SagaId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSagaModel) Insert(ctx context.Context, data *Saga) (sql.Result, error) {
	sagaSagaIdKey := fmt.Sprintf("%s%v", cacheSagaSagaIdPrefix, data.SagaId)
	sagaTenantIdOrderIdKey := fmt.Sprintf("%s%v:%v", cacheSagaTenantIdOrderIdPrefix, data.TenantId, data.OrderId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sagaRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SagaId, data.OrderId, data.OrderNo, data.OrderType, data.CurrentStep, data.Status, data.RetryCount, data.NextRetryAt, data.LastError, data.ContextJson, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt)
	}, sagaSagaIdKey, sagaTenantIdOrderIdKey)
	return ret, err
}

func (m *defaultSagaModel) Update(ctx context.Context, newData *Saga) error {
	data, err := m.FindOne(ctx, newData.SagaId)
	if err != nil {
		return err
	}

	sagaSagaIdKey := fmt.Sprintf("%s%v", cacheSagaSagaIdPrefix, data.SagaId)
	sagaTenantIdOrderIdKey := fmt.Sprintf("%s%v:%v", cacheSagaTenantIdOrderIdPrefix, data.TenantId, data.OrderId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `saga_id` = ?", m.table, sagaRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.OrderId, newData.OrderNo, newData.OrderType, newData.CurrentStep, newData.Status, newData.RetryCount, newData.NextRetryAt, newData.LastError, newData.ContextJson, newData.TenantId, newData.CreatedBy, newData.UpdatedBy, newData.DeletedAt, newData.SagaId)
	}, sagaSagaIdKey, sagaTenantIdOrderIdKey)
	return err
}

func (m *defaultSagaModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSagaSagaIdPrefix, primary)
}

func (m *defaultSagaModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `saga_id` = ? limit 1", sagaRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSagaModel) tableName() string {
	return m.table
}
