// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shipmentTraceFieldNames          = builder.RawFieldNames(&ShipmentTrace{})
	shipmentTraceRows                = strings.Join(shipmentTraceFieldNames, ",")
	shipmentTraceRowsExpectAutoSet   = strings.Join(stringx.Remove(shipmentTraceFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shipmentTraceRowsWithPlaceHolder = strings.Join(stringx.Remove(shipmentTraceFieldNames, "`trace_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheShipmentTraceTraceIdPrefix = "cache:shipmentTrace:traceId:"
)

type (
	shipmentTraceModel interface {
		Insert(ctx context.Context, data *ShipmentTrace) (sql.Result, error)
		FindOne(ctx context.Context, traceId int64) (*ShipmentTrace, error)
		Update(ctx context.Context, data *ShipmentTrace) error
		Delete(ctx context.Context, traceId int64) error
	}

	defaultShipmentTraceModel struct {
		sqlc.CachedConn
		table string
	}

	ShipmentTrace struct {
		TraceId     int64          `db:"trace_id"`    // 雪花 ID
		ShipmentId  int64          `db:"shipment_id"` // 发货单
		Node        string         `db:"node"`        // 轨迹节点
		Description sql.NullString `db:"description"` // 描述
		TraceTime   time.Time      `db:"trace_time"`  // 轨迹时刻
		TenantId    int64          `db:"tenant_id"`   // 租户 ID
		CreatedAt   time.Time      `db:"created_at"`  // 创建时间
		CreatedBy   sql.NullInt64  `db:"created_by"`  // 创建人 uid
		UpdatedAt   time.Time      `db:"updated_at"`  // 更新时间
		UpdatedBy   sql.NullInt64  `db:"updated_by"`  // 更新人 uid
		DeletedAt   sql.NullTime   `db:"deleted_at"`  // 软删标记(NULL=有效)
	}
)

func newShipmentTraceModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultShipmentTraceModel {
	return &defaultShipmentTraceModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`shipment_trace`",
	}
}

func (m *defaultShipmentTraceModel) Delete(ctx context.Context, traceId int64) error {
	shipmentTraceTraceIdKey := fmt.Sprintf("%s%v", cacheShipmentTraceTraceIdPrefix, traceId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `trace_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, traceId)
	}, shipmentTraceTraceIdKey)
	return err
}

func (m *defaultShipmentTraceModel) FindOne(ctx context.Context, traceId int64) (*ShipmentTrace, error) {
	shipmentTraceTraceIdKey := fmt.Sprintf("%s%v", cacheShipmentTraceTraceIdPrefix, traceId)
	var resp ShipmentTrace
	err := m.QueryRowCtx(ctx, &resp, shipmentTraceTraceIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `trace_id` = ? limit 1", shipmentTraceRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, traceId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShipmentTraceModel) Insert(ctx context.Context, data *ShipmentTrace) (sql.Result, error) {
	shipmentTraceTraceIdKey := fmt.Sprintf("%s%v", cacheShipmentTraceTraceIdPrefix, data.TraceId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, shipmentTraceRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TraceId, data.ShipmentId, data.Node, data.Description, data.TraceTime, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt)
	}, shipmentTraceTraceIdKey)
	return ret, err
}

func (m *defaultShipmentTraceModel) Update(ctx context.Context, data *ShipmentTrace) error {
	shipmentTraceTraceIdKey := fmt.Sprintf("%s%v", cacheShipmentTraceTraceIdPrefix, data.TraceId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `trace_id` = ?", m.table, shipmentTraceRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ShipmentId, data.Node, data.Description, data.TraceTime, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt, data.TraceId)
	}, shipmentTraceTraceIdKey)
	return err
}

func (m *defaultShipmentTraceModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheShipmentTraceTraceIdPrefix, primary)
}

func (m *defaultShipmentTraceModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `trace_id` = ? limit 1", shipmentTraceRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultShipmentTraceModel) tableName() string {
	return m.table
}
