// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	auth "micro-server/services/admin-bff/internal/handler/auth"
	menu "micro-server/services/admin-bff/internal/handler/menu"
	org "micro-server/services/admin-bff/internal/handler/org"
	role "micro-server/services/admin-bff/internal/handler/role"
	session "micro-server/services/admin-bff/internal/handler/session"
	tenant "micro-server/services/admin-bff/internal/handler/tenant"
	user "micro-server/services/admin-bff/internal/handler/user"
	"micro-server/services/admin-bff/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 密码登录（10400 凭证错误 / 10407 锁定倒计时）
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				// 登出
				Method:  http.MethodPost,
				Path:    "/auth/logout",
				Handler: auth.LogoutHandler(serverCtx),
			},
			{
				// 刷新（前端 request.ts 单飞调用；后端轮换式）
				Method:  http.MethodPost,
				Path:    "/auth/refresh",
				Handler: auth.RefreshHandler(serverCtx),
			},
			{
				// 二次认证提级（5min 窗口 level=2）
				Method:  http.MethodPost,
				Path:    "/auth/step-up",
				Handler: auth.StepUpHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authz},
			[]rest.Route{
				{
					// 当前用户信息
					Method:  http.MethodGet,
					Path:    "/auth/me",
					Handler: auth.MeHandler(serverCtx),
				},
				{
					// 用户可见菜单与权限码
					Method:  http.MethodGet,
					Path:    "/auth/menus",
					Handler: auth.MenusHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authz},
			[]rest.Route{
				{
					// 菜单管理列表（perm: system:menu:list）
					Method:  http.MethodGet,
					Path:    "/menus",
					Handler: menu.ListMenusHandler(serverCtx),
				},
				{
					// 新建菜单（perm: system:menu:create）
					Method:  http.MethodPost,
					Path:    "/menus",
					Handler: menu.CreateMenuHandler(serverCtx),
				},
				{
					// 编辑菜单（perm: system:menu:update）
					Method:  http.MethodPut,
					Path:    "/menus/:id",
					Handler: menu.UpdateMenuHandler(serverCtx),
				},
				{
					// 删除菜单（perm: system:menu:delete）
					Method:  http.MethodDelete,
					Path:    "/menus/:id",
					Handler: menu.DeleteMenuHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authz},
			[]rest.Route{
				{
					// 组织树（perm: system:org:list）
					Method:  http.MethodGet,
					Path:    "/orgs",
					Handler: org.ListOrgsHandler(serverCtx),
				},
				{
					// 新建组织（perm: system:org:create）
					Method:  http.MethodPost,
					Path:    "/orgs",
					Handler: org.CreateOrgHandler(serverCtx),
				},
				{
					// 编辑组织（perm: system:org:update）
					Method:  http.MethodPut,
					Path:    "/orgs/:id",
					Handler: org.UpdateOrgHandler(serverCtx),
				},
				{
					// 删除组织（perm: system:org:delete）
					Method:  http.MethodDelete,
					Path:    "/orgs/:id",
					Handler: org.DeleteOrgHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authz},
			[]rest.Route{
				{
					// 角色列表（perm: system:role:list）
					Method:  http.MethodGet,
					Path:    "/roles",
					Handler: role.ListRolesHandler(serverCtx),
				},
				{
					// 新建角色（perm: system:role:create）
					Method:  http.MethodPost,
					Path:    "/roles",
					Handler: role.CreateRoleHandler(serverCtx),
				},
				{
					// 角色详情+权限树回显（perm: system:role:list）
					Method:  http.MethodGet,
					Path:    "/roles/:id",
					Handler: role.GetRoleHandler(serverCtx),
				},
				{
					// 编辑角色（perm: system:role:update；联动失效相关用户 auth_cache）
					Method:  http.MethodPut,
					Path:    "/roles/:id",
					Handler: role.UpdateRoleHandler(serverCtx),
				},
				{
					// 删除角色（perm: system:role:delete）
					Method:  http.MethodDelete,
					Path:    "/roles/:id",
					Handler: role.DeleteRoleHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authz},
			[]rest.Route{
				{
					// 在线会话列表（perm: system:session:list；uid 空=自己）
					Method:  http.MethodGet,
					Path:    "/sessions",
					Handler: session.ListSessionsHandler(serverCtx),
				},
				{
					// 踢下线（perm: system:session:kick；sid 定点 / uid+client 该端 / uid 全端）
					Method:  http.MethodPost,
					Path:    "/sessions/kick",
					Handler: session.KickSessionsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authz},
			[]rest.Route{
				{
					// 租户列表（perm: system:tenant:list；平台面）
					Method:  http.MethodGet,
					Path:    "/tenants",
					Handler: tenant.ListTenantsHandler(serverCtx),
				},
				{
					// 新建租户（perm: system:tenant:create）
					Method:  http.MethodPost,
					Path:    "/tenants",
					Handler: tenant.CreateTenantHandler(serverCtx),
				},
				{
					// 编辑租户（perm: system:tenant:update）
					Method:  http.MethodPut,
					Path:    "/tenants/:id",
					Handler: tenant.UpdateTenantHandler(serverCtx),
				},
				{
					// 删除租户（perm: system:tenant:update）
					Method:  http.MethodDelete,
					Path:    "/tenants/:id",
					Handler: tenant.DeleteTenantHandler(serverCtx),
				},
				{
					// 配额设置（perm: system:tenant:quota）
					Method:  http.MethodPut,
					Path:    "/tenants/:id/quota",
					Handler: tenant.UpdateTenantQuotaHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authz},
			[]rest.Route{
				{
					// 用户列表（perm: system:user:list）
					Method:  http.MethodGet,
					Path:    "/users",
					Handler: user.ListUsersHandler(serverCtx),
				},
				{
					// 新建用户（perm: system:user:create）
					Method:  http.MethodPost,
					Path:    "/users",
					Handler: user.CreateUserHandler(serverCtx),
				},
				{
					// 用户详情（perm: system:user:list）
					Method:  http.MethodGet,
					Path:    "/users/:id",
					Handler: user.GetUserHandler(serverCtx),
				},
				{
					// 编辑用户（perm: system:user:update）
					Method:  http.MethodPut,
					Path:    "/users/:id",
					Handler: user.UpdateUserHandler(serverCtx),
				},
				{
					// 删除用户（perm: system:user:delete）
					Method:  http.MethodDelete,
					Path:    "/users/:id",
					Handler: user.DeleteUserHandler(serverCtx),
				},
				{
					// 重置密码（perm: system:user:reset-pwd）
					Method:  http.MethodPut,
					Path:    "/users/:id/password",
					Handler: user.ResetUserPasswordHandler(serverCtx),
				},
				{
					// 禁用/恢复（perm: system:user:status；禁用即时踢全部会话）
					Method:  http.MethodPut,
					Path:    "/users/:id/status",
					Handler: user.UpdateUserStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)
}
