// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tenantFieldNames          = builder.RawFieldNames(&Tenant{})
	tenantRows                = strings.Join(tenantFieldNames, ",")
	tenantRowsExpectAutoSet   = strings.Join(stringx.Remove(tenantFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tenantRowsWithPlaceHolder = strings.Join(stringx.Remove(tenantFieldNames, "`tenant_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTenantTenantIdPrefix   = "cache:tenant:tenantId:"
	cacheTenantTenantCodePrefix = "cache:tenant:tenantCode:"
)

type (
	tenantModel interface {
		Insert(ctx context.Context, data *Tenant) (sql.Result, error)
		FindOne(ctx context.Context, tenantId int64) (*Tenant, error)
		FindOneByTenantCode(ctx context.Context, tenantCode string) (*Tenant, error)
		Update(ctx context.Context, data *Tenant) error
		Delete(ctx context.Context, tenantId int64) error
	}

	defaultTenantModel struct {
		sqlc.CachedConn
		table string
	}

	Tenant struct {
		TenantId   int64          `db:"tenant_id"`   // 雪花 ID
		TenantCode string         `db:"tenant_code"` // 租户编码（登录上下文/配置键引用）
		Name       string         `db:"name"`        // 租户名称
		Plan       string         `db:"plan"`        // 套餐：STANDARD/PRO/ENTERPRISE
		Quota      sql.NullString `db:"quota"`       // 配额 JSON：{"rpm":600,"user_max":100,...}（tenantx 配额源）
		Status     int64          `db:"status"`      // 1 正常 / 2 停用
		CreatedAt  time.Time      `db:"created_at"`  // 创建时间
		CreatedBy  sql.NullInt64  `db:"created_by"`  // 创建人 uid
		UpdatedAt  time.Time      `db:"updated_at"`  // 更新时间
		UpdatedBy  sql.NullInt64  `db:"updated_by"`  // 更新人 uid
		DeletedAt  sql.NullTime   `db:"deleted_at"`  // 软删标记（NULL=有效）
	}
)

func newTenantModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTenantModel {
	return &defaultTenantModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tenant`",
	}
}

func (m *defaultTenantModel) Delete(ctx context.Context, tenantId int64) error {
	data, err := m.FindOne(ctx, tenantId)
	if err != nil {
		return err
	}

	tenantTenantCodeKey := fmt.Sprintf("%s%v", cacheTenantTenantCodePrefix, data.TenantCode)
	tenantTenantIdKey := fmt.Sprintf("%s%v", cacheTenantTenantIdPrefix, tenantId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `tenant_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, tenantId)
	}, tenantTenantCodeKey, tenantTenantIdKey)
	return err
}

func (m *defaultTenantModel) FindOne(ctx context.Context, tenantId int64) (*Tenant, error) {
	tenantTenantIdKey := fmt.Sprintf("%s%v", cacheTenantTenantIdPrefix, tenantId)
	var resp Tenant
	err := m.QueryRowCtx(ctx, &resp, tenantTenantIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? limit 1", tenantRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, tenantId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTenantModel) FindOneByTenantCode(ctx context.Context, tenantCode string) (*Tenant, error) {
	tenantTenantCodeKey := fmt.Sprintf("%s%v", cacheTenantTenantCodePrefix, tenantCode)
	var resp Tenant
	err := m.QueryRowIndexCtx(ctx, &resp, tenantTenantCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_code` = ? limit 1", tenantRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantCode); err != nil {
			return nil, err
		}
		return resp.TenantId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTenantModel) Insert(ctx context.Context, data *Tenant) (sql.Result, error) {
	tenantTenantCodeKey := fmt.Sprintf("%s%v", cacheTenantTenantCodePrefix, data.TenantCode)
	tenantTenantIdKey := fmt.Sprintf("%s%v", cacheTenantTenantIdPrefix, data.TenantId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tenantRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.TenantCode, data.Name, data.Plan, data.Quota, data.Status, data.CreatedBy, data.UpdatedBy, data.DeletedAt)
	}, tenantTenantCodeKey, tenantTenantIdKey)
	return ret, err
}

func (m *defaultTenantModel) Update(ctx context.Context, newData *Tenant) error {
	data, err := m.FindOne(ctx, newData.TenantId)
	if err != nil {
		return err
	}

	tenantTenantCodeKey := fmt.Sprintf("%s%v", cacheTenantTenantCodePrefix, data.TenantCode)
	tenantTenantIdKey := fmt.Sprintf("%s%v", cacheTenantTenantIdPrefix, data.TenantId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `tenant_id` = ?", m.table, tenantRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantCode, newData.Name, newData.Plan, newData.Quota, newData.Status, newData.CreatedBy, newData.UpdatedBy, newData.DeletedAt, newData.TenantId)
	}, tenantTenantCodeKey, tenantTenantIdKey)
	return err
}

func (m *defaultTenantModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTenantTenantIdPrefix, primary)
}

func (m *defaultTenantModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `tenant_id` = ? limit 1", tenantRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTenantModel) tableName() string {
	return m.table
}
