// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userSsoBindingFieldNames          = builder.RawFieldNames(&UserSsoBinding{})
	userSsoBindingRows                = strings.Join(userSsoBindingFieldNames, ",")
	userSsoBindingRowsExpectAutoSet   = strings.Join(stringx.Remove(userSsoBindingFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userSsoBindingRowsWithPlaceHolder = strings.Join(stringx.Remove(userSsoBindingFieldNames, "`binding_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserSsoBindingBindingIdPrefix      = "cache:userSsoBinding:bindingId:"
	cacheUserSsoBindingProviderOpenidPrefix = "cache:userSsoBinding:provider:openid:"
)

type (
	userSsoBindingModel interface {
		Insert(ctx context.Context, data *UserSsoBinding) (sql.Result, error)
		FindOne(ctx context.Context, bindingId int64) (*UserSsoBinding, error)
		FindOneByProviderOpenid(ctx context.Context, provider string, openid string) (*UserSsoBinding, error)
		Update(ctx context.Context, data *UserSsoBinding) error
		Delete(ctx context.Context, bindingId int64) error
	}

	defaultUserSsoBindingModel struct {
		sqlc.CachedConn
		table string
	}

	UserSsoBinding struct {
		BindingId int64          `db:"binding_id"` // 雪花 ID
		UserId    int64          `db:"user_id"`    // 用户 ID
		Provider  string         `db:"provider"`   // SSO 提供方：WECHAT_MA / WECHAT_MP / DINGTALK ...
		Openid    string         `db:"openid"`     // 提供方侧 openid
		Unionid   sql.NullString `db:"unionid"`    // 提供方侧 unionid（可空）
		TenantId  int64          `db:"tenant_id"`  // 租户 ID
		CreatedAt time.Time      `db:"created_at"` // 创建时间
		CreatedBy sql.NullInt64  `db:"created_by"` // 创建人 uid
		UpdatedAt time.Time      `db:"updated_at"` // 更新时间
		UpdatedBy sql.NullInt64  `db:"updated_by"` // 更新人 uid
		DeletedAt sql.NullTime   `db:"deleted_at"` // 软删标记
	}
)

func newUserSsoBindingModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserSsoBindingModel {
	return &defaultUserSsoBindingModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_sso_binding`",
	}
}

func (m *defaultUserSsoBindingModel) Delete(ctx context.Context, bindingId int64) error {
	data, err := m.FindOne(ctx, bindingId)
	if err != nil {
		return err
	}

	userSsoBindingBindingIdKey := fmt.Sprintf("%s%v", cacheUserSsoBindingBindingIdPrefix, bindingId)
	userSsoBindingProviderOpenidKey := fmt.Sprintf("%s%v:%v", cacheUserSsoBindingProviderOpenidPrefix, data.Provider, data.Openid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `binding_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, bindingId)
	}, userSsoBindingBindingIdKey, userSsoBindingProviderOpenidKey)
	return err
}

func (m *defaultUserSsoBindingModel) FindOne(ctx context.Context, bindingId int64) (*UserSsoBinding, error) {
	userSsoBindingBindingIdKey := fmt.Sprintf("%s%v", cacheUserSsoBindingBindingIdPrefix, bindingId)
	var resp UserSsoBinding
	err := m.QueryRowCtx(ctx, &resp, userSsoBindingBindingIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `binding_id` = ? limit 1", userSsoBindingRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, bindingId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserSsoBindingModel) FindOneByProviderOpenid(ctx context.Context, provider string, openid string) (*UserSsoBinding, error) {
	userSsoBindingProviderOpenidKey := fmt.Sprintf("%s%v:%v", cacheUserSsoBindingProviderOpenidPrefix, provider, openid)
	var resp UserSsoBinding
	err := m.QueryRowIndexCtx(ctx, &resp, userSsoBindingProviderOpenidKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `provider` = ? and `openid` = ? limit 1", userSsoBindingRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, provider, openid); err != nil {
			return nil, err
		}
		return resp.BindingId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserSsoBindingModel) Insert(ctx context.Context, data *UserSsoBinding) (sql.Result, error) {
	userSsoBindingBindingIdKey := fmt.Sprintf("%s%v", cacheUserSsoBindingBindingIdPrefix, data.BindingId)
	userSsoBindingProviderOpenidKey := fmt.Sprintf("%s%v:%v", cacheUserSsoBindingProviderOpenidPrefix, data.Provider, data.Openid)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userSsoBindingRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.BindingId, data.UserId, data.Provider, data.Openid, data.Unionid, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt)
	}, userSsoBindingBindingIdKey, userSsoBindingProviderOpenidKey)
	return ret, err
}

func (m *defaultUserSsoBindingModel) Update(ctx context.Context, newData *UserSsoBinding) error {
	data, err := m.FindOne(ctx, newData.BindingId)
	if err != nil {
		return err
	}

	userSsoBindingBindingIdKey := fmt.Sprintf("%s%v", cacheUserSsoBindingBindingIdPrefix, data.BindingId)
	userSsoBindingProviderOpenidKey := fmt.Sprintf("%s%v:%v", cacheUserSsoBindingProviderOpenidPrefix, data.Provider, data.Openid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `binding_id` = ?", m.table, userSsoBindingRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.Provider, newData.Openid, newData.Unionid, newData.TenantId, newData.CreatedBy, newData.UpdatedBy, newData.DeletedAt, newData.BindingId)
	}, userSsoBindingBindingIdKey, userSsoBindingProviderOpenidKey)
	return err
}

func (m *defaultUserSsoBindingModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserSsoBindingBindingIdPrefix, primary)
}

func (m *defaultUserSsoBindingModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `binding_id` = ? limit 1", userSsoBindingRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserSsoBindingModel) tableName() string {
	return m.table
}
