// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	inventoryFieldNames          = builder.RawFieldNames(&Inventory{})
	inventoryRows                = strings.Join(inventoryFieldNames, ",")
	inventoryRowsExpectAutoSet   = strings.Join(stringx.Remove(inventoryFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	inventoryRowsWithPlaceHolder = strings.Join(stringx.Remove(inventoryFieldNames, "`inventory_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheInventoryInventoryIdPrefix      = "cache:inventory:inventoryId:"
	cacheInventoryWarehouseIdSkuIdPrefix = "cache:inventory:warehouseId:skuId:"
)

type (
	inventoryModel interface {
		Insert(ctx context.Context, data *Inventory) (sql.Result, error)
		FindOne(ctx context.Context, inventoryId int64) (*Inventory, error)
		FindOneByWarehouseIdSkuId(ctx context.Context, warehouseId int64, skuId int64) (*Inventory, error)
		Update(ctx context.Context, data *Inventory) error
		Delete(ctx context.Context, inventoryId int64) error
	}

	defaultInventoryModel struct {
		sqlc.CachedConn
		table string
	}

	Inventory struct {
		InventoryId       int64         `db:"inventory_id"`        // 雪花 ID
		WarehouseId       int64         `db:"warehouse_id"`        // 仓库 ID
		SkuId             int64         `db:"sku_id"`              // SKU(逻辑引用 catalog.sku)
		Available         int64         `db:"available"`           // 可用库存
		Locked            int64         `db:"locked"`              // 锁定库存(已预留未出库)
		InTransit         int64         `db:"in_transit"`          // 在途库存(调拨/采购在途)
		Defective         int64         `db:"defective"`           // 残次库存
		LowStockThreshold int64         `db:"low_stock_threshold"` // 低库存预警阈值
		TenantId          int64         `db:"tenant_id"`           // 租户 ID
		CreatedAt         time.Time     `db:"created_at"`          // 创建时间
		CreatedBy         sql.NullInt64 `db:"created_by"`          // 创建人 uid
		UpdatedAt         time.Time     `db:"updated_at"`          // 更新时间
		UpdatedBy         sql.NullInt64 `db:"updated_by"`          // 更新人 uid
		DeletedAt         sql.NullTime  `db:"deleted_at"`          // 软删标记(NULL=有效)
	}
)

func newInventoryModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultInventoryModel {
	return &defaultInventoryModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`inventory`",
	}
}

func (m *defaultInventoryModel) Delete(ctx context.Context, inventoryId int64) error {
	data, err := m.FindOne(ctx, inventoryId)
	if err != nil {
		return err
	}

	inventoryInventoryIdKey := fmt.Sprintf("%s%v", cacheInventoryInventoryIdPrefix, inventoryId)
	inventoryWarehouseIdSkuIdKey := fmt.Sprintf("%s%v:%v", cacheInventoryWarehouseIdSkuIdPrefix, data.WarehouseId, data.SkuId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `inventory_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, inventoryId)
	}, inventoryInventoryIdKey, inventoryWarehouseIdSkuIdKey)
	return err
}

func (m *defaultInventoryModel) FindOne(ctx context.Context, inventoryId int64) (*Inventory, error) {
	inventoryInventoryIdKey := fmt.Sprintf("%s%v", cacheInventoryInventoryIdPrefix, inventoryId)
	var resp Inventory
	err := m.QueryRowCtx(ctx, &resp, inventoryInventoryIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `inventory_id` = ? limit 1", inventoryRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, inventoryId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInventoryModel) FindOneByWarehouseIdSkuId(ctx context.Context, warehouseId int64, skuId int64) (*Inventory, error) {
	inventoryWarehouseIdSkuIdKey := fmt.Sprintf("%s%v:%v", cacheInventoryWarehouseIdSkuIdPrefix, warehouseId, skuId)
	var resp Inventory
	err := m.QueryRowIndexCtx(ctx, &resp, inventoryWarehouseIdSkuIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `warehouse_id` = ? and `sku_id` = ? limit 1", inventoryRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, warehouseId, skuId); err != nil {
			return nil, err
		}
		return resp.InventoryId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInventoryModel) Insert(ctx context.Context, data *Inventory) (sql.Result, error) {
	inventoryInventoryIdKey := fmt.Sprintf("%s%v", cacheInventoryInventoryIdPrefix, data.InventoryId)
	inventoryWarehouseIdSkuIdKey := fmt.Sprintf("%s%v:%v", cacheInventoryWarehouseIdSkuIdPrefix, data.WarehouseId, data.SkuId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, inventoryRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.InventoryId, data.WarehouseId, data.SkuId, data.Available, data.Locked, data.InTransit, data.Defective, data.LowStockThreshold, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt)
	}, inventoryInventoryIdKey, inventoryWarehouseIdSkuIdKey)
	return ret, err
}

func (m *defaultInventoryModel) Update(ctx context.Context, newData *Inventory) error {
	data, err := m.FindOne(ctx, newData.InventoryId)
	if err != nil {
		return err
	}

	inventoryInventoryIdKey := fmt.Sprintf("%s%v", cacheInventoryInventoryIdPrefix, data.InventoryId)
	inventoryWarehouseIdSkuIdKey := fmt.Sprintf("%s%v:%v", cacheInventoryWarehouseIdSkuIdPrefix, data.WarehouseId, data.SkuId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `inventory_id` = ?", m.table, inventoryRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.WarehouseId, newData.SkuId, newData.Available, newData.Locked, newData.InTransit, newData.Defective, newData.LowStockThreshold, newData.TenantId, newData.CreatedBy, newData.UpdatedBy, newData.DeletedAt, newData.InventoryId)
	}, inventoryInventoryIdKey, inventoryWarehouseIdSkuIdKey)
	return err
}

func (m *defaultInventoryModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheInventoryInventoryIdPrefix, primary)
}

func (m *defaultInventoryModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `inventory_id` = ? limit 1", inventoryRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultInventoryModel) tableName() string {
	return m.table
}
