// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	warehouseFieldNames          = builder.RawFieldNames(&Warehouse{})
	warehouseRows                = strings.Join(warehouseFieldNames, ",")
	warehouseRowsExpectAutoSet   = strings.Join(stringx.Remove(warehouseFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	warehouseRowsWithPlaceHolder = strings.Join(stringx.Remove(warehouseFieldNames, "`warehouse_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheWarehouseWarehouseIdPrefix  = "cache:warehouse:warehouseId:"
	cacheWarehouseTenantIdCodePrefix = "cache:warehouse:tenantId:code:"
)

type (
	warehouseModel interface {
		Insert(ctx context.Context, data *Warehouse) (sql.Result, error)
		FindOne(ctx context.Context, warehouseId int64) (*Warehouse, error)
		FindOneByTenantIdCode(ctx context.Context, tenantId int64, code string) (*Warehouse, error)
		Update(ctx context.Context, data *Warehouse) error
		Delete(ctx context.Context, warehouseId int64) error
	}

	defaultWarehouseModel struct {
		sqlc.CachedConn
		table string
	}

	Warehouse struct {
		WarehouseId int64          `db:"warehouse_id"` // 雪花 ID
		Code        string         `db:"code"`         // 仓库编码(租户内唯一)
		Name        string         `db:"name"`         // 仓库名称
		Address     sql.NullString `db:"address"`      // 仓库地址
		Status      int64          `db:"status"`       // 1 启用/2 停用
		TenantId    int64          `db:"tenant_id"`    // 租户 ID
		CreatedAt   time.Time      `db:"created_at"`   // 创建时间
		CreatedBy   sql.NullInt64  `db:"created_by"`   // 创建人 uid
		UpdatedAt   time.Time      `db:"updated_at"`   // 更新时间
		UpdatedBy   sql.NullInt64  `db:"updated_by"`   // 更新人 uid
		DeletedAt   sql.NullTime   `db:"deleted_at"`   // 软删标记(NULL=有效)
	}
)

func newWarehouseModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultWarehouseModel {
	return &defaultWarehouseModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`warehouse`",
	}
}

func (m *defaultWarehouseModel) Delete(ctx context.Context, warehouseId int64) error {
	data, err := m.FindOne(ctx, warehouseId)
	if err != nil {
		return err
	}

	warehouseTenantIdCodeKey := fmt.Sprintf("%s%v:%v", cacheWarehouseTenantIdCodePrefix, data.TenantId, data.Code)
	warehouseWarehouseIdKey := fmt.Sprintf("%s%v", cacheWarehouseWarehouseIdPrefix, warehouseId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `warehouse_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, warehouseId)
	}, warehouseTenantIdCodeKey, warehouseWarehouseIdKey)
	return err
}

func (m *defaultWarehouseModel) FindOne(ctx context.Context, warehouseId int64) (*Warehouse, error) {
	warehouseWarehouseIdKey := fmt.Sprintf("%s%v", cacheWarehouseWarehouseIdPrefix, warehouseId)
	var resp Warehouse
	err := m.QueryRowCtx(ctx, &resp, warehouseWarehouseIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `warehouse_id` = ? limit 1", warehouseRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, warehouseId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWarehouseModel) FindOneByTenantIdCode(ctx context.Context, tenantId int64, code string) (*Warehouse, error) {
	warehouseTenantIdCodeKey := fmt.Sprintf("%s%v:%v", cacheWarehouseTenantIdCodePrefix, tenantId, code)
	var resp Warehouse
	err := m.QueryRowIndexCtx(ctx, &resp, warehouseTenantIdCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `code` = ? limit 1", warehouseRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, code); err != nil {
			return nil, err
		}
		return resp.WarehouseId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWarehouseModel) Insert(ctx context.Context, data *Warehouse) (sql.Result, error) {
	warehouseTenantIdCodeKey := fmt.Sprintf("%s%v:%v", cacheWarehouseTenantIdCodePrefix, data.TenantId, data.Code)
	warehouseWarehouseIdKey := fmt.Sprintf("%s%v", cacheWarehouseWarehouseIdPrefix, data.WarehouseId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, warehouseRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.WarehouseId, data.Code, data.Name, data.Address, data.Status, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt)
	}, warehouseTenantIdCodeKey, warehouseWarehouseIdKey)
	return ret, err
}

func (m *defaultWarehouseModel) Update(ctx context.Context, newData *Warehouse) error {
	data, err := m.FindOne(ctx, newData.WarehouseId)
	if err != nil {
		return err
	}

	warehouseTenantIdCodeKey := fmt.Sprintf("%s%v:%v", cacheWarehouseTenantIdCodePrefix, data.TenantId, data.Code)
	warehouseWarehouseIdKey := fmt.Sprintf("%s%v", cacheWarehouseWarehouseIdPrefix, data.WarehouseId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `warehouse_id` = ?", m.table, warehouseRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Code, newData.Name, newData.Address, newData.Status, newData.TenantId, newData.CreatedBy, newData.UpdatedBy, newData.DeletedAt, newData.WarehouseId)
	}, warehouseTenantIdCodeKey, warehouseWarehouseIdKey)
	return err
}

func (m *defaultWarehouseModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheWarehouseWarehouseIdPrefix, primary)
}

func (m *defaultWarehouseModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `warehouse_id` = ? limit 1", warehouseRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultWarehouseModel) tableName() string {
	return m.table
}
