// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: finance.proto

package finance

import (
	"context"

	"micro-server/services/finance/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AlipayCallbackReq        = pb.AlipayCallbackReq
	AlipayCallbackResp       = pb.AlipayCallbackResp
	AlipayPayURLReq          = pb.AlipayPayURLReq
	AlipayPayURLResp         = pb.AlipayPayURLResp
	ApprovePaymentReq        = pb.ApprovePaymentReq
	ApprovePaymentResp       = pb.ApprovePaymentResp
	ConfirmPaymentReq        = pb.ConfirmPaymentReq
	ConfirmPaymentResp       = pb.ConfirmPaymentResp
	CreatePaymentReq         = pb.CreatePaymentReq
	CreatePaymentResp        = pb.CreatePaymentResp
	CreateReconcileTaskReq   = pb.CreateReconcileTaskReq
	CreateReconcileTaskResp  = pb.CreateReconcileTaskResp
	CreateRefundReq          = pb.CreateRefundReq
	CreateRefundResp         = pb.CreateRefundResp
	GetPaymentReq            = pb.GetPaymentReq
	GetPaymentResp           = pb.GetPaymentResp
	InvoiceDetail            = pb.InvoiceDetail
	IssueInvoiceReq          = pb.IssueInvoiceReq
	IssueInvoiceResp         = pb.IssueInvoiceResp
	ListInvoiceReq           = pb.ListInvoiceReq
	ListInvoiceResp          = pb.ListInvoiceResp
	ListPaymentReq           = pb.ListPaymentReq
	ListPaymentResp          = pb.ListPaymentResp
	ListReconcileTaskReq     = pb.ListReconcileTaskReq
	ListReconcileTaskResp    = pb.ListReconcileTaskResp
	ListRefundReq            = pb.ListRefundReq
	ListRefundResp           = pb.ListRefundResp
	PaymentDetail            = pb.PaymentDetail
	PingReq                  = pb.PingReq
	PingResp                 = pb.PingResp
	ReconcileTaskDetail      = pb.ReconcileTaskDetail
	RefundDetail             = pb.RefundDetail
	ResolveReconcileTaskReq  = pb.ResolveReconcileTaskReq
	ResolveReconcileTaskResp = pb.ResolveReconcileTaskResp
	ReverseInvoiceReq        = pb.ReverseInvoiceReq
	ReverseInvoiceResp       = pb.ReverseInvoiceResp
	SettlePaymentReq         = pb.SettlePaymentReq
	SettlePaymentResp        = pb.SettlePaymentResp
	WechatCallbackReq        = pb.WechatCallbackReq
	WechatCallbackResp       = pb.WechatCallbackResp
	WechatPayURLReq          = pb.WechatPayURLReq
	WechatPayURLResp         = pb.WechatPayURLResp

	Finance interface {
		Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
		// ---- 支付单 ----
		CreatePayment(ctx context.Context, in *CreatePaymentReq, opts ...grpc.CallOption) (*CreatePaymentResp, error)
		ConfirmPayment(ctx context.Context, in *ConfirmPaymentReq, opts ...grpc.CallOption) (*ConfirmPaymentResp, error)
		ApprovePayment(ctx context.Context, in *ApprovePaymentReq, opts ...grpc.CallOption) (*ApprovePaymentResp, error)
		SettlePayment(ctx context.Context, in *SettlePaymentReq, opts ...grpc.CallOption) (*SettlePaymentResp, error)
		GetPayment(ctx context.Context, in *GetPaymentReq, opts ...grpc.CallOption) (*GetPaymentResp, error)
		ListPayment(ctx context.Context, in *ListPaymentReq, opts ...grpc.CallOption) (*ListPaymentResp, error)
		// ---- 渠道 ----
		WechatPayURL(ctx context.Context, in *WechatPayURLReq, opts ...grpc.CallOption) (*WechatPayURLResp, error)
		WechatCallback(ctx context.Context, in *WechatCallbackReq, opts ...grpc.CallOption) (*WechatCallbackResp, error)
		AlipayPayURL(ctx context.Context, in *AlipayPayURLReq, opts ...grpc.CallOption) (*AlipayPayURLResp, error)
		AlipayCallback(ctx context.Context, in *AlipayCallbackReq, opts ...grpc.CallOption) (*AlipayCallbackResp, error)
		// ---- 退款 ----
		CreateRefund(ctx context.Context, in *CreateRefundReq, opts ...grpc.CallOption) (*CreateRefundResp, error)
		ListRefund(ctx context.Context, in *ListRefundReq, opts ...grpc.CallOption) (*ListRefundResp, error)
		// ---- 发票（ISSUED/REVERSED 状态机桩，FR-FIN-004）----
		IssueInvoice(ctx context.Context, in *IssueInvoiceReq, opts ...grpc.CallOption) (*IssueInvoiceResp, error)
		ReverseInvoice(ctx context.Context, in *ReverseInvoiceReq, opts ...grpc.CallOption) (*ReverseInvoiceResp, error)
		ListInvoice(ctx context.Context, in *ListInvoiceReq, opts ...grpc.CallOption) (*ListInvoiceResp, error)
		// ---- 对账任务（FR-FIN-003，差异修复只允许补投递重放，E10）----
		CreateReconcileTask(ctx context.Context, in *CreateReconcileTaskReq, opts ...grpc.CallOption) (*CreateReconcileTaskResp, error)
		ResolveReconcileTask(ctx context.Context, in *ResolveReconcileTaskReq, opts ...grpc.CallOption) (*ResolveReconcileTaskResp, error)
		ListReconcileTask(ctx context.Context, in *ListReconcileTaskReq, opts ...grpc.CallOption) (*ListReconcileTaskResp, error)
	}

	defaultFinance struct {
		cli zrpc.Client
	}
)

func NewFinance(cli zrpc.Client) Finance {
	return &defaultFinance{
		cli: cli,
	}
}

func (m *defaultFinance) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	client := pb.NewFinanceClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

// ---- 支付单 ----
func (m *defaultFinance) CreatePayment(ctx context.Context, in *CreatePaymentReq, opts ...grpc.CallOption) (*CreatePaymentResp, error) {
	client := pb.NewFinanceClient(m.cli.Conn())
	return client.CreatePayment(ctx, in, opts...)
}

func (m *defaultFinance) ConfirmPayment(ctx context.Context, in *ConfirmPaymentReq, opts ...grpc.CallOption) (*ConfirmPaymentResp, error) {
	client := pb.NewFinanceClient(m.cli.Conn())
	return client.ConfirmPayment(ctx, in, opts...)
}

func (m *defaultFinance) ApprovePayment(ctx context.Context, in *ApprovePaymentReq, opts ...grpc.CallOption) (*ApprovePaymentResp, error) {
	client := pb.NewFinanceClient(m.cli.Conn())
	return client.ApprovePayment(ctx, in, opts...)
}

func (m *defaultFinance) SettlePayment(ctx context.Context, in *SettlePaymentReq, opts ...grpc.CallOption) (*SettlePaymentResp, error) {
	client := pb.NewFinanceClient(m.cli.Conn())
	return client.SettlePayment(ctx, in, opts...)
}

func (m *defaultFinance) GetPayment(ctx context.Context, in *GetPaymentReq, opts ...grpc.CallOption) (*GetPaymentResp, error) {
	client := pb.NewFinanceClient(m.cli.Conn())
	return client.GetPayment(ctx, in, opts...)
}

func (m *defaultFinance) ListPayment(ctx context.Context, in *ListPaymentReq, opts ...grpc.CallOption) (*ListPaymentResp, error) {
	client := pb.NewFinanceClient(m.cli.Conn())
	return client.ListPayment(ctx, in, opts...)
}

// ---- 渠道 ----
func (m *defaultFinance) WechatPayURL(ctx context.Context, in *WechatPayURLReq, opts ...grpc.CallOption) (*WechatPayURLResp, error) {
	client := pb.NewFinanceClient(m.cli.Conn())
	return client.WechatPayURL(ctx, in, opts...)
}

func (m *defaultFinance) WechatCallback(ctx context.Context, in *WechatCallbackReq, opts ...grpc.CallOption) (*WechatCallbackResp, error) {
	client := pb.NewFinanceClient(m.cli.Conn())
	return client.WechatCallback(ctx, in, opts...)
}

func (m *defaultFinance) AlipayPayURL(ctx context.Context, in *AlipayPayURLReq, opts ...grpc.CallOption) (*AlipayPayURLResp, error) {
	client := pb.NewFinanceClient(m.cli.Conn())
	return client.AlipayPayURL(ctx, in, opts...)
}

func (m *defaultFinance) AlipayCallback(ctx context.Context, in *AlipayCallbackReq, opts ...grpc.CallOption) (*AlipayCallbackResp, error) {
	client := pb.NewFinanceClient(m.cli.Conn())
	return client.AlipayCallback(ctx, in, opts...)
}

// ---- 退款 ----
func (m *defaultFinance) CreateRefund(ctx context.Context, in *CreateRefundReq, opts ...grpc.CallOption) (*CreateRefundResp, error) {
	client := pb.NewFinanceClient(m.cli.Conn())
	return client.CreateRefund(ctx, in, opts...)
}

func (m *defaultFinance) ListRefund(ctx context.Context, in *ListRefundReq, opts ...grpc.CallOption) (*ListRefundResp, error) {
	client := pb.NewFinanceClient(m.cli.Conn())
	return client.ListRefund(ctx, in, opts...)
}

// ---- 发票（ISSUED/REVERSED 状态机桩，FR-FIN-004）----
func (m *defaultFinance) IssueInvoice(ctx context.Context, in *IssueInvoiceReq, opts ...grpc.CallOption) (*IssueInvoiceResp, error) {
	client := pb.NewFinanceClient(m.cli.Conn())
	return client.IssueInvoice(ctx, in, opts...)
}

func (m *defaultFinance) ReverseInvoice(ctx context.Context, in *ReverseInvoiceReq, opts ...grpc.CallOption) (*ReverseInvoiceResp, error) {
	client := pb.NewFinanceClient(m.cli.Conn())
	return client.ReverseInvoice(ctx, in, opts...)
}

func (m *defaultFinance) ListInvoice(ctx context.Context, in *ListInvoiceReq, opts ...grpc.CallOption) (*ListInvoiceResp, error) {
	client := pb.NewFinanceClient(m.cli.Conn())
	return client.ListInvoice(ctx, in, opts...)
}

// ---- 对账任务（FR-FIN-003，差异修复只允许补投递重放，E10）----
func (m *defaultFinance) CreateReconcileTask(ctx context.Context, in *CreateReconcileTaskReq, opts ...grpc.CallOption) (*CreateReconcileTaskResp, error) {
	client := pb.NewFinanceClient(m.cli.Conn())
	return client.CreateReconcileTask(ctx, in, opts...)
}

func (m *defaultFinance) ResolveReconcileTask(ctx context.Context, in *ResolveReconcileTaskReq, opts ...grpc.CallOption) (*ResolveReconcileTaskResp, error) {
	client := pb.NewFinanceClient(m.cli.Conn())
	return client.ResolveReconcileTask(ctx, in, opts...)
}

func (m *defaultFinance) ListReconcileTask(ctx context.Context, in *ListReconcileTaskReq, opts ...grpc.CallOption) (*ListReconcileTaskResp, error) {
	client := pb.NewFinanceClient(m.cli.Conn())
	return client.ListReconcileTask(ctx, in, opts...)
}
