// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.4
// source: services/finance/pb/finance.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{0}
}

type PingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResp) Reset() {
	*x = PingResp{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResp) ProtoMessage() {}

func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{1}
}

func (x *PingResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type CreatePaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`   // DECIMAL 字符串（order 快照总额）
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"` // WECHAT/ALIPAY/BANK_OFFLINE
	PayerPartyId  int64                  `protobuf:"varint,4,opt,name=payer_party_id,json=payerPartyId,proto3" json:"payer_party_id,omitempty"`
	Remark        string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentReq) Reset() {
	*x = CreatePaymentReq{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentReq) ProtoMessage() {}

func (x *CreatePaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentReq.ProtoReflect.Descriptor instead.
func (*CreatePaymentReq) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePaymentReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreatePaymentReq) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreatePaymentReq) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *CreatePaymentReq) GetPayerPartyId() int64 {
	if x != nil {
		return x.PayerPartyId
	}
	return 0
}

func (x *CreatePaymentReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type CreatePaymentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                        // PAYING（线上）/REVIEWING（对公录入）
	PayParams     string                 `protobuf:"bytes,3,opt,name=pay_params,json=payParams,proto3" json:"pay_params,omitempty"` // 渠道透传 JSON（dev mock = {"mock_url":...}）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResp) Reset() {
	*x = CreatePaymentResp{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResp) ProtoMessage() {}

func (x *CreatePaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResp.ProtoReflect.Descriptor instead.
func (*CreatePaymentResp) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePaymentResp) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *CreatePaymentResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePaymentResp) GetPayParams() string {
	if x != nil {
		return x.PayParams
	}
	return ""
}

type ConfirmPaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	ChannelTxnId  string                 `protobuf:"bytes,2,opt,name=channel_txn_id,json=channelTxnId,proto3" json:"channel_txn_id,omitempty"` // 渠道流水号（UK，回调验签后必传）
	PaidAmount    string                 `protobuf:"bytes,3,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`         // 实收金额（金额不一致 → 差异对账任务）
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`                                   // WECHAT_CALLBACK/ALIPAY_CALLBACK/MOCK（dev 模拟网关）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentReq) Reset() {
	*x = ConfirmPaymentReq{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentReq) ProtoMessage() {}

func (x *ConfirmPaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentReq.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentReq) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmPaymentReq) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *ConfirmPaymentReq) GetChannelTxnId() string {
	if x != nil {
		return x.ChannelTxnId
	}
	return ""
}

func (x *ConfirmPaymentReq) GetPaidAmount() string {
	if x != nil {
		return x.PaidAmount
	}
	return ""
}

func (x *ConfirmPaymentReq) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ConfirmPaymentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // PAID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentResp) Reset() {
	*x = ConfirmPaymentResp{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentResp) ProtoMessage() {}

func (x *ConfirmPaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentResp.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentResp) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmPaymentResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ApprovePaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	Approve       bool                   `protobuf:"varint,2,opt,name=approve,proto3" json:"approve,omitempty"` // false=复核驳回（→ REJECTED，可重新录入）
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`    // 复核意见
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovePaymentReq) Reset() {
	*x = ApprovePaymentReq{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovePaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovePaymentReq) ProtoMessage() {}

func (x *ApprovePaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovePaymentReq.ProtoReflect.Descriptor instead.
func (*ApprovePaymentReq) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{6}
}

func (x *ApprovePaymentReq) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *ApprovePaymentReq) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

func (x *ApprovePaymentReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type ApprovePaymentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovePaymentResp) Reset() {
	*x = ApprovePaymentResp{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovePaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovePaymentResp) ProtoMessage() {}

func (x *ApprovePaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovePaymentResp.ProtoReflect.Descriptor instead.
func (*ApprovePaymentResp) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{7}
}

type SettlePaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	Remark        string                 `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlePaymentReq) Reset() {
	*x = SettlePaymentReq{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlePaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlePaymentReq) ProtoMessage() {}

func (x *SettlePaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlePaymentReq.ProtoReflect.Descriptor instead.
func (*SettlePaymentReq) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{8}
}

func (x *SettlePaymentReq) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *SettlePaymentReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type SettlePaymentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlePaymentResp) Reset() {
	*x = SettlePaymentResp{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlePaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlePaymentResp) ProtoMessage() {}

func (x *SettlePaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlePaymentResp.ProtoReflect.Descriptor instead.
func (*SettlePaymentResp) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{9}
}

type PaymentDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // PAYING/REVIEWING/PAID/REJECTED/SETTLED/CLOSED
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PaidAmount    string                 `protobuf:"bytes,6,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`
	ChannelTxnId  string                 `protobuf:"bytes,7,opt,name=channel_txn_id,json=channelTxnId,proto3" json:"channel_txn_id,omitempty"` // 渠道流水（脱敏由 BFF 决定，财务域明文）
	PayerPartyId  int64                  `protobuf:"varint,8,opt,name=payer_party_id,json=payerPartyId,proto3" json:"payer_party_id,omitempty"`
	CreatedBy     int64                  `protobuf:"varint,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`     // 录入人（对公复核职责分离比对）
	ApprovedBy    int64                  `protobuf:"varint,10,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"` // 复核人
	Remark        string                 `protobuf:"bytes,11,opt,name=remark,proto3" json:"remark,omitempty"`
	PaidAt        int64                  `protobuf:"varint,12,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentDetail) Reset() {
	*x = PaymentDetail{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentDetail) ProtoMessage() {}

func (x *PaymentDetail) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentDetail.ProtoReflect.Descriptor instead.
func (*PaymentDetail) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{10}
}

func (x *PaymentDetail) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *PaymentDetail) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PaymentDetail) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PaymentDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentDetail) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *PaymentDetail) GetPaidAmount() string {
	if x != nil {
		return x.PaidAmount
	}
	return ""
}

func (x *PaymentDetail) GetChannelTxnId() string {
	if x != nil {
		return x.ChannelTxnId
	}
	return ""
}

func (x *PaymentDetail) GetPayerPartyId() int64 {
	if x != nil {
		return x.PayerPartyId
	}
	return 0
}

func (x *PaymentDetail) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *PaymentDetail) GetApprovedBy() int64 {
	if x != nil {
		return x.ApprovedBy
	}
	return 0
}

func (x *PaymentDetail) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *PaymentDetail) GetPaidAt() int64 {
	if x != nil {
		return x.PaidAt
	}
	return 0
}

func (x *PaymentDetail) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetPaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentReq) Reset() {
	*x = GetPaymentReq{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentReq) ProtoMessage() {}

func (x *GetPaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentReq.ProtoReflect.Descriptor instead.
func (*GetPaymentReq) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{11}
}

func (x *GetPaymentReq) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

type GetPaymentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *PaymentDetail         `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentResp) Reset() {
	*x = GetPaymentResp{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentResp) ProtoMessage() {}

func (x *GetPaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentResp.ProtoReflect.Descriptor instead.
func (*GetPaymentResp) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{12}
}

func (x *GetPaymentResp) GetPayment() *PaymentDetail {
	if x != nil {
		return x.Payment
	}
	return nil
}

type ListPaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"` // payment_no/order_no 模糊
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"` // 空=全部
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`   // 空=全部；REVIEWING 高亮（前端）
	Page          int64                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentReq) Reset() {
	*x = ListPaymentReq{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentReq) ProtoMessage() {}

func (x *ListPaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentReq.ProtoReflect.Descriptor instead.
func (*ListPaymentReq) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{13}
}

func (x *ListPaymentReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListPaymentReq) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ListPaymentReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListPaymentReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPaymentReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListPaymentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*PaymentDetail       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentResp) Reset() {
	*x = ListPaymentResp{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentResp) ProtoMessage() {}

func (x *ListPaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentResp.ProtoReflect.Descriptor instead.
func (*ListPaymentResp) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{14}
}

func (x *ListPaymentResp) GetList() []*PaymentDetail {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListPaymentResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type WechatPayURLReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WechatPayURLReq) Reset() {
	*x = WechatPayURLReq{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WechatPayURLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatPayURLReq) ProtoMessage() {}

func (x *WechatPayURLReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatPayURLReq.ProtoReflect.Descriptor instead.
func (*WechatPayURLReq) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{15}
}

func (x *WechatPayURLReq) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

type WechatPayURLResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayUrl        string                 `protobuf:"bytes,1,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"` // JSAPI/Native 支付链接（dev = mock URL）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WechatPayURLResp) Reset() {
	*x = WechatPayURLResp{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WechatPayURLResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatPayURLResp) ProtoMessage() {}

func (x *WechatPayURLResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatPayURLResp.ProtoReflect.Descriptor instead.
func (*WechatPayURLResp) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{16}
}

func (x *WechatPayURLResp) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

type WechatCallbackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeadersJson   string                 `protobuf:"bytes,1,opt,name=headers_json,json=headersJson,proto3" json:"headers_json,omitempty"` // Wechatpay-Timestamp/Nonce/Signature/Serial
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`                                  // 回调报文原文（AES-GCM 密文解密后取 amount/txn）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WechatCallbackReq) Reset() {
	*x = WechatCallbackReq{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WechatCallbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatCallbackReq) ProtoMessage() {}

func (x *WechatCallbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatCallbackReq.ProtoReflect.Descriptor instead.
func (*WechatCallbackReq) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{17}
}

func (x *WechatCallbackReq) GetHeadersJson() string {
	if x != nil {
		return x.HeadersJson
	}
	return ""
}

func (x *WechatCallbackReq) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type WechatCallbackResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // true = 已受理（验签+落账），应答渠道成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WechatCallbackResp) Reset() {
	*x = WechatCallbackResp{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WechatCallbackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatCallbackResp) ProtoMessage() {}

func (x *WechatCallbackResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatCallbackResp.ProtoReflect.Descriptor instead.
func (*WechatCallbackResp) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{18}
}

func (x *WechatCallbackResp) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type AlipayPayURLReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlipayPayURLReq) Reset() {
	*x = AlipayPayURLReq{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlipayPayURLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlipayPayURLReq) ProtoMessage() {}

func (x *AlipayPayURLReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlipayPayURLReq.ProtoReflect.Descriptor instead.
func (*AlipayPayURLReq) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{19}
}

func (x *AlipayPayURLReq) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

type AlipayPayURLResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayUrl        string                 `protobuf:"bytes,1,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlipayPayURLResp) Reset() {
	*x = AlipayPayURLResp{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlipayPayURLResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlipayPayURLResp) ProtoMessage() {}

func (x *AlipayPayURLResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlipayPayURLResp.ProtoReflect.Descriptor instead.
func (*AlipayPayURLResp) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{20}
}

func (x *AlipayPayURLResp) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

type AlipayCallbackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormJson      string                 `protobuf:"bytes,1,opt,name=form_json,json=formJson,proto3" json:"form_json,omitempty"` // 异步通知表单（sign/sign_type/字段集）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlipayCallbackReq) Reset() {
	*x = AlipayCallbackReq{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlipayCallbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlipayCallbackReq) ProtoMessage() {}

func (x *AlipayCallbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlipayCallbackReq.ProtoReflect.Descriptor instead.
func (*AlipayCallbackReq) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{21}
}

func (x *AlipayCallbackReq) GetFormJson() string {
	if x != nil {
		return x.FormJson
	}
	return ""
}

type AlipayCallbackResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlipayCallbackResp) Reset() {
	*x = AlipayCallbackResp{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlipayCallbackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlipayCallbackResp) ProtoMessage() {}

func (x *AlipayCallbackResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlipayCallbackResp.ProtoReflect.Descriptor instead.
func (*AlipayCallbackResp) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{22}
}

func (x *AlipayCallbackResp) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type RefundDetail struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RefundNo        string                 `protobuf:"bytes,1,opt,name=refund_no,json=refundNo,proto3" json:"refund_no,omitempty"`
	PaymentNo       string                 `protobuf:"bytes,2,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	OrderNo         string                 `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	ReturnNo        string                 `protobuf:"bytes,4,opt,name=return_no,json=returnNo,proto3" json:"return_no,omitempty"` // 触发退货单（空=手工退款）
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Channel         string                 `protobuf:"bytes,6,opt,name=channel,proto3" json:"channel,omitempty"` // 原路退回 = 原支付渠道
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`   // PROCESSING/SUCCESS/FAILED
	ChannelRefundId string                 `protobuf:"bytes,8,opt,name=channel_refund_id,json=channelRefundId,proto3" json:"channel_refund_id,omitempty"`
	Reason          string                 `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RefundDetail) Reset() {
	*x = RefundDetail{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundDetail) ProtoMessage() {}

func (x *RefundDetail) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundDetail.ProtoReflect.Descriptor instead.
func (*RefundDetail) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{23}
}

func (x *RefundDetail) GetRefundNo() string {
	if x != nil {
		return x.RefundNo
	}
	return ""
}

func (x *RefundDetail) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *RefundDetail) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *RefundDetail) GetReturnNo() string {
	if x != nil {
		return x.ReturnNo
	}
	return ""
}

func (x *RefundDetail) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *RefundDetail) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *RefundDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RefundDetail) GetChannelRefundId() string {
	if x != nil {
		return x.ChannelRefundId
	}
	return ""
}

func (x *RefundDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RefundDetail) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateRefundReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"` // 原路退回锚点
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	ReturnNo      string                 `protobuf:"bytes,3,opt,name=return_no,json=returnNo,proto3" json:"return_no,omitempty"` // 退货审批触发时必传（幂等键成分）
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRefundReq) Reset() {
	*x = CreateRefundReq{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRefundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRefundReq) ProtoMessage() {}

func (x *CreateRefundReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRefundReq.ProtoReflect.Descriptor instead.
func (*CreateRefundReq) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{24}
}

func (x *CreateRefundReq) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *CreateRefundReq) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreateRefundReq) GetReturnNo() string {
	if x != nil {
		return x.ReturnNo
	}
	return ""
}

func (x *CreateRefundReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CreateRefundResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundNo      string                 `protobuf:"bytes,1,opt,name=refund_no,json=refundNo,proto3" json:"refund_no,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRefundResp) Reset() {
	*x = CreateRefundResp{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRefundResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRefundResp) ProtoMessage() {}

func (x *CreateRefundResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRefundResp.ProtoReflect.Descriptor instead.
func (*CreateRefundResp) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{25}
}

func (x *CreateRefundResp) GetRefundNo() string {
	if x != nil {
		return x.RefundNo
	}
	return ""
}

func (x *CreateRefundResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListRefundReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"` // refund_no/payment_no/order_no
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRefundReq) Reset() {
	*x = ListRefundReq{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRefundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRefundReq) ProtoMessage() {}

func (x *ListRefundReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRefundReq.ProtoReflect.Descriptor instead.
func (*ListRefundReq) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{26}
}

func (x *ListRefundReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListRefundReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListRefundReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRefundReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListRefundResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*RefundDetail        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRefundResp) Reset() {
	*x = ListRefundResp{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRefundResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRefundResp) ProtoMessage() {}

func (x *ListRefundResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRefundResp.ProtoReflect.Descriptor instead.
func (*ListRefundResp) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{27}
}

func (x *ListRefundResp) GetList() []*RefundDetail {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListRefundResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type InvoiceDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceNo     string                 `protobuf:"bytes,1,opt,name=invoice_no,json=invoiceNo,proto3" json:"invoice_no,omitempty"`
	PaymentNo     string                 `protobuf:"bytes,2,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	OrderNo       string                 `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`              // 抬头
	TaxNo         string                 `protobuf:"bytes,5,opt,name=tax_no,json=taxNo,proto3" json:"tax_no,omitempty"` // 税号
	Amount        string                 `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // ISSUED/REVERSED
	ReverseReason string                 `protobuf:"bytes,8,opt,name=reverse_reason,json=reverseReason,proto3" json:"reverse_reason,omitempty"`
	IssuedAt      int64                  `protobuf:"varint,9,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceDetail) Reset() {
	*x = InvoiceDetail{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceDetail) ProtoMessage() {}

func (x *InvoiceDetail) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceDetail.ProtoReflect.Descriptor instead.
func (*InvoiceDetail) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{28}
}

func (x *InvoiceDetail) GetInvoiceNo() string {
	if x != nil {
		return x.InvoiceNo
	}
	return ""
}

func (x *InvoiceDetail) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *InvoiceDetail) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *InvoiceDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InvoiceDetail) GetTaxNo() string {
	if x != nil {
		return x.TaxNo
	}
	return ""
}

func (x *InvoiceDetail) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *InvoiceDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InvoiceDetail) GetReverseReason() string {
	if x != nil {
		return x.ReverseReason
	}
	return ""
}

func (x *InvoiceDetail) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *InvoiceDetail) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type IssueInvoiceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	TaxNo         string                 `protobuf:"bytes,3,opt,name=tax_no,json=taxNo,proto3" json:"tax_no,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueInvoiceReq) Reset() {
	*x = IssueInvoiceReq{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueInvoiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueInvoiceReq) ProtoMessage() {}

func (x *IssueInvoiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueInvoiceReq.ProtoReflect.Descriptor instead.
func (*IssueInvoiceReq) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{29}
}

func (x *IssueInvoiceReq) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *IssueInvoiceReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *IssueInvoiceReq) GetTaxNo() string {
	if x != nil {
		return x.TaxNo
	}
	return ""
}

func (x *IssueInvoiceReq) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type IssueInvoiceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceNo     string                 `protobuf:"bytes,1,opt,name=invoice_no,json=invoiceNo,proto3" json:"invoice_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueInvoiceResp) Reset() {
	*x = IssueInvoiceResp{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueInvoiceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueInvoiceResp) ProtoMessage() {}

func (x *IssueInvoiceResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueInvoiceResp.ProtoReflect.Descriptor instead.
func (*IssueInvoiceResp) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{30}
}

func (x *IssueInvoiceResp) GetInvoiceNo() string {
	if x != nil {
		return x.InvoiceNo
	}
	return ""
}

type ReverseInvoiceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceNo     string                 `protobuf:"bytes,1,opt,name=invoice_no,json=invoiceNo,proto3" json:"invoice_no,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseInvoiceReq) Reset() {
	*x = ReverseInvoiceReq{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseInvoiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseInvoiceReq) ProtoMessage() {}

func (x *ReverseInvoiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseInvoiceReq.ProtoReflect.Descriptor instead.
func (*ReverseInvoiceReq) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{31}
}

func (x *ReverseInvoiceReq) GetInvoiceNo() string {
	if x != nil {
		return x.InvoiceNo
	}
	return ""
}

func (x *ReverseInvoiceReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReverseInvoiceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseInvoiceResp) Reset() {
	*x = ReverseInvoiceResp{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseInvoiceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseInvoiceResp) ProtoMessage() {}

func (x *ReverseInvoiceResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseInvoiceResp.ProtoReflect.Descriptor instead.
func (*ReverseInvoiceResp) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{32}
}

type ListInvoiceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"` // invoice_no/payment_no/order_no
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvoiceReq) Reset() {
	*x = ListInvoiceReq{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoiceReq) ProtoMessage() {}

func (x *ListInvoiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoiceReq.ProtoReflect.Descriptor instead.
func (*ListInvoiceReq) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{33}
}

func (x *ListInvoiceReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListInvoiceReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListInvoiceReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListInvoiceReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListInvoiceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*InvoiceDetail       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvoiceResp) Reset() {
	*x = ListInvoiceResp{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoiceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoiceResp) ProtoMessage() {}

func (x *ListInvoiceResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoiceResp.ProtoReflect.Descriptor instead.
func (*ListInvoiceResp) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{34}
}

func (x *ListInvoiceResp) GetList() []*InvoiceDetail {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListInvoiceResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ReconcileTaskDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskNo        string                 `protobuf:"bytes,2,opt,name=task_no,json=taskNo,proto3" json:"task_no,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                               // PAYMENT/REFUND（资金日结；库存日结在 tools/reconcile）
	BizDate       string                 `protobuf:"bytes,4,opt,name=biz_date,json=bizDate,proto3" json:"biz_date,omitempty"`          // yyyy-MM-dd
	DiffReport    string                 `protobuf:"bytes,5,opt,name=diff_report,json=diffReport,proto3" json:"diff_report,omitempty"` // 差异报告 JSON（渠道账单 vs 系统流水）
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                           // OPEN/RESOLVED
	Resolution    string                 `protobuf:"bytes,7,opt,name=resolution,proto3" json:"resolution,omitempty"`                   // REPLAY（补投递重放，唯一允许的修复，E10）/IGNORE/…
	ResolveRemark string                 `protobuf:"bytes,8,opt,name=resolve_remark,json=resolveRemark,proto3" json:"resolve_remark,omitempty"`
	ResolvedBy    int64                  `protobuf:"varint,9,opt,name=resolved_by,json=resolvedBy,proto3" json:"resolved_by,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileTaskDetail) Reset() {
	*x = ReconcileTaskDetail{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileTaskDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileTaskDetail) ProtoMessage() {}

func (x *ReconcileTaskDetail) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileTaskDetail.ProtoReflect.Descriptor instead.
func (*ReconcileTaskDetail) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{35}
}

func (x *ReconcileTaskDetail) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ReconcileTaskDetail) GetTaskNo() string {
	if x != nil {
		return x.TaskNo
	}
	return ""
}

func (x *ReconcileTaskDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReconcileTaskDetail) GetBizDate() string {
	if x != nil {
		return x.BizDate
	}
	return ""
}

func (x *ReconcileTaskDetail) GetDiffReport() string {
	if x != nil {
		return x.DiffReport
	}
	return ""
}

func (x *ReconcileTaskDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReconcileTaskDetail) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *ReconcileTaskDetail) GetResolveRemark() string {
	if x != nil {
		return x.ResolveRemark
	}
	return ""
}

func (x *ReconcileTaskDetail) GetResolvedBy() int64 {
	if x != nil {
		return x.ResolvedBy
	}
	return 0
}

func (x *ReconcileTaskDetail) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateReconcileTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	BizDate       string                 `protobuf:"bytes,2,opt,name=biz_date,json=bizDate,proto3" json:"biz_date,omitempty"`
	DiffReport    string                 `protobuf:"bytes,3,opt,name=diff_report,json=diffReport,proto3" json:"diff_report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReconcileTaskReq) Reset() {
	*x = CreateReconcileTaskReq{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReconcileTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReconcileTaskReq) ProtoMessage() {}

func (x *CreateReconcileTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReconcileTaskReq.ProtoReflect.Descriptor instead.
func (*CreateReconcileTaskReq) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{36}
}

func (x *CreateReconcileTaskReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateReconcileTaskReq) GetBizDate() string {
	if x != nil {
		return x.BizDate
	}
	return ""
}

func (x *CreateReconcileTaskReq) GetDiffReport() string {
	if x != nil {
		return x.DiffReport
	}
	return ""
}

type CreateReconcileTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskNo        string                 `protobuf:"bytes,2,opt,name=task_no,json=taskNo,proto3" json:"task_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReconcileTaskResp) Reset() {
	*x = CreateReconcileTaskResp{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReconcileTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReconcileTaskResp) ProtoMessage() {}

func (x *CreateReconcileTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReconcileTaskResp.ProtoReflect.Descriptor instead.
func (*CreateReconcileTaskResp) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{37}
}

func (x *CreateReconcileTaskResp) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CreateReconcileTaskResp) GetTaskNo() string {
	if x != nil {
		return x.TaskNo
	}
	return ""
}

type ResolveReconcileTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Resolution    string                 `protobuf:"bytes,2,opt,name=resolution,proto3" json:"resolution,omitempty"` // REPLAY/IGNORE
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveReconcileTaskReq) Reset() {
	*x = ResolveReconcileTaskReq{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveReconcileTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveReconcileTaskReq) ProtoMessage() {}

func (x *ResolveReconcileTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveReconcileTaskReq.ProtoReflect.Descriptor instead.
func (*ResolveReconcileTaskReq) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{38}
}

func (x *ResolveReconcileTaskReq) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ResolveReconcileTaskReq) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *ResolveReconcileTaskReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type ResolveReconcileTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveReconcileTaskResp) Reset() {
	*x = ResolveReconcileTaskResp{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveReconcileTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveReconcileTaskResp) ProtoMessage() {}

func (x *ResolveReconcileTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveReconcileTaskResp.ProtoReflect.Descriptor instead.
func (*ResolveReconcileTaskResp) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{39}
}

type ListReconcileTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 空=全部
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReconcileTaskReq) Reset() {
	*x = ListReconcileTaskReq{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReconcileTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReconcileTaskReq) ProtoMessage() {}

func (x *ListReconcileTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReconcileTaskReq.ProtoReflect.Descriptor instead.
func (*ListReconcileTaskReq) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{40}
}

func (x *ListReconcileTaskReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListReconcileTaskReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReconcileTaskReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListReconcileTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ReconcileTaskDetail `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReconcileTaskResp) Reset() {
	*x = ListReconcileTaskResp{}
	mi := &file_services_finance_pb_finance_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReconcileTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReconcileTaskResp) ProtoMessage() {}

func (x *ListReconcileTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_finance_pb_finance_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReconcileTaskResp.ProtoReflect.Descriptor instead.
func (*ListReconcileTaskResp) Descriptor() ([]byte, []int) {
	return file_services_finance_pb_finance_proto_rawDescGZIP(), []int{41}
}

func (x *ListReconcileTaskResp) GetList() []*ReconcileTaskDetail {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListReconcileTaskResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_services_finance_pb_finance_proto protoreflect.FileDescriptor

const file_services_finance_pb_finance_proto_rawDesc = "" +
	"\n" +
	"!services/finance/pb/finance.proto\x12\afinance\"\t\n" +
	"\aPingReq\"\x1e\n" +
	"\bPingResp\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\"\x9d\x01\n" +
	"\x10CreatePaymentReq\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12$\n" +
	"\x0epayer_party_id\x18\x04 \x01(\x03R\fpayerPartyId\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\"i\n" +
	"\x11CreatePaymentResp\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"pay_params\x18\x03 \x01(\tR\tpayParams\"\x91\x01\n" +
	"\x11ConfirmPaymentReq\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\x12$\n" +
	"\x0echannel_txn_id\x18\x02 \x01(\tR\fchannelTxnId\x12\x1f\n" +
	"\vpaid_amount\x18\x03 \x01(\tR\n" +
	"paidAmount\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\",\n" +
	"\x12ConfirmPaymentResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"d\n" +
	"\x11ApprovePaymentReq\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\x12\x18\n" +
	"\aapprove\x18\x02 \x01(\bR\aapprove\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\"\x14\n" +
	"\x12ApprovePaymentResp\"I\n" +
	"\x10SettlePaymentReq\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\x12\x16\n" +
	"\x06remark\x18\x02 \x01(\tR\x06remark\"\x13\n" +
	"\x11SettlePaymentResp\"\x90\x03\n" +
	"\rPaymentDetail\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1f\n" +
	"\vpaid_amount\x18\x06 \x01(\tR\n" +
	"paidAmount\x12$\n" +
	"\x0echannel_txn_id\x18\a \x01(\tR\fchannelTxnId\x12$\n" +
	"\x0epayer_party_id\x18\b \x01(\x03R\fpayerPartyId\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\x03R\tcreatedBy\x12\x1f\n" +
	"\vapproved_by\x18\n" +
	" \x01(\x03R\n" +
	"approvedBy\x12\x16\n" +
	"\x06remark\x18\v \x01(\tR\x06remark\x12\x17\n" +
	"\apaid_at\x18\f \x01(\x03R\x06paidAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\x03R\tcreatedAt\".\n" +
	"\rGetPaymentReq\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\"B\n" +
	"\x0eGetPaymentResp\x120\n" +
	"\apayment\x18\x01 \x01(\v2\x16.finance.PaymentDetailR\apayment\"\x84\x01\n" +
	"\x0eListPaymentReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\"S\n" +
	"\x0fListPaymentResp\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.finance.PaymentDetailR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"0\n" +
	"\x0fWechatPayURLReq\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\"+\n" +
	"\x10WechatPayURLResp\x12\x17\n" +
	"\apay_url\x18\x01 \x01(\tR\x06payUrl\"J\n" +
	"\x11WechatCallbackReq\x12!\n" +
	"\fheaders_json\x18\x01 \x01(\tR\vheadersJson\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"0\n" +
	"\x12WechatCallbackResp\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"0\n" +
	"\x0fAlipayPayURLReq\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\"+\n" +
	"\x10AlipayPayURLResp\x12\x17\n" +
	"\apay_url\x18\x01 \x01(\tR\x06payUrl\"0\n" +
	"\x11AlipayCallbackReq\x12\x1b\n" +
	"\tform_json\x18\x01 \x01(\tR\bformJson\"0\n" +
	"\x12AlipayCallbackResp\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\xaf\x02\n" +
	"\fRefundDetail\x12\x1b\n" +
	"\trefund_no\x18\x01 \x01(\tR\brefundNo\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x02 \x01(\tR\tpaymentNo\x12\x19\n" +
	"\border_no\x18\x03 \x01(\tR\aorderNo\x12\x1b\n" +
	"\treturn_no\x18\x04 \x01(\tR\breturnNo\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x18\n" +
	"\achannel\x18\x06 \x01(\tR\achannel\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12*\n" +
	"\x11channel_refund_id\x18\b \x01(\tR\x0fchannelRefundId\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\"}\n" +
	"\x0fCreateRefundReq\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x1b\n" +
	"\treturn_no\x18\x03 \x01(\tR\breturnNo\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"G\n" +
	"\x10CreateRefundResp\x12\x1b\n" +
	"\trefund_no\x18\x01 \x01(\tR\brefundNo\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"i\n" +
	"\rListRefundReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"Q\n" +
	"\x0eListRefundResp\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.finance.RefundDetailR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa8\x02\n" +
	"\rInvoiceDetail\x12\x1d\n" +
	"\n" +
	"invoice_no\x18\x01 \x01(\tR\tinvoiceNo\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x02 \x01(\tR\tpaymentNo\x12\x19\n" +
	"\border_no\x18\x03 \x01(\tR\aorderNo\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x15\n" +
	"\x06tax_no\x18\x05 \x01(\tR\x05taxNo\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\tR\x06amount\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12%\n" +
	"\x0ereverse_reason\x18\b \x01(\tR\rreverseReason\x12\x1b\n" +
	"\tissued_at\x18\t \x01(\x03R\bissuedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\"u\n" +
	"\x0fIssueInvoiceReq\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x15\n" +
	"\x06tax_no\x18\x03 \x01(\tR\x05taxNo\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\"1\n" +
	"\x10IssueInvoiceResp\x12\x1d\n" +
	"\n" +
	"invoice_no\x18\x01 \x01(\tR\tinvoiceNo\"J\n" +
	"\x11ReverseInvoiceReq\x12\x1d\n" +
	"\n" +
	"invoice_no\x18\x01 \x01(\tR\tinvoiceNo\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x14\n" +
	"\x12ReverseInvoiceResp\"j\n" +
	"\x0eListInvoiceReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"S\n" +
	"\x0fListInvoiceResp\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.finance.InvoiceDetailR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xb6\x02\n" +
	"\x13ReconcileTaskDetail\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x17\n" +
	"\atask_no\x18\x02 \x01(\tR\x06taskNo\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x19\n" +
	"\bbiz_date\x18\x04 \x01(\tR\abizDate\x12\x1f\n" +
	"\vdiff_report\x18\x05 \x01(\tR\n" +
	"diffReport\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"resolution\x18\a \x01(\tR\n" +
	"resolution\x12%\n" +
	"\x0eresolve_remark\x18\b \x01(\tR\rresolveRemark\x12\x1f\n" +
	"\vresolved_by\x18\t \x01(\x03R\n" +
	"resolvedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\"h\n" +
	"\x16CreateReconcileTaskReq\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x19\n" +
	"\bbiz_date\x18\x02 \x01(\tR\abizDate\x12\x1f\n" +
	"\vdiff_report\x18\x03 \x01(\tR\n" +
	"diffReport\"K\n" +
	"\x17CreateReconcileTaskResp\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x17\n" +
	"\atask_no\x18\x02 \x01(\tR\x06taskNo\"j\n" +
	"\x17ResolveReconcileTaskReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x1e\n" +
	"\n" +
	"resolution\x18\x02 \x01(\tR\n" +
	"resolution\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\"\x1a\n" +
	"\x18ResolveReconcileTaskResp\"V\n" +
	"\x14ListReconcileTaskReq\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"_\n" +
	"\x15ListReconcileTaskResp\x120\n" +
	"\x04list\x18\x01 \x03(\v2\x1c.finance.ReconcileTaskDetailR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xde\n" +
	"\n" +
	"\aFinance\x12+\n" +
	"\x04Ping\x12\x10.finance.PingReq\x1a\x11.finance.PingResp\x12F\n" +
	"\rCreatePayment\x12\x19.finance.CreatePaymentReq\x1a\x1a.finance.CreatePaymentResp\x12I\n" +
	"\x0eConfirmPayment\x12\x1a.finance.ConfirmPaymentReq\x1a\x1b.finance.ConfirmPaymentResp\x12I\n" +
	"\x0eApprovePayment\x12\x1a.finance.ApprovePaymentReq\x1a\x1b.finance.ApprovePaymentResp\x12F\n" +
	"\rSettlePayment\x12\x19.finance.SettlePaymentReq\x1a\x1a.finance.SettlePaymentResp\x12=\n" +
	"\n" +
	"GetPayment\x12\x16.finance.GetPaymentReq\x1a\x17.finance.GetPaymentResp\x12@\n" +
	"\vListPayment\x12\x17.finance.ListPaymentReq\x1a\x18.finance.ListPaymentResp\x12C\n" +
	"\fWechatPayURL\x12\x18.finance.WechatPayURLReq\x1a\x19.finance.WechatPayURLResp\x12I\n" +
	"\x0eWechatCallback\x12\x1a.finance.WechatCallbackReq\x1a\x1b.finance.WechatCallbackResp\x12C\n" +
	"\fAlipayPayURL\x12\x18.finance.AlipayPayURLReq\x1a\x19.finance.AlipayPayURLResp\x12I\n" +
	"\x0eAlipayCallback\x12\x1a.finance.AlipayCallbackReq\x1a\x1b.finance.AlipayCallbackResp\x12C\n" +
	"\fCreateRefund\x12\x18.finance.CreateRefundReq\x1a\x19.finance.CreateRefundResp\x12=\n" +
	"\n" +
	"ListRefund\x12\x16.finance.ListRefundReq\x1a\x17.finance.ListRefundResp\x12C\n" +
	"\fIssueInvoice\x12\x18.finance.IssueInvoiceReq\x1a\x19.finance.IssueInvoiceResp\x12I\n" +
	"\x0eReverseInvoice\x12\x1a.finance.ReverseInvoiceReq\x1a\x1b.finance.ReverseInvoiceResp\x12@\n" +
	"\vListInvoice\x12\x17.finance.ListInvoiceReq\x1a\x18.finance.ListInvoiceResp\x12X\n" +
	"\x13CreateReconcileTask\x12\x1f.finance.CreateReconcileTaskReq\x1a .finance.CreateReconcileTaskResp\x12[\n" +
	"\x14ResolveReconcileTask\x12 .finance.ResolveReconcileTaskReq\x1a!.finance.ResolveReconcileTaskResp\x12R\n" +
	"\x11ListReconcileTask\x12\x1d.finance.ListReconcileTaskReq\x1a\x1e.finance.ListReconcileTaskRespB\x06Z\x04./pbb\x06proto3"

var (
	file_services_finance_pb_finance_proto_rawDescOnce sync.Once
	file_services_finance_pb_finance_proto_rawDescData []byte
)

func file_services_finance_pb_finance_proto_rawDescGZIP() []byte {
	file_services_finance_pb_finance_proto_rawDescOnce.Do(func() {
		file_services_finance_pb_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_finance_pb_finance_proto_rawDesc), len(file_services_finance_pb_finance_proto_rawDesc)))
	})
	return file_services_finance_pb_finance_proto_rawDescData
}

var file_services_finance_pb_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_services_finance_pb_finance_proto_goTypes = []any{
	(*PingReq)(nil),                  // 0: finance.PingReq
	(*PingResp)(nil),                 // 1: finance.PingResp
	(*CreatePaymentReq)(nil),         // 2: finance.CreatePaymentReq
	(*CreatePaymentResp)(nil),        // 3: finance.CreatePaymentResp
	(*ConfirmPaymentReq)(nil),        // 4: finance.ConfirmPaymentReq
	(*ConfirmPaymentResp)(nil),       // 5: finance.ConfirmPaymentResp
	(*ApprovePaymentReq)(nil),        // 6: finance.ApprovePaymentReq
	(*ApprovePaymentResp)(nil),       // 7: finance.ApprovePaymentResp
	(*SettlePaymentReq)(nil),         // 8: finance.SettlePaymentReq
	(*SettlePaymentResp)(nil),        // 9: finance.SettlePaymentResp
	(*PaymentDetail)(nil),            // 10: finance.PaymentDetail
	(*GetPaymentReq)(nil),            // 11: finance.GetPaymentReq
	(*GetPaymentResp)(nil),           // 12: finance.GetPaymentResp
	(*ListPaymentReq)(nil),           // 13: finance.ListPaymentReq
	(*ListPaymentResp)(nil),          // 14: finance.ListPaymentResp
	(*WechatPayURLReq)(nil),          // 15: finance.WechatPayURLReq
	(*WechatPayURLResp)(nil),         // 16: finance.WechatPayURLResp
	(*WechatCallbackReq)(nil),        // 17: finance.WechatCallbackReq
	(*WechatCallbackResp)(nil),       // 18: finance.WechatCallbackResp
	(*AlipayPayURLReq)(nil),          // 19: finance.AlipayPayURLReq
	(*AlipayPayURLResp)(nil),         // 20: finance.AlipayPayURLResp
	(*AlipayCallbackReq)(nil),        // 21: finance.AlipayCallbackReq
	(*AlipayCallbackResp)(nil),       // 22: finance.AlipayCallbackResp
	(*RefundDetail)(nil),             // 23: finance.RefundDetail
	(*CreateRefundReq)(nil),          // 24: finance.CreateRefundReq
	(*CreateRefundResp)(nil),         // 25: finance.CreateRefundResp
	(*ListRefundReq)(nil),            // 26: finance.ListRefundReq
	(*ListRefundResp)(nil),           // 27: finance.ListRefundResp
	(*InvoiceDetail)(nil),            // 28: finance.InvoiceDetail
	(*IssueInvoiceReq)(nil),          // 29: finance.IssueInvoiceReq
	(*IssueInvoiceResp)(nil),         // 30: finance.IssueInvoiceResp
	(*ReverseInvoiceReq)(nil),        // 31: finance.ReverseInvoiceReq
	(*ReverseInvoiceResp)(nil),       // 32: finance.ReverseInvoiceResp
	(*ListInvoiceReq)(nil),           // 33: finance.ListInvoiceReq
	(*ListInvoiceResp)(nil),          // 34: finance.ListInvoiceResp
	(*ReconcileTaskDetail)(nil),      // 35: finance.ReconcileTaskDetail
	(*CreateReconcileTaskReq)(nil),   // 36: finance.CreateReconcileTaskReq
	(*CreateReconcileTaskResp)(nil),  // 37: finance.CreateReconcileTaskResp
	(*ResolveReconcileTaskReq)(nil),  // 38: finance.ResolveReconcileTaskReq
	(*ResolveReconcileTaskResp)(nil), // 39: finance.ResolveReconcileTaskResp
	(*ListReconcileTaskReq)(nil),     // 40: finance.ListReconcileTaskReq
	(*ListReconcileTaskResp)(nil),    // 41: finance.ListReconcileTaskResp
}
var file_services_finance_pb_finance_proto_depIdxs = []int32{
	10, // 0: finance.GetPaymentResp.payment:type_name -> finance.PaymentDetail
	10, // 1: finance.ListPaymentResp.list:type_name -> finance.PaymentDetail
	23, // 2: finance.ListRefundResp.list:type_name -> finance.RefundDetail
	28, // 3: finance.ListInvoiceResp.list:type_name -> finance.InvoiceDetail
	35, // 4: finance.ListReconcileTaskResp.list:type_name -> finance.ReconcileTaskDetail
	0,  // 5: finance.Finance.Ping:input_type -> finance.PingReq
	2,  // 6: finance.Finance.CreatePayment:input_type -> finance.CreatePaymentReq
	4,  // 7: finance.Finance.ConfirmPayment:input_type -> finance.ConfirmPaymentReq
	6,  // 8: finance.Finance.ApprovePayment:input_type -> finance.ApprovePaymentReq
	8,  // 9: finance.Finance.SettlePayment:input_type -> finance.SettlePaymentReq
	11, // 10: finance.Finance.GetPayment:input_type -> finance.GetPaymentReq
	13, // 11: finance.Finance.ListPayment:input_type -> finance.ListPaymentReq
	15, // 12: finance.Finance.WechatPayURL:input_type -> finance.WechatPayURLReq
	17, // 13: finance.Finance.WechatCallback:input_type -> finance.WechatCallbackReq
	19, // 14: finance.Finance.AlipayPayURL:input_type -> finance.AlipayPayURLReq
	21, // 15: finance.Finance.AlipayCallback:input_type -> finance.AlipayCallbackReq
	24, // 16: finance.Finance.CreateRefund:input_type -> finance.CreateRefundReq
	26, // 17: finance.Finance.ListRefund:input_type -> finance.ListRefundReq
	29, // 18: finance.Finance.IssueInvoice:input_type -> finance.IssueInvoiceReq
	31, // 19: finance.Finance.ReverseInvoice:input_type -> finance.ReverseInvoiceReq
	33, // 20: finance.Finance.ListInvoice:input_type -> finance.ListInvoiceReq
	36, // 21: finance.Finance.CreateReconcileTask:input_type -> finance.CreateReconcileTaskReq
	38, // 22: finance.Finance.ResolveReconcileTask:input_type -> finance.ResolveReconcileTaskReq
	40, // 23: finance.Finance.ListReconcileTask:input_type -> finance.ListReconcileTaskReq
	1,  // 24: finance.Finance.Ping:output_type -> finance.PingResp
	3,  // 25: finance.Finance.CreatePayment:output_type -> finance.CreatePaymentResp
	5,  // 26: finance.Finance.ConfirmPayment:output_type -> finance.ConfirmPaymentResp
	7,  // 27: finance.Finance.ApprovePayment:output_type -> finance.ApprovePaymentResp
	9,  // 28: finance.Finance.SettlePayment:output_type -> finance.SettlePaymentResp
	12, // 29: finance.Finance.GetPayment:output_type -> finance.GetPaymentResp
	14, // 30: finance.Finance.ListPayment:output_type -> finance.ListPaymentResp
	16, // 31: finance.Finance.WechatPayURL:output_type -> finance.WechatPayURLResp
	18, // 32: finance.Finance.WechatCallback:output_type -> finance.WechatCallbackResp
	20, // 33: finance.Finance.AlipayPayURL:output_type -> finance.AlipayPayURLResp
	22, // 34: finance.Finance.AlipayCallback:output_type -> finance.AlipayCallbackResp
	25, // 35: finance.Finance.CreateRefund:output_type -> finance.CreateRefundResp
	27, // 36: finance.Finance.ListRefund:output_type -> finance.ListRefundResp
	30, // 37: finance.Finance.IssueInvoice:output_type -> finance.IssueInvoiceResp
	32, // 38: finance.Finance.ReverseInvoice:output_type -> finance.ReverseInvoiceResp
	34, // 39: finance.Finance.ListInvoice:output_type -> finance.ListInvoiceResp
	37, // 40: finance.Finance.CreateReconcileTask:output_type -> finance.CreateReconcileTaskResp
	39, // 41: finance.Finance.ResolveReconcileTask:output_type -> finance.ResolveReconcileTaskResp
	41, // 42: finance.Finance.ListReconcileTask:output_type -> finance.ListReconcileTaskResp
	24, // [24:43] is the sub-list for method output_type
	5,  // [5:24] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_services_finance_pb_finance_proto_init() }
func file_services_finance_pb_finance_proto_init() {
	if File_services_finance_pb_finance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_finance_pb_finance_proto_rawDesc), len(file_services_finance_pb_finance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_finance_pb_finance_proto_goTypes,
		DependencyIndexes: file_services_finance_pb_finance_proto_depIdxs,
		MessageInfos:      file_services_finance_pb_finance_proto_msgTypes,
	}.Build()
	File_services_finance_pb_finance_proto = out.File
	file_services_finance_pb_finance_proto_goTypes = nil
	file_services_finance_pb_finance_proto_depIdxs = nil
}
