// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: services/finance/pb/finance.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Finance_Ping_FullMethodName                 = "/finance.Finance/Ping"
	Finance_CreatePayment_FullMethodName        = "/finance.Finance/CreatePayment"
	Finance_ConfirmPayment_FullMethodName       = "/finance.Finance/ConfirmPayment"
	Finance_ApprovePayment_FullMethodName       = "/finance.Finance/ApprovePayment"
	Finance_SettlePayment_FullMethodName        = "/finance.Finance/SettlePayment"
	Finance_GetPayment_FullMethodName           = "/finance.Finance/GetPayment"
	Finance_ListPayment_FullMethodName          = "/finance.Finance/ListPayment"
	Finance_WechatPayURL_FullMethodName         = "/finance.Finance/WechatPayURL"
	Finance_WechatCallback_FullMethodName       = "/finance.Finance/WechatCallback"
	Finance_AlipayPayURL_FullMethodName         = "/finance.Finance/AlipayPayURL"
	Finance_AlipayCallback_FullMethodName       = "/finance.Finance/AlipayCallback"
	Finance_CreateRefund_FullMethodName         = "/finance.Finance/CreateRefund"
	Finance_ListRefund_FullMethodName           = "/finance.Finance/ListRefund"
	Finance_IssueInvoice_FullMethodName         = "/finance.Finance/IssueInvoice"
	Finance_ReverseInvoice_FullMethodName       = "/finance.Finance/ReverseInvoice"
	Finance_ListInvoice_FullMethodName          = "/finance.Finance/ListInvoice"
	Finance_CreateReconcileTask_FullMethodName  = "/finance.Finance/CreateReconcileTask"
	Finance_ResolveReconcileTask_FullMethodName = "/finance.Finance/ResolveReconcileTask"
	Finance_ListReconcileTask_FullMethodName    = "/finance.Finance/ListReconcileTask"
)

// FinanceClient is the client API for Finance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Finance 财务服务契约（S5-03，v4/03 阶段 5 任务正本）。
//
// 职责边界：finance_db 是支付单/退款/发票/对账任务的唯一写入方（FR-FIN）。
// 渠道：微信 v3（JSAPI+回调验签）/ 支付宝 RSA2 / 对公转账（BANK_OFFLINE）；
// dev 模拟网关（MockGateway=true，冒烟不依赖真实商户号，02 §10 渠道韧性策略表）。
// 对公收款职责分离：录入（CreatePayment）→ REVIEWING → 第二人复核（ApprovePayment，
// created_by == 复核人 拒绝）→ PAID；回调验签成功才 ConfirmPayment。
// 支付成功（ConfirmPayment/ApprovePayment）发 order_paid 事件（topic 契约固定，key=order_no）；
// 退货审批事件 order_return_approved → 自动 CreateRefund 原路退回 → payment_refunded 回写。
// 退款幂等：payment_no + return_no 唯一约束（FR-FIN-002）。
// ID 传输 int64，对外 string（E8）；金额 DECIMAL 字符串。
type FinanceClient interface {
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
	// ---- 支付单 ----
	CreatePayment(ctx context.Context, in *CreatePaymentReq, opts ...grpc.CallOption) (*CreatePaymentResp, error)
	ConfirmPayment(ctx context.Context, in *ConfirmPaymentReq, opts ...grpc.CallOption) (*ConfirmPaymentResp, error)
	ApprovePayment(ctx context.Context, in *ApprovePaymentReq, opts ...grpc.CallOption) (*ApprovePaymentResp, error)
	SettlePayment(ctx context.Context, in *SettlePaymentReq, opts ...grpc.CallOption) (*SettlePaymentResp, error)
	GetPayment(ctx context.Context, in *GetPaymentReq, opts ...grpc.CallOption) (*GetPaymentResp, error)
	ListPayment(ctx context.Context, in *ListPaymentReq, opts ...grpc.CallOption) (*ListPaymentResp, error)
	// ---- 渠道 ----
	WechatPayURL(ctx context.Context, in *WechatPayURLReq, opts ...grpc.CallOption) (*WechatPayURLResp, error)
	WechatCallback(ctx context.Context, in *WechatCallbackReq, opts ...grpc.CallOption) (*WechatCallbackResp, error)
	AlipayPayURL(ctx context.Context, in *AlipayPayURLReq, opts ...grpc.CallOption) (*AlipayPayURLResp, error)
	AlipayCallback(ctx context.Context, in *AlipayCallbackReq, opts ...grpc.CallOption) (*AlipayCallbackResp, error)
	// ---- 退款 ----
	CreateRefund(ctx context.Context, in *CreateRefundReq, opts ...grpc.CallOption) (*CreateRefundResp, error)
	ListRefund(ctx context.Context, in *ListRefundReq, opts ...grpc.CallOption) (*ListRefundResp, error)
	// ---- 发票（ISSUED/REVERSED 状态机桩，FR-FIN-004）----
	IssueInvoice(ctx context.Context, in *IssueInvoiceReq, opts ...grpc.CallOption) (*IssueInvoiceResp, error)
	ReverseInvoice(ctx context.Context, in *ReverseInvoiceReq, opts ...grpc.CallOption) (*ReverseInvoiceResp, error)
	ListInvoice(ctx context.Context, in *ListInvoiceReq, opts ...grpc.CallOption) (*ListInvoiceResp, error)
	// ---- 对账任务（FR-FIN-003，差异修复只允许补投递重放，E10）----
	CreateReconcileTask(ctx context.Context, in *CreateReconcileTaskReq, opts ...grpc.CallOption) (*CreateReconcileTaskResp, error)
	ResolveReconcileTask(ctx context.Context, in *ResolveReconcileTaskReq, opts ...grpc.CallOption) (*ResolveReconcileTaskResp, error)
	ListReconcileTask(ctx context.Context, in *ListReconcileTaskReq, opts ...grpc.CallOption) (*ListReconcileTaskResp, error)
}

type financeClient struct {
	cc grpc.ClientConnInterface
}

func NewFinanceClient(cc grpc.ClientConnInterface) FinanceClient {
	return &financeClient{cc}
}

func (c *financeClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResp)
	err := c.cc.Invoke(ctx, Finance_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) CreatePayment(ctx context.Context, in *CreatePaymentReq, opts ...grpc.CallOption) (*CreatePaymentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentResp)
	err := c.cc.Invoke(ctx, Finance_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) ConfirmPayment(ctx context.Context, in *ConfirmPaymentReq, opts ...grpc.CallOption) (*ConfirmPaymentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmPaymentResp)
	err := c.cc.Invoke(ctx, Finance_ConfirmPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) ApprovePayment(ctx context.Context, in *ApprovePaymentReq, opts ...grpc.CallOption) (*ApprovePaymentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovePaymentResp)
	err := c.cc.Invoke(ctx, Finance_ApprovePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) SettlePayment(ctx context.Context, in *SettlePaymentReq, opts ...grpc.CallOption) (*SettlePaymentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettlePaymentResp)
	err := c.cc.Invoke(ctx, Finance_SettlePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) GetPayment(ctx context.Context, in *GetPaymentReq, opts ...grpc.CallOption) (*GetPaymentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentResp)
	err := c.cc.Invoke(ctx, Finance_GetPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) ListPayment(ctx context.Context, in *ListPaymentReq, opts ...grpc.CallOption) (*ListPaymentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPaymentResp)
	err := c.cc.Invoke(ctx, Finance_ListPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) WechatPayURL(ctx context.Context, in *WechatPayURLReq, opts ...grpc.CallOption) (*WechatPayURLResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WechatPayURLResp)
	err := c.cc.Invoke(ctx, Finance_WechatPayURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) WechatCallback(ctx context.Context, in *WechatCallbackReq, opts ...grpc.CallOption) (*WechatCallbackResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WechatCallbackResp)
	err := c.cc.Invoke(ctx, Finance_WechatCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) AlipayPayURL(ctx context.Context, in *AlipayPayURLReq, opts ...grpc.CallOption) (*AlipayPayURLResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlipayPayURLResp)
	err := c.cc.Invoke(ctx, Finance_AlipayPayURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) AlipayCallback(ctx context.Context, in *AlipayCallbackReq, opts ...grpc.CallOption) (*AlipayCallbackResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlipayCallbackResp)
	err := c.cc.Invoke(ctx, Finance_AlipayCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) CreateRefund(ctx context.Context, in *CreateRefundReq, opts ...grpc.CallOption) (*CreateRefundResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRefundResp)
	err := c.cc.Invoke(ctx, Finance_CreateRefund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) ListRefund(ctx context.Context, in *ListRefundReq, opts ...grpc.CallOption) (*ListRefundResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRefundResp)
	err := c.cc.Invoke(ctx, Finance_ListRefund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) IssueInvoice(ctx context.Context, in *IssueInvoiceReq, opts ...grpc.CallOption) (*IssueInvoiceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueInvoiceResp)
	err := c.cc.Invoke(ctx, Finance_IssueInvoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) ReverseInvoice(ctx context.Context, in *ReverseInvoiceReq, opts ...grpc.CallOption) (*ReverseInvoiceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReverseInvoiceResp)
	err := c.cc.Invoke(ctx, Finance_ReverseInvoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) ListInvoice(ctx context.Context, in *ListInvoiceReq, opts ...grpc.CallOption) (*ListInvoiceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInvoiceResp)
	err := c.cc.Invoke(ctx, Finance_ListInvoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) CreateReconcileTask(ctx context.Context, in *CreateReconcileTaskReq, opts ...grpc.CallOption) (*CreateReconcileTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReconcileTaskResp)
	err := c.cc.Invoke(ctx, Finance_CreateReconcileTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) ResolveReconcileTask(ctx context.Context, in *ResolveReconcileTaskReq, opts ...grpc.CallOption) (*ResolveReconcileTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveReconcileTaskResp)
	err := c.cc.Invoke(ctx, Finance_ResolveReconcileTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) ListReconcileTask(ctx context.Context, in *ListReconcileTaskReq, opts ...grpc.CallOption) (*ListReconcileTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReconcileTaskResp)
	err := c.cc.Invoke(ctx, Finance_ListReconcileTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinanceServer is the server API for Finance service.
// All implementations must embed UnimplementedFinanceServer
// for forward compatibility.
//
// Finance 财务服务契约（S5-03，v4/03 阶段 5 任务正本）。
//
// 职责边界：finance_db 是支付单/退款/发票/对账任务的唯一写入方（FR-FIN）。
// 渠道：微信 v3（JSAPI+回调验签）/ 支付宝 RSA2 / 对公转账（BANK_OFFLINE）；
// dev 模拟网关（MockGateway=true，冒烟不依赖真实商户号，02 §10 渠道韧性策略表）。
// 对公收款职责分离：录入（CreatePayment）→ REVIEWING → 第二人复核（ApprovePayment，
// created_by == 复核人 拒绝）→ PAID；回调验签成功才 ConfirmPayment。
// 支付成功（ConfirmPayment/ApprovePayment）发 order_paid 事件（topic 契约固定，key=order_no）；
// 退货审批事件 order_return_approved → 自动 CreateRefund 原路退回 → payment_refunded 回写。
// 退款幂等：payment_no + return_no 唯一约束（FR-FIN-002）。
// ID 传输 int64，对外 string（E8）；金额 DECIMAL 字符串。
type FinanceServer interface {
	Ping(context.Context, *PingReq) (*PingResp, error)
	// ---- 支付单 ----
	CreatePayment(context.Context, *CreatePaymentReq) (*CreatePaymentResp, error)
	ConfirmPayment(context.Context, *ConfirmPaymentReq) (*ConfirmPaymentResp, error)
	ApprovePayment(context.Context, *ApprovePaymentReq) (*ApprovePaymentResp, error)
	SettlePayment(context.Context, *SettlePaymentReq) (*SettlePaymentResp, error)
	GetPayment(context.Context, *GetPaymentReq) (*GetPaymentResp, error)
	ListPayment(context.Context, *ListPaymentReq) (*ListPaymentResp, error)
	// ---- 渠道 ----
	WechatPayURL(context.Context, *WechatPayURLReq) (*WechatPayURLResp, error)
	WechatCallback(context.Context, *WechatCallbackReq) (*WechatCallbackResp, error)
	AlipayPayURL(context.Context, *AlipayPayURLReq) (*AlipayPayURLResp, error)
	AlipayCallback(context.Context, *AlipayCallbackReq) (*AlipayCallbackResp, error)
	// ---- 退款 ----
	CreateRefund(context.Context, *CreateRefundReq) (*CreateRefundResp, error)
	ListRefund(context.Context, *ListRefundReq) (*ListRefundResp, error)
	// ---- 发票（ISSUED/REVERSED 状态机桩，FR-FIN-004）----
	IssueInvoice(context.Context, *IssueInvoiceReq) (*IssueInvoiceResp, error)
	ReverseInvoice(context.Context, *ReverseInvoiceReq) (*ReverseInvoiceResp, error)
	ListInvoice(context.Context, *ListInvoiceReq) (*ListInvoiceResp, error)
	// ---- 对账任务（FR-FIN-003，差异修复只允许补投递重放，E10）----
	CreateReconcileTask(context.Context, *CreateReconcileTaskReq) (*CreateReconcileTaskResp, error)
	ResolveReconcileTask(context.Context, *ResolveReconcileTaskReq) (*ResolveReconcileTaskResp, error)
	ListReconcileTask(context.Context, *ListReconcileTaskReq) (*ListReconcileTaskResp, error)
	mustEmbedUnimplementedFinanceServer()
}

// UnimplementedFinanceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFinanceServer struct{}

func (UnimplementedFinanceServer) Ping(context.Context, *PingReq) (*PingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedFinanceServer) CreatePayment(context.Context, *CreatePaymentReq) (*CreatePaymentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedFinanceServer) ConfirmPayment(context.Context, *ConfirmPaymentReq) (*ConfirmPaymentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmPayment not implemented")
}
func (UnimplementedFinanceServer) ApprovePayment(context.Context, *ApprovePaymentReq) (*ApprovePaymentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ApprovePayment not implemented")
}
func (UnimplementedFinanceServer) SettlePayment(context.Context, *SettlePaymentReq) (*SettlePaymentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SettlePayment not implemented")
}
func (UnimplementedFinanceServer) GetPayment(context.Context, *GetPaymentReq) (*GetPaymentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayment not implemented")
}
func (UnimplementedFinanceServer) ListPayment(context.Context, *ListPaymentReq) (*ListPaymentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPayment not implemented")
}
func (UnimplementedFinanceServer) WechatPayURL(context.Context, *WechatPayURLReq) (*WechatPayURLResp, error) {
	return nil, status.Error(codes.Unimplemented, "method WechatPayURL not implemented")
}
func (UnimplementedFinanceServer) WechatCallback(context.Context, *WechatCallbackReq) (*WechatCallbackResp, error) {
	return nil, status.Error(codes.Unimplemented, "method WechatCallback not implemented")
}
func (UnimplementedFinanceServer) AlipayPayURL(context.Context, *AlipayPayURLReq) (*AlipayPayURLResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AlipayPayURL not implemented")
}
func (UnimplementedFinanceServer) AlipayCallback(context.Context, *AlipayCallbackReq) (*AlipayCallbackResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AlipayCallback not implemented")
}
func (UnimplementedFinanceServer) CreateRefund(context.Context, *CreateRefundReq) (*CreateRefundResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRefund not implemented")
}
func (UnimplementedFinanceServer) ListRefund(context.Context, *ListRefundReq) (*ListRefundResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRefund not implemented")
}
func (UnimplementedFinanceServer) IssueInvoice(context.Context, *IssueInvoiceReq) (*IssueInvoiceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueInvoice not implemented")
}
func (UnimplementedFinanceServer) ReverseInvoice(context.Context, *ReverseInvoiceReq) (*ReverseInvoiceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReverseInvoice not implemented")
}
func (UnimplementedFinanceServer) ListInvoice(context.Context, *ListInvoiceReq) (*ListInvoiceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInvoice not implemented")
}
func (UnimplementedFinanceServer) CreateReconcileTask(context.Context, *CreateReconcileTaskReq) (*CreateReconcileTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateReconcileTask not implemented")
}
func (UnimplementedFinanceServer) ResolveReconcileTask(context.Context, *ResolveReconcileTaskReq) (*ResolveReconcileTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveReconcileTask not implemented")
}
func (UnimplementedFinanceServer) ListReconcileTask(context.Context, *ListReconcileTaskReq) (*ListReconcileTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReconcileTask not implemented")
}
func (UnimplementedFinanceServer) mustEmbedUnimplementedFinanceServer() {}
func (UnimplementedFinanceServer) testEmbeddedByValue()                 {}

// UnsafeFinanceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinanceServer will
// result in compilation errors.
type UnsafeFinanceServer interface {
	mustEmbedUnimplementedFinanceServer()
}

func RegisterFinanceServer(s grpc.ServiceRegistrar, srv FinanceServer) {
	// If the following call panics, it indicates UnimplementedFinanceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Finance_ServiceDesc, srv)
}

func _Finance_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).CreatePayment(ctx, req.(*CreatePaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_ConfirmPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).ConfirmPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_ConfirmPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).ConfirmPayment(ctx, req.(*ConfirmPaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_ApprovePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApprovePaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).ApprovePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_ApprovePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).ApprovePayment(ctx, req.(*ApprovePaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_SettlePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettlePaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).SettlePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_SettlePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).SettlePayment(ctx, req.(*SettlePaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_GetPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).GetPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_GetPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).GetPayment(ctx, req.(*GetPaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_ListPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).ListPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_ListPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).ListPayment(ctx, req.(*ListPaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_WechatPayURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WechatPayURLReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).WechatPayURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_WechatPayURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).WechatPayURL(ctx, req.(*WechatPayURLReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_WechatCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WechatCallbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).WechatCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_WechatCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).WechatCallback(ctx, req.(*WechatCallbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_AlipayPayURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlipayPayURLReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).AlipayPayURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_AlipayPayURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).AlipayPayURL(ctx, req.(*AlipayPayURLReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_AlipayCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlipayCallbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).AlipayCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_AlipayCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).AlipayCallback(ctx, req.(*AlipayCallbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_CreateRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRefundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).CreateRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_CreateRefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).CreateRefund(ctx, req.(*CreateRefundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_ListRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRefundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).ListRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_ListRefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).ListRefund(ctx, req.(*ListRefundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_IssueInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueInvoiceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).IssueInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_IssueInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).IssueInvoice(ctx, req.(*IssueInvoiceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_ReverseInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseInvoiceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).ReverseInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_ReverseInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).ReverseInvoice(ctx, req.(*ReverseInvoiceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_ListInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInvoiceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).ListInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_ListInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).ListInvoice(ctx, req.(*ListInvoiceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_CreateReconcileTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReconcileTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).CreateReconcileTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_CreateReconcileTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).CreateReconcileTask(ctx, req.(*CreateReconcileTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_ResolveReconcileTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveReconcileTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).ResolveReconcileTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_ResolveReconcileTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).ResolveReconcileTask(ctx, req.(*ResolveReconcileTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_ListReconcileTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReconcileTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).ListReconcileTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_ListReconcileTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).ListReconcileTask(ctx, req.(*ListReconcileTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Finance_ServiceDesc is the grpc.ServiceDesc for Finance service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Finance_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finance.Finance",
	HandlerType: (*FinanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Finance_Ping_Handler,
		},
		{
			MethodName: "CreatePayment",
			Handler:    _Finance_CreatePayment_Handler,
		},
		{
			MethodName: "ConfirmPayment",
			Handler:    _Finance_ConfirmPayment_Handler,
		},
		{
			MethodName: "ApprovePayment",
			Handler:    _Finance_ApprovePayment_Handler,
		},
		{
			MethodName: "SettlePayment",
			Handler:    _Finance_SettlePayment_Handler,
		},
		{
			MethodName: "GetPayment",
			Handler:    _Finance_GetPayment_Handler,
		},
		{
			MethodName: "ListPayment",
			Handler:    _Finance_ListPayment_Handler,
		},
		{
			MethodName: "WechatPayURL",
			Handler:    _Finance_WechatPayURL_Handler,
		},
		{
			MethodName: "WechatCallback",
			Handler:    _Finance_WechatCallback_Handler,
		},
		{
			MethodName: "AlipayPayURL",
			Handler:    _Finance_AlipayPayURL_Handler,
		},
		{
			MethodName: "AlipayCallback",
			Handler:    _Finance_AlipayCallback_Handler,
		},
		{
			MethodName: "CreateRefund",
			Handler:    _Finance_CreateRefund_Handler,
		},
		{
			MethodName: "ListRefund",
			Handler:    _Finance_ListRefund_Handler,
		},
		{
			MethodName: "IssueInvoice",
			Handler:    _Finance_IssueInvoice_Handler,
		},
		{
			MethodName: "ReverseInvoice",
			Handler:    _Finance_ReverseInvoice_Handler,
		},
		{
			MethodName: "ListInvoice",
			Handler:    _Finance_ListInvoice_Handler,
		},
		{
			MethodName: "CreateReconcileTask",
			Handler:    _Finance_CreateReconcileTask_Handler,
		},
		{
			MethodName: "ResolveReconcileTask",
			Handler:    _Finance_ResolveReconcileTask_Handler,
		},
		{
			MethodName: "ListReconcileTask",
			Handler:    _Finance_ListReconcileTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/finance/pb/finance.proto",
}
