// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: inventory.proto

package inventory

import (
	"context"

	"micro-server/services/inventory/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApproveStocktakeReq      = pb.ApproveStocktakeReq
	ApproveStocktakeResp     = pb.ApproveStocktakeResp
	CreateStocktakeReq       = pb.CreateStocktakeReq
	CreateStocktakeResp      = pb.CreateStocktakeResp
	CreateWarehouseReq       = pb.CreateWarehouseReq
	CreateWarehouseResp      = pb.CreateWarehouseResp
	DeductLockedReq          = pb.DeductLockedReq
	DeductLockedResp         = pb.DeductLockedResp
	GetInventoryReq          = pb.GetInventoryReq
	GetInventoryResp         = pb.GetInventoryResp
	GetStocktakeReq          = pb.GetStocktakeReq
	GetStocktakeResp         = pb.GetStocktakeResp
	InventoryItem            = pb.InventoryItem
	ListInventoryReq         = pb.ListInventoryReq
	ListInventoryResp        = pb.ListInventoryResp
	ListStockRecordReq       = pb.ListStockRecordReq
	ListStockRecordResp      = pb.ListStockRecordResp
	ListStocktakeReq         = pb.ListStocktakeReq
	ListStocktakeResp        = pb.ListStocktakeResp
	ListWarehouseReq         = pb.ListWarehouseReq
	ListWarehouseResp        = pb.ListWarehouseResp
	PingReq                  = pb.PingReq
	PingResp                 = pb.PingResp
	ReleaseReq               = pb.ReleaseReq
	ReleaseResp              = pb.ReleaseResp
	ReserveReq               = pb.ReserveReq
	ReserveResp              = pb.ReserveResp
	SpareOutReq              = pb.SpareOutReq
	SpareOutResp             = pb.SpareOutResp
	SpareReturnReq           = pb.SpareReturnReq
	SpareReturnResp          = pb.SpareReturnResp
	StockInReq               = pb.StockInReq
	StockInResp              = pb.StockInResp
	StockRecordItem          = pb.StockRecordItem
	StocktakeItem            = pb.StocktakeItem
	StocktakeRecord          = pb.StocktakeRecord
	SubmitStocktakeCountItem = pb.SubmitStocktakeCountItem
	SubmitStocktakeCountReq  = pb.SubmitStocktakeCountReq
	SubmitStocktakeCountResp = pb.SubmitStocktakeCountResp
	WarehouseItem            = pb.WarehouseItem

	Inventory interface {
		Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
		// ---- 仓库 ----
		CreateWarehouse(ctx context.Context, in *CreateWarehouseReq, opts ...grpc.CallOption) (*CreateWarehouseResp, error)
		ListWarehouse(ctx context.Context, in *ListWarehouseReq, opts ...grpc.CallOption) (*ListWarehouseResp, error)
		// ---- 库存变动 ----
		StockIn(ctx context.Context, in *StockInReq, opts ...grpc.CallOption) (*StockInResp, error)
		Reserve(ctx context.Context, in *ReserveReq, opts ...grpc.CallOption) (*ReserveResp, error)
		Release(ctx context.Context, in *ReleaseReq, opts ...grpc.CallOption) (*ReleaseResp, error)
		DeductLocked(ctx context.Context, in *DeductLockedReq, opts ...grpc.CallOption) (*DeductLockedResp, error)
		SpareOut(ctx context.Context, in *SpareOutReq, opts ...grpc.CallOption) (*SpareOutResp, error)
		SpareReturn(ctx context.Context, in *SpareReturnReq, opts ...grpc.CallOption) (*SpareReturnResp, error)
		// ---- 库存查询 ----
		GetInventory(ctx context.Context, in *GetInventoryReq, opts ...grpc.CallOption) (*GetInventoryResp, error)
		ListInventory(ctx context.Context, in *ListInventoryReq, opts ...grpc.CallOption) (*ListInventoryResp, error)
		ListStockRecord(ctx context.Context, in *ListStockRecordReq, opts ...grpc.CallOption) (*ListStockRecordResp, error)
		// ---- 盘点（差异审批 + 账面调整有流水，FR-INV-007）----
		CreateStocktake(ctx context.Context, in *CreateStocktakeReq, opts ...grpc.CallOption) (*CreateStocktakeResp, error)
		SubmitStocktakeCount(ctx context.Context, in *SubmitStocktakeCountReq, opts ...grpc.CallOption) (*SubmitStocktakeCountResp, error)
		ApproveStocktake(ctx context.Context, in *ApproveStocktakeReq, opts ...grpc.CallOption) (*ApproveStocktakeResp, error)
		ListStocktake(ctx context.Context, in *ListStocktakeReq, opts ...grpc.CallOption) (*ListStocktakeResp, error)
		GetStocktake(ctx context.Context, in *GetStocktakeReq, opts ...grpc.CallOption) (*GetStocktakeResp, error)
	}

	defaultInventory struct {
		cli zrpc.Client
	}
)

func NewInventory(cli zrpc.Client) Inventory {
	return &defaultInventory{
		cli: cli,
	}
}

func (m *defaultInventory) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	client := pb.NewInventoryClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

// ---- 仓库 ----
func (m *defaultInventory) CreateWarehouse(ctx context.Context, in *CreateWarehouseReq, opts ...grpc.CallOption) (*CreateWarehouseResp, error) {
	client := pb.NewInventoryClient(m.cli.Conn())
	return client.CreateWarehouse(ctx, in, opts...)
}

func (m *defaultInventory) ListWarehouse(ctx context.Context, in *ListWarehouseReq, opts ...grpc.CallOption) (*ListWarehouseResp, error) {
	client := pb.NewInventoryClient(m.cli.Conn())
	return client.ListWarehouse(ctx, in, opts...)
}

// ---- 库存变动 ----
func (m *defaultInventory) StockIn(ctx context.Context, in *StockInReq, opts ...grpc.CallOption) (*StockInResp, error) {
	client := pb.NewInventoryClient(m.cli.Conn())
	return client.StockIn(ctx, in, opts...)
}

func (m *defaultInventory) Reserve(ctx context.Context, in *ReserveReq, opts ...grpc.CallOption) (*ReserveResp, error) {
	client := pb.NewInventoryClient(m.cli.Conn())
	return client.Reserve(ctx, in, opts...)
}

func (m *defaultInventory) Release(ctx context.Context, in *ReleaseReq, opts ...grpc.CallOption) (*ReleaseResp, error) {
	client := pb.NewInventoryClient(m.cli.Conn())
	return client.Release(ctx, in, opts...)
}

func (m *defaultInventory) DeductLocked(ctx context.Context, in *DeductLockedReq, opts ...grpc.CallOption) (*DeductLockedResp, error) {
	client := pb.NewInventoryClient(m.cli.Conn())
	return client.DeductLocked(ctx, in, opts...)
}

func (m *defaultInventory) SpareOut(ctx context.Context, in *SpareOutReq, opts ...grpc.CallOption) (*SpareOutResp, error) {
	client := pb.NewInventoryClient(m.cli.Conn())
	return client.SpareOut(ctx, in, opts...)
}

func (m *defaultInventory) SpareReturn(ctx context.Context, in *SpareReturnReq, opts ...grpc.CallOption) (*SpareReturnResp, error) {
	client := pb.NewInventoryClient(m.cli.Conn())
	return client.SpareReturn(ctx, in, opts...)
}

// ---- 库存查询 ----
func (m *defaultInventory) GetInventory(ctx context.Context, in *GetInventoryReq, opts ...grpc.CallOption) (*GetInventoryResp, error) {
	client := pb.NewInventoryClient(m.cli.Conn())
	return client.GetInventory(ctx, in, opts...)
}

func (m *defaultInventory) ListInventory(ctx context.Context, in *ListInventoryReq, opts ...grpc.CallOption) (*ListInventoryResp, error) {
	client := pb.NewInventoryClient(m.cli.Conn())
	return client.ListInventory(ctx, in, opts...)
}

func (m *defaultInventory) ListStockRecord(ctx context.Context, in *ListStockRecordReq, opts ...grpc.CallOption) (*ListStockRecordResp, error) {
	client := pb.NewInventoryClient(m.cli.Conn())
	return client.ListStockRecord(ctx, in, opts...)
}

// ---- 盘点（差异审批 + 账面调整有流水，FR-INV-007）----
func (m *defaultInventory) CreateStocktake(ctx context.Context, in *CreateStocktakeReq, opts ...grpc.CallOption) (*CreateStocktakeResp, error) {
	client := pb.NewInventoryClient(m.cli.Conn())
	return client.CreateStocktake(ctx, in, opts...)
}

func (m *defaultInventory) SubmitStocktakeCount(ctx context.Context, in *SubmitStocktakeCountReq, opts ...grpc.CallOption) (*SubmitStocktakeCountResp, error) {
	client := pb.NewInventoryClient(m.cli.Conn())
	return client.SubmitStocktakeCount(ctx, in, opts...)
}

func (m *defaultInventory) ApproveStocktake(ctx context.Context, in *ApproveStocktakeReq, opts ...grpc.CallOption) (*ApproveStocktakeResp, error) {
	client := pb.NewInventoryClient(m.cli.Conn())
	return client.ApproveStocktake(ctx, in, opts...)
}

func (m *defaultInventory) ListStocktake(ctx context.Context, in *ListStocktakeReq, opts ...grpc.CallOption) (*ListStocktakeResp, error) {
	client := pb.NewInventoryClient(m.cli.Conn())
	return client.ListStocktake(ctx, in, opts...)
}

func (m *defaultInventory) GetStocktake(ctx context.Context, in *GetStocktakeReq, opts ...grpc.CallOption) (*GetStocktakeResp, error) {
	client := pb.NewInventoryClient(m.cli.Conn())
	return client.GetStocktake(ctx, in, opts...)
}
