// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.4
// source: pb/audit.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_pb_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_pb_audit_proto_rawDescGZIP(), []int{0}
}

type PingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResp) Reset() {
	*x = PingResp{}
	mi := &file_pb_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResp) ProtoMessage() {}

func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) {
	return file_pb_audit_proto_rawDescGZIP(), []int{1}
}

func (x *PingResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type AuditLogItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         int64                  `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Uid           int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	TargetType    string                 `protobuf:"bytes,5,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      string                 `protobuf:"bytes,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	BeforeJson    string                 `protobuf:"bytes,7,opt,name=before_json,json=beforeJson,proto3" json:"before_json,omitempty"`
	AfterJson     string                 `protobuf:"bytes,8,opt,name=after_json,json=afterJson,proto3" json:"after_json,omitempty"`
	Result        string                 `protobuf:"bytes,9,opt,name=result,proto3" json:"result,omitempty"`
	Client        string                 `protobuf:"bytes,10,opt,name=client,proto3" json:"client,omitempty"`
	OnBehalfOf    int64                  `protobuf:"varint,11,opt,name=on_behalf_of,json=onBehalfOf,proto3" json:"on_behalf_of,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // UnixMilli
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogItem) Reset() {
	*x = AuditLogItem{}
	mi := &file_pb_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogItem) ProtoMessage() {}

func (x *AuditLogItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogItem.ProtoReflect.Descriptor instead.
func (*AuditLogItem) Descriptor() ([]byte, []int) {
	return file_pb_audit_proto_rawDescGZIP(), []int{2}
}

func (x *AuditLogItem) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *AuditLogItem) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AuditLogItem) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AuditLogItem) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLogItem) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *AuditLogItem) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *AuditLogItem) GetBeforeJson() string {
	if x != nil {
		return x.BeforeJson
	}
	return ""
}

func (x *AuditLogItem) GetAfterJson() string {
	if x != nil {
		return x.AfterJson
	}
	return ""
}

func (x *AuditLogItem) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AuditLogItem) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *AuditLogItem) GetOnBehalfOf() int64 {
	if x != nil {
		return x.OnBehalfOf
	}
	return 0
}

func (x *AuditLogItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type WriteLogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	TargetType    string                 `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      string                 `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	BeforeJson    string                 `protobuf:"bytes,5,opt,name=before_json,json=beforeJson,proto3" json:"before_json,omitempty"`
	AfterJson     string                 `protobuf:"bytes,6,opt,name=after_json,json=afterJson,proto3" json:"after_json,omitempty"`
	Result        string                 `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"` // OK/FAIL
	Client        string                 `protobuf:"bytes,8,opt,name=client,proto3" json:"client,omitempty"`
	OnBehalfOf    int64                  `protobuf:"varint,9,opt,name=on_behalf_of,json=onBehalfOf,proto3" json:"on_behalf_of,omitempty"`
	DetailJson    string                 `protobuf:"bytes,10,opt,name=detail_json,json=detailJson,proto3" json:"detail_json,omitempty"`
	TraceId       string                 `protobuf:"bytes,11,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	TenantId      int64                  `protobuf:"varint,12,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // BFF 已注入 ctx 时 Logic 优先 ctx（后台作业显式传）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteLogReq) Reset() {
	*x = WriteLogReq{}
	mi := &file_pb_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteLogReq) ProtoMessage() {}

func (x *WriteLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteLogReq.ProtoReflect.Descriptor instead.
func (*WriteLogReq) Descriptor() ([]byte, []int) {
	return file_pb_audit_proto_rawDescGZIP(), []int{3}
}

func (x *WriteLogReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *WriteLogReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *WriteLogReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *WriteLogReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *WriteLogReq) GetBeforeJson() string {
	if x != nil {
		return x.BeforeJson
	}
	return ""
}

func (x *WriteLogReq) GetAfterJson() string {
	if x != nil {
		return x.AfterJson
	}
	return ""
}

func (x *WriteLogReq) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *WriteLogReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *WriteLogReq) GetOnBehalfOf() int64 {
	if x != nil {
		return x.OnBehalfOf
	}
	return 0
}

func (x *WriteLogReq) GetDetailJson() string {
	if x != nil {
		return x.DetailJson
	}
	return ""
}

func (x *WriteLogReq) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *WriteLogReq) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type WriteLogResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         int64                  `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteLogResp) Reset() {
	*x = WriteLogResp{}
	mi := &file_pb_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteLogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteLogResp) ProtoMessage() {}

func (x *WriteLogResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteLogResp.ProtoReflect.Descriptor instead.
func (*WriteLogResp) Descriptor() ([]byte, []int) {
	return file_pb_audit_proto_rawDescGZIP(), []int{4}
}

func (x *WriteLogResp) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

type ListLogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // 空 = 全部
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`      // 0 = 全部
	TargetType    string                 `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      string                 `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Page          int64                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogReq) Reset() {
	*x = ListLogReq{}
	mi := &file_pb_audit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogReq) ProtoMessage() {}

func (x *ListLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_audit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogReq.ProtoReflect.Descriptor instead.
func (*ListLogReq) Descriptor() ([]byte, []int) {
	return file_pb_audit_proto_rawDescGZIP(), []int{5}
}

func (x *ListLogReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ListLogReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ListLogReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *ListLogReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ListLogReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLogReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListLogResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AuditLogItem        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogResp) Reset() {
	*x = ListLogResp{}
	mi := &file_pb_audit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogResp) ProtoMessage() {}

func (x *ListLogResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_audit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogResp.ProtoReflect.Descriptor instead.
func (*ListLogResp) Descriptor() ([]byte, []int) {
	return file_pb_audit_proto_rawDescGZIP(), []int{6}
}

func (x *ListLogResp) GetList() []*AuditLogItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListLogResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CmdAuditItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdAuditId    int64                  `protobuf:"varint,1,opt,name=cmd_audit_id,json=cmdAuditId,proto3" json:"cmd_audit_id,omitempty"`
	CmdId         string                 `protobuf:"bytes,2,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	Sn            string                 `protobuf:"bytes,3,opt,name=sn,proto3" json:"sn,omitempty"`
	Uid           int64                  `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,6,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Result        string                 `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	TraceId       string                 `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdAuditItem) Reset() {
	*x = CmdAuditItem{}
	mi := &file_pb_audit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdAuditItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdAuditItem) ProtoMessage() {}

func (x *CmdAuditItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_audit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdAuditItem.ProtoReflect.Descriptor instead.
func (*CmdAuditItem) Descriptor() ([]byte, []int) {
	return file_pb_audit_proto_rawDescGZIP(), []int{7}
}

func (x *CmdAuditItem) GetCmdAuditId() int64 {
	if x != nil {
		return x.CmdAuditId
	}
	return 0
}

func (x *CmdAuditItem) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *CmdAuditItem) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *CmdAuditItem) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CmdAuditItem) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CmdAuditItem) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *CmdAuditItem) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CmdAuditItem) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CmdAuditItem) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CmdAuditItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type WriteCmdLogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdId         string                 `protobuf:"bytes,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	Sn            string                 `protobuf:"bytes,2,opt,name=sn,proto3" json:"sn,omitempty"`
	Uid           int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,5,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Result        string                 `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	TraceId       string                 `protobuf:"bytes,8,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	TenantId      int64                  `protobuf:"varint,9,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteCmdLogReq) Reset() {
	*x = WriteCmdLogReq{}
	mi := &file_pb_audit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteCmdLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteCmdLogReq) ProtoMessage() {}

func (x *WriteCmdLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_audit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteCmdLogReq.ProtoReflect.Descriptor instead.
func (*WriteCmdLogReq) Descriptor() ([]byte, []int) {
	return file_pb_audit_proto_rawDescGZIP(), []int{8}
}

func (x *WriteCmdLogReq) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *WriteCmdLogReq) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *WriteCmdLogReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *WriteCmdLogReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *WriteCmdLogReq) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *WriteCmdLogReq) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *WriteCmdLogReq) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WriteCmdLogReq) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *WriteCmdLogReq) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type WriteCmdLogResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdAuditId    int64                  `protobuf:"varint,1,opt,name=cmd_audit_id,json=cmdAuditId,proto3" json:"cmd_audit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteCmdLogResp) Reset() {
	*x = WriteCmdLogResp{}
	mi := &file_pb_audit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteCmdLogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteCmdLogResp) ProtoMessage() {}

func (x *WriteCmdLogResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_audit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteCmdLogResp.ProtoReflect.Descriptor instead.
func (*WriteCmdLogResp) Descriptor() ([]byte, []int) {
	return file_pb_audit_proto_rawDescGZIP(), []int{9}
}

func (x *WriteCmdLogResp) GetCmdAuditId() int64 {
	if x != nil {
		return x.CmdAuditId
	}
	return 0
}

type ListCmdLogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`                    // 空 = 全部
	CmdId         string                 `protobuf:"bytes,2,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"` // 空 = 全部
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCmdLogReq) Reset() {
	*x = ListCmdLogReq{}
	mi := &file_pb_audit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCmdLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCmdLogReq) ProtoMessage() {}

func (x *ListCmdLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_audit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCmdLogReq.ProtoReflect.Descriptor instead.
func (*ListCmdLogReq) Descriptor() ([]byte, []int) {
	return file_pb_audit_proto_rawDescGZIP(), []int{10}
}

func (x *ListCmdLogReq) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *ListCmdLogReq) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *ListCmdLogReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCmdLogReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListCmdLogResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*CmdAuditItem        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCmdLogResp) Reset() {
	*x = ListCmdLogResp{}
	mi := &file_pb_audit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCmdLogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCmdLogResp) ProtoMessage() {}

func (x *ListCmdLogResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_audit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCmdLogResp.ProtoReflect.Descriptor instead.
func (*ListCmdLogResp) Descriptor() ([]byte, []int) {
	return file_pb_audit_proto_rawDescGZIP(), []int{11}
}

func (x *ListCmdLogResp) GetList() []*CmdAuditItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListCmdLogResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_pb_audit_proto protoreflect.FileDescriptor

const file_pb_audit_proto_rawDesc = "" +
	"\n" +
	"\x0epb/audit.proto\x12\x05audit\"\t\n" +
	"\aPingReq\"\x1e\n" +
	"\bPingResp\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\"\xd9\x02\n" +
	"\fAuditLogItem\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\x03R\x05logId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1f\n" +
	"\vtarget_type\x18\x05 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x06 \x01(\tR\btargetId\x12\x1f\n" +
	"\vbefore_json\x18\a \x01(\tR\n" +
	"beforeJson\x12\x1d\n" +
	"\n" +
	"after_json\x18\b \x01(\tR\tafterJson\x12\x16\n" +
	"\x06result\x18\t \x01(\tR\x06result\x12\x16\n" +
	"\x06client\x18\n" +
	" \x01(\tR\x06client\x12 \n" +
	"\fon_behalf_of\x18\v \x01(\x03R\n" +
	"onBehalfOf\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x03R\tcreatedAt\"\xe0\x02\n" +
	"\vWriteLogReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\tR\btargetId\x12\x1f\n" +
	"\vbefore_json\x18\x05 \x01(\tR\n" +
	"beforeJson\x12\x1d\n" +
	"\n" +
	"after_json\x18\x06 \x01(\tR\tafterJson\x12\x16\n" +
	"\x06result\x18\a \x01(\tR\x06result\x12\x16\n" +
	"\x06client\x18\b \x01(\tR\x06client\x12 \n" +
	"\fon_behalf_of\x18\t \x01(\x03R\n" +
	"onBehalfOf\x12\x1f\n" +
	"\vdetail_json\x18\n" +
	" \x01(\tR\n" +
	"detailJson\x12\x19\n" +
	"\btrace_id\x18\v \x01(\tR\atraceId\x12\x1b\n" +
	"\ttenant_id\x18\f \x01(\x03R\btenantId\"%\n" +
	"\fWriteLogResp\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\x03R\x05logId\"\x9c\x01\n" +
	"\n" +
	"ListLogReq\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\tR\btargetId\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\"L\n" +
	"\vListLogResp\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.audit.AuditLogItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x8c\x02\n" +
	"\fCmdAuditItem\x12 \n" +
	"\fcmd_audit_id\x18\x01 \x01(\x03R\n" +
	"cmdAuditId\x12\x15\n" +
	"\x06cmd_id\x18\x02 \x01(\tR\x05cmdId\x12\x0e\n" +
	"\x02sn\x18\x03 \x01(\tR\x02sn\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x03R\x03uid\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12!\n" +
	"\fpayload_json\x18\x06 \x01(\tR\vpayloadJson\x12\x16\n" +
	"\x06result\x18\a \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\"\xea\x01\n" +
	"\x0eWriteCmdLogReq\x12\x15\n" +
	"\x06cmd_id\x18\x01 \x01(\tR\x05cmdId\x12\x0e\n" +
	"\x02sn\x18\x02 \x01(\tR\x02sn\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12!\n" +
	"\fpayload_json\x18\x05 \x01(\tR\vpayloadJson\x12\x16\n" +
	"\x06result\x18\x06 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12\x19\n" +
	"\btrace_id\x18\b \x01(\tR\atraceId\x12\x1b\n" +
	"\ttenant_id\x18\t \x01(\x03R\btenantId\"3\n" +
	"\x0fWriteCmdLogResp\x12 \n" +
	"\fcmd_audit_id\x18\x01 \x01(\x03R\n" +
	"cmdAuditId\"^\n" +
	"\rListCmdLogReq\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\x12\x15\n" +
	"\x06cmd_id\x18\x02 \x01(\tR\x05cmdId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"O\n" +
	"\x0eListCmdLogResp\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.audit.CmdAuditItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\x90\x02\n" +
	"\x05Audit\x12'\n" +
	"\x04Ping\x12\x0e.audit.PingReq\x1a\x0f.audit.PingResp\x123\n" +
	"\bWriteLog\x12\x12.audit.WriteLogReq\x1a\x13.audit.WriteLogResp\x120\n" +
	"\aListLog\x12\x11.audit.ListLogReq\x1a\x12.audit.ListLogResp\x12<\n" +
	"\vWriteCmdLog\x12\x15.audit.WriteCmdLogReq\x1a\x16.audit.WriteCmdLogResp\x129\n" +
	"\n" +
	"ListCmdLog\x12\x14.audit.ListCmdLogReq\x1a\x15.audit.ListCmdLogRespB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_audit_proto_rawDescOnce sync.Once
	file_pb_audit_proto_rawDescData []byte
)

func file_pb_audit_proto_rawDescGZIP() []byte {
	file_pb_audit_proto_rawDescOnce.Do(func() {
		file_pb_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_audit_proto_rawDesc), len(file_pb_audit_proto_rawDesc)))
	})
	return file_pb_audit_proto_rawDescData
}

var file_pb_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pb_audit_proto_goTypes = []any{
	(*PingReq)(nil),         // 0: audit.PingReq
	(*PingResp)(nil),        // 1: audit.PingResp
	(*AuditLogItem)(nil),    // 2: audit.AuditLogItem
	(*WriteLogReq)(nil),     // 3: audit.WriteLogReq
	(*WriteLogResp)(nil),    // 4: audit.WriteLogResp
	(*ListLogReq)(nil),      // 5: audit.ListLogReq
	(*ListLogResp)(nil),     // 6: audit.ListLogResp
	(*CmdAuditItem)(nil),    // 7: audit.CmdAuditItem
	(*WriteCmdLogReq)(nil),  // 8: audit.WriteCmdLogReq
	(*WriteCmdLogResp)(nil), // 9: audit.WriteCmdLogResp
	(*ListCmdLogReq)(nil),   // 10: audit.ListCmdLogReq
	(*ListCmdLogResp)(nil),  // 11: audit.ListCmdLogResp
}
var file_pb_audit_proto_depIdxs = []int32{
	2,  // 0: audit.ListLogResp.list:type_name -> audit.AuditLogItem
	7,  // 1: audit.ListCmdLogResp.list:type_name -> audit.CmdAuditItem
	0,  // 2: audit.Audit.Ping:input_type -> audit.PingReq
	3,  // 3: audit.Audit.WriteLog:input_type -> audit.WriteLogReq
	5,  // 4: audit.Audit.ListLog:input_type -> audit.ListLogReq
	8,  // 5: audit.Audit.WriteCmdLog:input_type -> audit.WriteCmdLogReq
	10, // 6: audit.Audit.ListCmdLog:input_type -> audit.ListCmdLogReq
	1,  // 7: audit.Audit.Ping:output_type -> audit.PingResp
	4,  // 8: audit.Audit.WriteLog:output_type -> audit.WriteLogResp
	6,  // 9: audit.Audit.ListLog:output_type -> audit.ListLogResp
	9,  // 10: audit.Audit.WriteCmdLog:output_type -> audit.WriteCmdLogResp
	11, // 11: audit.Audit.ListCmdLog:output_type -> audit.ListCmdLogResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_pb_audit_proto_init() }
func file_pb_audit_proto_init() {
	if File_pb_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_audit_proto_rawDesc), len(file_pb_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_audit_proto_goTypes,
		DependencyIndexes: file_pb_audit_proto_depIdxs,
		MessageInfos:      file_pb_audit_proto_msgTypes,
	}.Build()
	File_pb_audit_proto = out.File
	file_pb_audit_proto_goTypes = nil
	file_pb_audit_proto_depIdxs = nil
}
