// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	auditLogFieldNames          = builder.RawFieldNames(&AuditLog{})
	auditLogRows                = strings.Join(auditLogFieldNames, ",")
	auditLogRowsExpectAutoSet   = strings.Join(stringx.Remove(auditLogFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	auditLogRowsWithPlaceHolder = strings.Join(stringx.Remove(auditLogFieldNames, "`log_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAuditLogLogIdPrefix = "cache:auditLog:logId:"
)

type (
	auditLogModel interface {
		Insert(ctx context.Context, data *AuditLog) (sql.Result, error)
		FindOne(ctx context.Context, logId int64) (*AuditLog, error)
		Update(ctx context.Context, data *AuditLog) error
		Delete(ctx context.Context, logId int64) error
	}

	defaultAuditLogModel struct {
		sqlc.CachedConn
		table string
	}

	AuditLog struct {
		LogId      int64          `db:"log_id"`       // 雪花 ID
		TraceId    string         `db:"trace_id"`     // 链路 ID
		Uid        int64          `db:"uid"`          // 操作人 uid(0=系统)
		Action     string         `db:"action"`       // 动作(auth.login/user.create/...)
		TargetType sql.NullString `db:"target_type"`  // 目标类型(user/party/role...)
		TargetId   sql.NullString `db:"target_id"`    // 目标 ID(字符串,兼容多形态)
		BeforeJson sql.NullString `db:"before_json"`  // 变更前快照
		AfterJson  sql.NullString `db:"after_json"`   // 变更后快照
		Result     string         `db:"result"`       // OK/FAIL
		Client     sql.NullString `db:"client"`       // 来源端(ADMIN_WEB/OPS_APP...)
		OnBehalfOf sql.NullInt64  `db:"on_behalf_of"` // 被模拟人(模拟他人场景预留)
		DetailJson sql.NullString `db:"detail_json"`  // 扩展明细(登录 IP/UA 等)
		TenantId   int64          `db:"tenant_id"`    // 租户 ID
		CreatedAt  time.Time      `db:"created_at"`   // 发生时间(毫秒精度)
	}
)

func newAuditLogModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAuditLogModel {
	return &defaultAuditLogModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`audit_log`",
	}
}

func (m *defaultAuditLogModel) Delete(ctx context.Context, logId int64) error {
	auditLogLogIdKey := fmt.Sprintf("%s%v", cacheAuditLogLogIdPrefix, logId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `log_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, logId)
	}, auditLogLogIdKey)
	return err
}

func (m *defaultAuditLogModel) FindOne(ctx context.Context, logId int64) (*AuditLog, error) {
	auditLogLogIdKey := fmt.Sprintf("%s%v", cacheAuditLogLogIdPrefix, logId)
	var resp AuditLog
	err := m.QueryRowCtx(ctx, &resp, auditLogLogIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `log_id` = ? limit 1", auditLogRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, logId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuditLogModel) Insert(ctx context.Context, data *AuditLog) (sql.Result, error) {
	auditLogLogIdKey := fmt.Sprintf("%s%v", cacheAuditLogLogIdPrefix, data.LogId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, auditLogRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.LogId, data.TraceId, data.Uid, data.Action, data.TargetType, data.TargetId, data.BeforeJson, data.AfterJson, data.Result, data.Client, data.OnBehalfOf, data.DetailJson, data.TenantId)
	}, auditLogLogIdKey)
	return ret, err
}

func (m *defaultAuditLogModel) Update(ctx context.Context, data *AuditLog) error {
	auditLogLogIdKey := fmt.Sprintf("%s%v", cacheAuditLogLogIdPrefix, data.LogId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `log_id` = ?", m.table, auditLogRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TraceId, data.Uid, data.Action, data.TargetType, data.TargetId, data.BeforeJson, data.AfterJson, data.Result, data.Client, data.OnBehalfOf, data.DetailJson, data.TenantId, data.LogId)
	}, auditLogLogIdKey)
	return err
}

func (m *defaultAuditLogModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAuditLogLogIdPrefix, primary)
}

func (m *defaultAuditLogModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `log_id` = ? limit 1", auditLogRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAuditLogModel) tableName() string {
	return m.table
}
