// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	stationTopologyFieldNames          = builder.RawFieldNames(&StationTopology{})
	stationTopologyRows                = strings.Join(stationTopologyFieldNames, ",")
	stationTopologyRowsExpectAutoSet   = strings.Join(stringx.Remove(stationTopologyFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	stationTopologyRowsWithPlaceHolder = strings.Join(stringx.Remove(stationTopologyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheStationTopologyIdPrefix               = "cache:stationTopology:id:"
	cacheStationTopologyStationIdVersionPrefix = "cache:stationTopology:stationId:version:"
)

type (
	stationTopologyModel interface {
		Insert(ctx context.Context, data *StationTopology) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*StationTopology, error)
		FindOneByStationIdVersion(ctx context.Context, stationId int64, version int64) (*StationTopology, error)
		Update(ctx context.Context, data *StationTopology) error
		Delete(ctx context.Context, id int64) error
	}

	defaultStationTopologyModel struct {
		sqlc.CachedConn
		table string
	}

	StationTopology struct {
		Id        int64         `db:"id"`         // 雪花 ID
		StationId int64         `db:"station_id"` // 场站
		Version   int64         `db:"version"`    // 版本号（递增）
		Nodes     string        `db:"nodes"`      // 节点（React Flow nodes 形状）
		Edges     string        `db:"edges"`      // 边（React Flow edges 形状）
		TenantId  int64         `db:"tenant_id"`  // 租户 ID
		CreatedAt time.Time     `db:"created_at"` // 创建时间
		CreatedBy sql.NullInt64 `db:"created_by"` // 创建人 uid
		UpdatedAt time.Time     `db:"updated_at"` // 更新时间
		DeletedAt sql.NullTime  `db:"deleted_at"` // 软删标记(NULL=有效)
	}
)

func newStationTopologyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultStationTopologyModel {
	return &defaultStationTopologyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`station_topology`",
	}
}

func (m *defaultStationTopologyModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	stationTopologyIdKey := fmt.Sprintf("%s%v", cacheStationTopologyIdPrefix, id)
	stationTopologyStationIdVersionKey := fmt.Sprintf("%s%v:%v", cacheStationTopologyStationIdVersionPrefix, data.StationId, data.Version)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, stationTopologyIdKey, stationTopologyStationIdVersionKey)
	return err
}

func (m *defaultStationTopologyModel) FindOne(ctx context.Context, id int64) (*StationTopology, error) {
	stationTopologyIdKey := fmt.Sprintf("%s%v", cacheStationTopologyIdPrefix, id)
	var resp StationTopology
	err := m.QueryRowCtx(ctx, &resp, stationTopologyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", stationTopologyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStationTopologyModel) FindOneByStationIdVersion(ctx context.Context, stationId int64, version int64) (*StationTopology, error) {
	stationTopologyStationIdVersionKey := fmt.Sprintf("%s%v:%v", cacheStationTopologyStationIdVersionPrefix, stationId, version)
	var resp StationTopology
	err := m.QueryRowIndexCtx(ctx, &resp, stationTopologyStationIdVersionKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `station_id` = ? and `version` = ? limit 1", stationTopologyRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, stationId, version); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStationTopologyModel) Insert(ctx context.Context, data *StationTopology) (sql.Result, error) {
	stationTopologyIdKey := fmt.Sprintf("%s%v", cacheStationTopologyIdPrefix, data.Id)
	stationTopologyStationIdVersionKey := fmt.Sprintf("%s%v:%v", cacheStationTopologyStationIdVersionPrefix, data.StationId, data.Version)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, stationTopologyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.StationId, data.Version, data.Nodes, data.Edges, data.TenantId, data.CreatedBy, data.DeletedAt)
	}, stationTopologyIdKey, stationTopologyStationIdVersionKey)
	return ret, err
}

func (m *defaultStationTopologyModel) Update(ctx context.Context, newData *StationTopology) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	stationTopologyIdKey := fmt.Sprintf("%s%v", cacheStationTopologyIdPrefix, data.Id)
	stationTopologyStationIdVersionKey := fmt.Sprintf("%s%v:%v", cacheStationTopologyStationIdVersionPrefix, data.StationId, data.Version)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, stationTopologyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.StationId, newData.Version, newData.Nodes, newData.Edges, newData.TenantId, newData.CreatedBy, newData.DeletedAt, newData.Id)
	}, stationTopologyIdKey, stationTopologyStationIdVersionKey)
	return err
}

func (m *defaultStationTopologyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheStationTopologyIdPrefix, primary)
}

func (m *defaultStationTopologyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", stationTopologyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultStationTopologyModel) tableName() string {
	return m.table
}
