// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: order.proto

package order

import (
	"context"

	"micro-server/services/order/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddShipmentTraceReq       = pb.AddShipmentTraceReq
	AddShipmentTraceResp      = pb.AddShipmentTraceResp
	ApproveReturnOrderReq     = pb.ApproveReturnOrderReq
	ApproveReturnOrderResp    = pb.ApproveReturnOrderResp
	CancelOrderReq            = pb.CancelOrderReq
	CancelOrderResp           = pb.CancelOrderResp
	ConfirmShipmentSignedReq  = pb.ConfirmShipmentSignedReq
	ConfirmShipmentSignedResp = pb.ConfirmShipmentSignedResp
	CreateOrderReq            = pb.CreateOrderReq
	CreateOrderResp           = pb.CreateOrderResp
	CreateReturnOrderReq      = pb.CreateReturnOrderReq
	CreateReturnOrderResp     = pb.CreateReturnOrderResp
	CreateShipmentReq         = pb.CreateShipmentReq
	CreateShipmentResp        = pb.CreateShipmentResp
	GetOrderReq               = pb.GetOrderReq
	GetOrderResp              = pb.GetOrderResp
	GetSagaReq                = pb.GetSagaReq
	GetSagaResp               = pb.GetSagaResp
	ListOrderReq              = pb.ListOrderReq
	ListOrderResp             = pb.ListOrderResp
	OrderDetail               = pb.OrderDetail
	OrderItem                 = pb.OrderItem
	OrderItemInput            = pb.OrderItemInput
	PayOrderReq               = pb.PayOrderReq
	PayOrderResp              = pb.PayOrderResp
	PingReq                   = pb.PingReq
	PingResp                  = pb.PingResp
	RetrySagaReq              = pb.RetrySagaReq
	RetrySagaResp             = pb.RetrySagaResp
	ReturnItemInput           = pb.ReturnItemInput
	SagaDetail                = pb.SagaDetail
	SagaStep                  = pb.SagaStep
	ShipmentItemInput         = pb.ShipmentItemInput
	SumPaidSalesReq           = pb.SumPaidSalesReq
	SumPaidSalesResp          = pb.SumPaidSalesResp

	Order interface {
		Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
		// ---- 订单 ----
		CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
		GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error)
		ListOrder(ctx context.Context, in *ListOrderReq, opts ...grpc.CallOption) (*ListOrderResp, error)
		PayOrder(ctx context.Context, in *PayOrderReq, opts ...grpc.CallOption) (*PayOrderResp, error)
		CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error)
		// ---- Saga ----
		GetSaga(ctx context.Context, in *GetSagaReq, opts ...grpc.CallOption) (*GetSagaResp, error)
		RetrySaga(ctx context.Context, in *RetrySagaReq, opts ...grpc.CallOption) (*RetrySagaResp, error)
		// ---- 退货（FR-ORD-004：申请/审核/退款联动）----
		CreateReturnOrder(ctx context.Context, in *CreateReturnOrderReq, opts ...grpc.CallOption) (*CreateReturnOrderResp, error)
		ApproveReturnOrder(ctx context.Context, in *ApproveReturnOrderReq, opts ...grpc.CallOption) (*ApproveReturnOrderResp, error)
		// ---- 发货单与物流轨迹（FR-ORD-005，轨迹手工录入基线）----
		CreateShipment(ctx context.Context, in *CreateShipmentReq, opts ...grpc.CallOption) (*CreateShipmentResp, error)
		AddShipmentTrace(ctx context.Context, in *AddShipmentTraceReq, opts ...grpc.CallOption) (*AddShipmentTraceResp, error)
		ConfirmShipmentSigned(ctx context.Context, in *ConfirmShipmentSignedReq, opts ...grpc.CallOption) (*ConfirmShipmentSignedResp, error)
		// ---- 统计 ----
		SumPaidSales(ctx context.Context, in *SumPaidSalesReq, opts ...grpc.CallOption) (*SumPaidSalesResp, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

func (m *defaultOrder) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

// ---- 订单 ----
func (m *defaultOrder) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultOrder) GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}

func (m *defaultOrder) ListOrder(ctx context.Context, in *ListOrderReq, opts ...grpc.CallOption) (*ListOrderResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.ListOrder(ctx, in, opts...)
}

func (m *defaultOrder) PayOrder(ctx context.Context, in *PayOrderReq, opts ...grpc.CallOption) (*PayOrderResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.PayOrder(ctx, in, opts...)
}

func (m *defaultOrder) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}

// ---- Saga ----
func (m *defaultOrder) GetSaga(ctx context.Context, in *GetSagaReq, opts ...grpc.CallOption) (*GetSagaResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.GetSaga(ctx, in, opts...)
}

func (m *defaultOrder) RetrySaga(ctx context.Context, in *RetrySagaReq, opts ...grpc.CallOption) (*RetrySagaResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.RetrySaga(ctx, in, opts...)
}

// ---- 退货（FR-ORD-004：申请/审核/退款联动）----
func (m *defaultOrder) CreateReturnOrder(ctx context.Context, in *CreateReturnOrderReq, opts ...grpc.CallOption) (*CreateReturnOrderResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.CreateReturnOrder(ctx, in, opts...)
}

func (m *defaultOrder) ApproveReturnOrder(ctx context.Context, in *ApproveReturnOrderReq, opts ...grpc.CallOption) (*ApproveReturnOrderResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.ApproveReturnOrder(ctx, in, opts...)
}

// ---- 发货单与物流轨迹（FR-ORD-005，轨迹手工录入基线）----
func (m *defaultOrder) CreateShipment(ctx context.Context, in *CreateShipmentReq, opts ...grpc.CallOption) (*CreateShipmentResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.CreateShipment(ctx, in, opts...)
}

func (m *defaultOrder) AddShipmentTrace(ctx context.Context, in *AddShipmentTraceReq, opts ...grpc.CallOption) (*AddShipmentTraceResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.AddShipmentTrace(ctx, in, opts...)
}

func (m *defaultOrder) ConfirmShipmentSigned(ctx context.Context, in *ConfirmShipmentSignedReq, opts ...grpc.CallOption) (*ConfirmShipmentSignedResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.ConfirmShipmentSigned(ctx, in, opts...)
}

// ---- 统计 ----
func (m *defaultOrder) SumPaidSales(ctx context.Context, in *SumPaidSalesReq, opts ...grpc.CallOption) (*SumPaidSalesResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.SumPaidSales(ctx, in, opts...)
}
