// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	priceFieldNames          = builder.RawFieldNames(&Price{})
	priceRows                = strings.Join(priceFieldNames, ",")
	priceRowsExpectAutoSet   = strings.Join(stringx.Remove(priceFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	priceRowsWithPlaceHolder = strings.Join(stringx.Remove(priceFieldNames, "`price_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePricePriceIdPrefix = "cache:price:priceId:"
)

type (
	priceModel interface {
		Insert(ctx context.Context, data *Price) (sql.Result, error)
		FindOne(ctx context.Context, priceId int64) (*Price, error)
		Update(ctx context.Context, data *Price) error
		Delete(ctx context.Context, priceId int64) error
	}

	defaultPriceModel struct {
		sqlc.CachedConn
		table string
	}

	Price struct {
		PriceId   int64         `db:"price_id"`   // 雪花 ID
		SkuId     int64         `db:"sku_id"`     // 归属 SKU
		PriceType string        `db:"price_type"` // RETAIL 零售价/DEALER 经销商价/TIER 阶梯价
		TierQty   int64         `db:"tier_qty"`   // 阶梯起量(仅 TIER 有意义)
		Amount    float64       `db:"amount"`     // 价格(元)
		Version   int64         `db:"version"`    // 版本号(同 sku+type+tier_qty 内自增)
		TenantId  int64         `db:"tenant_id"`  // 租户 ID
		CreatedAt time.Time     `db:"created_at"` // 创建时间
		CreatedBy sql.NullInt64 `db:"created_by"` // 创建人 uid
		UpdatedAt time.Time     `db:"updated_at"` // 更新时间
		UpdatedBy sql.NullInt64 `db:"updated_by"` // 更新人 uid
		DeletedAt sql.NullTime  `db:"deleted_at"` // 软删标记(NULL=有效)
	}
)

func newPriceModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPriceModel {
	return &defaultPriceModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`price`",
	}
}

func (m *defaultPriceModel) Delete(ctx context.Context, priceId int64) error {
	pricePriceIdKey := fmt.Sprintf("%s%v", cachePricePriceIdPrefix, priceId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `price_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, priceId)
	}, pricePriceIdKey)
	return err
}

func (m *defaultPriceModel) FindOne(ctx context.Context, priceId int64) (*Price, error) {
	pricePriceIdKey := fmt.Sprintf("%s%v", cachePricePriceIdPrefix, priceId)
	var resp Price
	err := m.QueryRowCtx(ctx, &resp, pricePriceIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `price_id` = ? limit 1", priceRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, priceId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPriceModel) Insert(ctx context.Context, data *Price) (sql.Result, error) {
	pricePriceIdKey := fmt.Sprintf("%s%v", cachePricePriceIdPrefix, data.PriceId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, priceRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PriceId, data.SkuId, data.PriceType, data.TierQty, data.Amount, data.Version, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt)
	}, pricePriceIdKey)
	return ret, err
}

func (m *defaultPriceModel) Update(ctx context.Context, data *Price) error {
	pricePriceIdKey := fmt.Sprintf("%s%v", cachePricePriceIdPrefix, data.PriceId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `price_id` = ?", m.table, priceRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.SkuId, data.PriceType, data.TierQty, data.Amount, data.Version, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt, data.PriceId)
	}, pricePriceIdKey)
	return err
}

func (m *defaultPriceModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePricePriceIdPrefix, primary)
}

func (m *defaultPriceModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `price_id` = ? limit 1", priceRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPriceModel) tableName() string {
	return m.table
}
