// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productFieldNames          = builder.RawFieldNames(&Product{})
	productRows                = strings.Join(productFieldNames, ",")
	productRowsExpectAutoSet   = strings.Join(stringx.Remove(productFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productRowsWithPlaceHolder = strings.Join(stringx.Remove(productFieldNames, "`product_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheProductProductIdPrefix = "cache:product:productId:"
)

type (
	productModel interface {
		Insert(ctx context.Context, data *Product) (sql.Result, error)
		FindOne(ctx context.Context, productId int64) (*Product, error)
		Update(ctx context.Context, data *Product) error
		Delete(ctx context.Context, productId int64) error
	}

	defaultProductModel struct {
		sqlc.CachedConn
		table string
	}

	Product struct {
		ProductId int64          `db:"product_id"` // 雪花 ID
		Name      string         `db:"name"`       // 商品名称
		Category  sql.NullString `db:"category"`   // 分类
		Status    int64          `db:"status"`     // 1 上架/2 下架
		Remark    sql.NullString `db:"remark"`     // 备注
		TenantId  int64          `db:"tenant_id"`  // 租户 ID
		CreatedAt time.Time      `db:"created_at"` // 创建时间
		CreatedBy sql.NullInt64  `db:"created_by"` // 创建人 uid
		UpdatedAt time.Time      `db:"updated_at"` // 更新时间
		UpdatedBy sql.NullInt64  `db:"updated_by"` // 更新人 uid
		DeletedAt sql.NullTime   `db:"deleted_at"` // 软删标记(NULL=有效)
	}
)

func newProductModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultProductModel {
	return &defaultProductModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`product`",
	}
}

func (m *defaultProductModel) Delete(ctx context.Context, productId int64) error {
	productProductIdKey := fmt.Sprintf("%s%v", cacheProductProductIdPrefix, productId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `product_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, productId)
	}, productProductIdKey)
	return err
}

func (m *defaultProductModel) FindOne(ctx context.Context, productId int64) (*Product, error) {
	productProductIdKey := fmt.Sprintf("%s%v", cacheProductProductIdPrefix, productId)
	var resp Product
	err := m.QueryRowCtx(ctx, &resp, productProductIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `product_id` = ? limit 1", productRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, productId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductModel) Insert(ctx context.Context, data *Product) (sql.Result, error) {
	productProductIdKey := fmt.Sprintf("%s%v", cacheProductProductIdPrefix, data.ProductId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, productRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ProductId, data.Name, data.Category, data.Status, data.Remark, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt)
	}, productProductIdKey)
	return ret, err
}

func (m *defaultProductModel) Update(ctx context.Context, data *Product) error {
	productProductIdKey := fmt.Sprintf("%s%v", cacheProductProductIdPrefix, data.ProductId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `product_id` = ?", m.table, productRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Category, data.Status, data.Remark, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt, data.ProductId)
	}, productProductIdKey)
	return err
}

func (m *defaultProductModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheProductProductIdPrefix, primary)
}

func (m *defaultProductModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `product_id` = ? limit 1", productRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultProductModel) tableName() string {
	return m.table
}
