// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	skuFieldNames          = builder.RawFieldNames(&Sku{})
	skuRows                = strings.Join(skuFieldNames, ",")
	skuRowsExpectAutoSet   = strings.Join(stringx.Remove(skuFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	skuRowsWithPlaceHolder = strings.Join(stringx.Remove(skuFieldNames, "`sku_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSkuSkuIdPrefix        = "cache:sku:skuId:"
	cacheSkuTenantIdCodePrefix = "cache:sku:tenantId:code:"
)

type (
	skuModel interface {
		Insert(ctx context.Context, data *Sku) (sql.Result, error)
		FindOne(ctx context.Context, skuId int64) (*Sku, error)
		FindOneByTenantIdCode(ctx context.Context, tenantId int64, code string) (*Sku, error)
		Update(ctx context.Context, data *Sku) error
		Delete(ctx context.Context, skuId int64) error
	}

	defaultSkuModel struct {
		sqlc.CachedConn
		table string
	}

	Sku struct {
		SkuId     int64          `db:"sku_id"`     // 雪花 ID
		ProductId int64          `db:"product_id"` // 归属商品
		Code      string         `db:"code"`       // SKU 编码(租户内唯一)
		Name      string         `db:"name"`       // SKU 名称
		Type      string         `db:"type"`       // STANDARD 标准品/EXT_WARRANTY 延保
		Spec      sql.NullString `db:"spec"`       // 规格参数 JSON
		Status    int64          `db:"status"`     // 1 上架/2 下架
		TenantId  int64          `db:"tenant_id"`  // 租户 ID
		CreatedAt time.Time      `db:"created_at"` // 创建时间
		CreatedBy sql.NullInt64  `db:"created_by"` // 创建人 uid
		UpdatedAt time.Time      `db:"updated_at"` // 更新时间
		UpdatedBy sql.NullInt64  `db:"updated_by"` // 更新人 uid
		DeletedAt sql.NullTime   `db:"deleted_at"` // 软删标记(NULL=有效)
	}
)

func newSkuModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSkuModel {
	return &defaultSkuModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sku`",
	}
}

func (m *defaultSkuModel) Delete(ctx context.Context, skuId int64) error {
	data, err := m.FindOne(ctx, skuId)
	if err != nil {
		return err
	}

	skuSkuIdKey := fmt.Sprintf("%s%v", cacheSkuSkuIdPrefix, skuId)
	skuTenantIdCodeKey := fmt.Sprintf("%s%v:%v", cacheSkuTenantIdCodePrefix, data.TenantId, data.Code)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `sku_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, skuId)
	}, skuSkuIdKey, skuTenantIdCodeKey)
	return err
}

func (m *defaultSkuModel) FindOne(ctx context.Context, skuId int64) (*Sku, error) {
	skuSkuIdKey := fmt.Sprintf("%s%v", cacheSkuSkuIdPrefix, skuId)
	var resp Sku
	err := m.QueryRowCtx(ctx, &resp, skuSkuIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `sku_id` = ? limit 1", skuRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, skuId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSkuModel) FindOneByTenantIdCode(ctx context.Context, tenantId int64, code string) (*Sku, error) {
	skuTenantIdCodeKey := fmt.Sprintf("%s%v:%v", cacheSkuTenantIdCodePrefix, tenantId, code)
	var resp Sku
	err := m.QueryRowIndexCtx(ctx, &resp, skuTenantIdCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `code` = ? limit 1", skuRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, code); err != nil {
			return nil, err
		}
		return resp.SkuId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSkuModel) Insert(ctx context.Context, data *Sku) (sql.Result, error) {
	skuSkuIdKey := fmt.Sprintf("%s%v", cacheSkuSkuIdPrefix, data.SkuId)
	skuTenantIdCodeKey := fmt.Sprintf("%s%v:%v", cacheSkuTenantIdCodePrefix, data.TenantId, data.Code)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, skuRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SkuId, data.ProductId, data.Code, data.Name, data.Type, data.Spec, data.Status, data.TenantId, data.CreatedBy, data.UpdatedBy, data.DeletedAt)
	}, skuSkuIdKey, skuTenantIdCodeKey)
	return ret, err
}

func (m *defaultSkuModel) Update(ctx context.Context, newData *Sku) error {
	data, err := m.FindOne(ctx, newData.SkuId)
	if err != nil {
		return err
	}

	skuSkuIdKey := fmt.Sprintf("%s%v", cacheSkuSkuIdPrefix, data.SkuId)
	skuTenantIdCodeKey := fmt.Sprintf("%s%v:%v", cacheSkuTenantIdCodePrefix, data.TenantId, data.Code)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `sku_id` = ?", m.table, skuRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ProductId, newData.Code, newData.Name, newData.Type, newData.Spec, newData.Status, newData.TenantId, newData.CreatedBy, newData.UpdatedBy, newData.DeletedAt, newData.SkuId)
	}, skuSkuIdKey, skuTenantIdCodeKey)
	return err
}

func (m *defaultSkuModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSkuSkuIdPrefix, primary)
}

func (m *defaultSkuModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `sku_id` = ? limit 1", skuRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSkuModel) tableName() string {
	return m.table
}
